import { FlatCompat } from "@eslint/eslintrc";
import noLiteralString from "./eslint-rules/no-literal-string.mjs";
import designTokens from "./eslint-rules/design-tokens.mjs";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: ["node_modules", ".next", "dist", "prisma/generated"],
  },
  {
    // Edit-time i18n backstop on surfaces already migrated to the shared
    // catalog: no hardcoded user-facing strings may reappear here. As each new
    // surface is converted, add its files to this glob (and regenerate the
    // ratchet baseline). Everything not yet listed is held by the repo-wide
    // ratchet test (tests/i18n-guard.test.ts) instead.
    files: [
      "src/app/(auth)/sign-in/sign-in-form.tsx",
      "src/app/(auth)/sign-up/sign-up-form.tsx",
      "src/app/(auth)/otp-verify-card.tsx",
      // Public booking funnel (student-facing).
      "src/app/b/[slug]/buy/page.tsx",
      "src/app/b/[slug]/buy/result/resend-sign-in-link.tsx",
      // Error boundaries + a handful of real no-English-branch fixes.
      "src/app/error.tsx",
      "src/app/(app)/error.tsx",
      "src/app/(student)/error.tsx",
      "src/app/b/[slug]/error.tsx",
      "src/app/r/notif-settings/[token]/page.tsx",
      "src/app/(app)/dashboard/students/[studentId]/insights-consent-control.tsx",
      // Full i18n sweep (dashboard/settings/student-portal/booking/components/admin/legal).
      "src/app/(app)/app-nav.tsx",
      "src/components/mobile-nav-panel.tsx",
      "src/components/report-problem-dialog.tsx",
      "src/components/report-problem-provider.tsx",
      "src/app/(app)/dashboard/calendar/page.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/call/page.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/content/page.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/focus-areas-card.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/lesson-notes-panel.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/lesson-summary-card.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/materials-panel.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/override-action.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/page.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/prepare-card.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/present/page.tsx",
      "src/app/(app)/dashboard/classes/[bookingId]/present/present-mode.tsx",
      "src/app/(app)/dashboard/classes/book/page.tsx",
      "src/app/(app)/dashboard/classes/book/student-picker.tsx",
      "src/app/(app)/dashboard/classes/book/teacher-slot-button.tsx",
      "src/app/(app)/dashboard/classes/page.tsx",
      "src/app/(app)/dashboard/classes/class-list.tsx",
      "src/app/(app)/dashboard/classes/classes-toolbar.tsx",
      "src/app/(app)/dashboard/customize/page.tsx",
      "src/app/(app)/dashboard/discounts/discount-forms.tsx",
      "src/app/(app)/dashboard/discounts/page.tsx",
      "src/app/(app)/dashboard/leads/lead-actions.tsx",
      "src/app/(app)/dashboard/leads/lead-list.tsx",
      "src/app/(app)/dashboard/leads/lead-message.tsx",
      "src/app/(app)/dashboard/leads/leads-toolbar.tsx",
      "src/app/(app)/dashboard/leads/page.tsx",
      "src/app/(app)/dashboard/materials/edit-form.tsx",
      "src/app/(app)/dashboard/materials/content-edit-form.tsx",
      "src/app/(app)/dashboard/materials/page.tsx",
      "src/components/materials/material-form.tsx",
      "src/components/materials/material-editor.tsx",
      "src/components/materials/block-editor.tsx",
      "src/components/materials/icon-button.tsx",
      "src/app/(app)/dashboard/messages/[studentId]/page.tsx",
      "src/app/(app)/dashboard/messages/new/page.tsx",
      "src/app/(app)/dashboard/messages/page.tsx",
      "src/app/(app)/dashboard/page.tsx",
      "src/app/(app)/dashboard/referrals/page.tsx",
      "src/app/(app)/dashboard/referrals/referral-program-form.tsx",
      "src/app/(app)/dashboard/share-groups/page.tsx",
      "src/app/(app)/dashboard/students/[studentId]/assign-material-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/contact-edit-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/custom-price-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/delete-package-button.tsx",
      "src/app/(app)/dashboard/students/[studentId]/edit-package-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/go-live-button.tsx",
      "src/app/(app)/dashboard/students/[studentId]/notifications-toggle.tsx",
      "src/app/(app)/dashboard/students/[studentId]/package-pause-button.tsx",
      "src/app/(app)/dashboard/students/[studentId]/page.tsx",
      "src/app/(app)/dashboard/students/[studentId]/student-archive-button.tsx",
      "src/app/(app)/dashboard/students/[studentId]/student-learning-profile-card.tsx",
      "src/app/(app)/dashboard/students/[studentId]/student-level-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/student-notes-form.tsx",
      "src/app/(app)/dashboard/students/[studentId]/student-profile-form.tsx",
      "src/app/(app)/dashboard/students/duplicate-merge-card.tsx",
      "src/app/(app)/dashboard/students/nuevo/add-student-form.tsx",
      "src/app/(app)/dashboard/students/nuevo/page.tsx",
      "src/app/(app)/dashboard/students/page.tsx",
      "src/app/(app)/dashboard/testimonials/page.tsx",
      "src/app/(app)/dashboard/testimonials/testimonial-forms.tsx",
      "src/app/(app)/notifications/page.tsx",
      "src/app/(app)/notifications/notification-list.tsx",
      "src/app/(app)/notifications/loading.tsx",
      "src/app/(app)/onboarding/availability/availability-form.tsx",
      "src/app/(app)/onboarding/availability/page.tsx",
      "src/app/(app)/onboarding/preview/page.tsx",
      "src/app/(app)/onboarding/stepper.tsx",
      "src/app/(app)/onboarding/templates/page.tsx",
      "src/app/(app)/onboarding/templates/templates-form.tsx",
      "src/app/(app)/onboarding/timezone/page.tsx",
      "src/app/(app)/onboarding/timezone/timezone-form.tsx",
      "src/app/(app)/payments/[id]/page.tsx",
      "src/app/(app)/payments/[id]/refund-form.tsx",
      "src/app/(app)/payments/[id]/wise-confirm-form.tsx",
      "src/app/(app)/payments/page.tsx",
      "src/app/(app)/payments/payments-toolbar.tsx",
      "src/app/(app)/payments/payments-view.tsx",
      "src/app/(app)/settings/account/account-deletion-form.tsx",
      "src/app/(app)/settings/account/country-form.tsx",
      "src/app/(app)/settings/account/discipline-form.tsx",
      "src/app/(app)/settings/account/page.tsx",
      "src/app/(app)/settings/availability/page.tsx",
      "src/app/(app)/settings/billing/page.tsx",
      "src/app/(app)/settings/billing/plan-buttons.tsx",
      "src/app/(app)/settings/blocked-dates/blocked-date-form.tsx",
      "src/app/(app)/settings/blocked-dates/page.tsx",
      "src/app/(app)/settings/booking-page/bio-form.tsx",
      "src/app/(app)/settings/booking-page/booking-page-status.tsx",
      "src/app/(app)/settings/booking-page/booking-slug-form.tsx",
      "src/app/(app)/settings/booking-page/headline-form.tsx",
      "src/app/(app)/settings/booking-page/page-preview.tsx",
      "src/app/(app)/settings/booking-page/page.tsx",
      "src/app/(app)/settings/booking-page/photo-form.tsx",
      "src/app/(app)/settings/booking-page/section-nav.tsx",
      "src/app/(app)/settings/calendar/page.tsx",
      "src/app/(app)/settings/class-content-templates/class-content-templates-form.tsx",
      "src/app/(app)/settings/class-content-templates/page.tsx",
      "src/app/(app)/settings/focus-tags/page.tsx",
      "src/app/(app)/settings/focus-tags/tags-manager.tsx",
      "src/app/(app)/settings/notifications/page.tsx",
      "src/app/(app)/settings/templates/page.tsx",
      "src/app/(app)/subscription-banner.tsx",
      "src/app/(student)/my-classes/[bookingId]/call/page.tsx",
      "src/app/(student)/my-classes/[bookingId]/cancel-form.tsx",
      "src/app/(student)/my-classes/[bookingId]/content/page.tsx",
      "src/app/(student)/my-classes/[bookingId]/page.tsx",
      "src/app/(student)/my-classes/[bookingId]/reschedule/page.tsx",
      "src/app/(student)/my-classes/[bookingId]/reschedule/reschedule-slot-button.tsx",
      "src/app/(student)/my-classes/[bookingId]/student-live-notes.tsx",
      "src/app/(student)/my-classes/account/page.tsx",
      "src/app/(student)/my-classes/account/identity-card.tsx",
      "src/app/(student)/my-classes/account/section-nav.tsx",
      "src/app/(student)/my-classes/account/settings-section.tsx",
      "src/app/(student)/my-classes/book/confirmation/page.tsx",
      "src/app/(student)/my-classes/book/slot-submit-button.tsx",
      "src/app/(student)/my-classes/buy/page.tsx",
      "src/app/(student)/my-classes/buy/portal-purchase-flow.tsx",
      "src/app/(student)/my-classes/calendar/page.tsx",
      "src/app/(student)/my-classes/materials/page.tsx",
      "src/app/(student)/my-classes/messages/[teacherId]/page.tsx",
      "src/app/(student)/my-classes/messages/new/page.tsx",
      "src/app/(student)/my-classes/messages/page.tsx",
      "src/app/(student)/my-classes/page.tsx",
      "src/app/(student)/my-classes/progress/page.tsx",
      "src/app/(student)/my-classes/progress/vocab-review.tsx",
      "src/app/(student)/my-classes/referral-share.tsx",
      "src/app/(student)/my-classes/student-nav.tsx",
      "src/app/about/page.tsx",
      "src/app/admin/admin-nav.tsx",
      "src/app/admin/audit/page.tsx",
      "src/app/admin/error.tsx",
      "src/app/admin/layout.tsx",
      "src/app/admin/money/page.tsx",
      "src/app/admin/notifications/broadcast-form.tsx",
      "src/app/admin/notifications/page.tsx",
      "src/app/admin/notifications/retry-button.tsx",
      "src/app/admin/packages/[id]/actions-form.tsx",
      "src/app/admin/packages/[id]/page.tsx",
      "src/app/admin/packages/page.tsx",
      "src/app/admin/page.tsx",
      "src/app/admin/payments/page.tsx",
      "src/app/admin/payments/refund-form.tsx",
      "src/app/admin/security/admin-mfa-form.tsx",
      "src/app/admin/security/page.tsx",
      "src/app/admin/staff/invite-form.tsx",
      "src/app/admin/storage/page.tsx",
      "src/app/admin/storage/storage-browser.tsx",
      "src/app/admin/students/[id]/email-form.tsx",
      "src/app/admin/students/[id]/moderation-form.tsx",
      "src/app/admin/students/[id]/page.tsx",
      "src/app/admin/subscriptions/page.tsx",
      "src/app/admin/subscriptions/wise-renewal-form.tsx",
      "src/app/admin/teachers/[id]/moderation-form.tsx",
      "src/app/admin/teachers/[id]/subscription-form.tsx",
      "src/app/admin/uat/page.tsx",
      "src/app/b/[slug]/buy/purchase-flow.tsx",
      "src/app/b/[slug]/buy/result/page.tsx",
      "src/app/b/[slug]/buy/single-class-slot-picker.tsx",
      "src/app/b/[slug]/buy/wise/[ref]/page.tsx",
      "src/app/b/[slug]/lead-form.tsx",
      "src/app/b/[slug]/page.tsx",
      "src/app/features/page.tsx",
      // The student's materials shelf, rewritten against the catalog rather
      // than migrated into it, so it goes straight onto the enforced list.
      "src/app/(student)/my-classes/materials/page.tsx",
      "src/app/(student)/my-classes/materials/material-tracking.tsx",
      "src/app/layout.tsx",
      "src/app/m/login/page.tsx",
      "src/app/page.tsx",
      "src/app/precios/page.tsx",
      "src/app/privacy-notice/page.tsx",
      "src/components/account-badge.tsx",
      "src/components/account-menu.tsx",
      "src/components/account/data-export-card.tsx",
      "src/components/account/delete-account-card.tsx",
      "src/components/account/email-change-form.tsx",
      "src/components/account/my-details-form.tsx",
      "src/components/account/notification-prefs-form.tsx",
      "src/components/booking-status-badge.tsx",
      "src/components/calendar/add-to-calendar.tsx",
      "src/components/calendar/booking-month-calendar.tsx",
      "src/components/calendar/calendar-day.tsx",
      "src/components/calendar/calendar-legend.tsx",
      "src/components/calendar/calendar-month.tsx",
      "src/components/calendar/calendar-range-header.tsx",
      "src/components/calendar/calendar-sync-panel.tsx",
      "src/components/calendar/calendar-view-switcher.tsx",
      "src/components/calendar/calendar-week.tsx",
      "src/components/calendar/day-cell.tsx",
      "src/components/calendar/time-grid.tsx",
      "src/components/calendar/google-calendar-panel.tsx",
      "src/components/cashflow-summary.tsx",
      "src/components/chat-room.tsx",
      "src/components/class-content/print-button.tsx",
      "src/components/copy-link-button.tsx",
      "src/components/dashboard/customize-tiles-form.tsx",
      "src/components/growth-checklist.tsx",
      "src/components/notification-schedule.tsx",
      // Student acquisition (D-125) — written against the shared catalog from
      // the start, so it goes straight onto the enforced list rather than into
      // the ratchet baseline.
      "src/app/(app)/dashboard/get-students/loading.tsx",
      "src/app/(app)/dashboard/get-students/page.tsx",
      "src/app/(app)/dashboard/get-students/action-card.tsx",
      "src/app/(app)/dashboard/get-students/page-readiness-card.tsx",
      "src/app/(app)/dashboard/get-students/regenerate-button.tsx",
      "src/app/(app)/dashboard/get-students/results-summary-card.tsx",
      "src/app/(app)/dashboard/get-students/section-nav.tsx",
      "src/app/(app)/dashboard/get-students/week-progress.tsx",
      "src/app/(app)/dashboard/get-students/[activityId]/page.tsx",
      "src/app/(app)/dashboard/get-students/[activityId]/prepare-panel.tsx",
      "src/app/(app)/dashboard/get-students/[activityId]/mark-done-button.tsx",
      "src/app/(app)/dashboard/get-students/[activityId]/skip-button.tsx",
      "src/app/(app)/dashboard/get-students/communities/page.tsx",
      "src/app/(app)/dashboard/get-students/communities/community-forms.tsx",
      "src/app/(app)/dashboard/get-students/communities/social-preview-panel.tsx",
      "src/app/(app)/dashboard/get-students/results/page.tsx",
      "src/app/(app)/dashboard/get-students/profile/page.tsx",
      "src/app/(app)/dashboard/get-students/profile/profile-form.tsx",
      // Blocked dates — rebuilt against the shared catalog (the calendar, the
      // composer and the block list all read every string from it), so it goes
      // straight onto the enforced list rather than into the ratchet baseline.
      "src/app/(app)/settings/blocked-dates/page.tsx",
      "src/app/(app)/settings/blocked-dates/blocked-dates-manager.tsx",
      "src/app/(app)/settings/blocked-dates/blocked-dates-calendar.tsx",
      "src/app/(app)/settings/blocked-dates/blocked-date-form.tsx",
      "src/app/(app)/settings/blocked-dates/blocked-list.tsx",
      "src/app/(app)/settings/blocked-dates/remove-block-button.tsx",
      // Discount codes — rebuilt against the shared catalog, so it joins the
      // enforced list rather than the ratchet baseline.
      "src/app/(app)/dashboard/discounts/page.tsx",
      "src/app/(app)/dashboard/discounts/discount-list.tsx",
      "src/app/(app)/dashboard/discounts/discount-forms.tsx",
      "src/app/(app)/dashboard/discounts/loading.tsx",
      "src/components/theme-toggle.tsx",
      "src/components/video/class-call-client.tsx",
      "src/components/video/class-call.tsx",
      "src/components/video/caption-band.tsx",
    ],
    plugins: { i18n: { rules: { "no-literal-string": noLiteralString } } },
    rules: { "i18n/no-literal-string": "error" },
  },
  {
    // The design-token rule, at ERROR on the surfaces that are clean.
    //
    // The ui/ primitives above all: a raw value there propagates to hundreds of
    // files, so this is the one place it must never land.
    files: [
      "src/components/ui/**/*.tsx",
      "src/components/brand/**/*.tsx",
      "src/components/materials/ai-change-chip.tsx",
    ],
    plugins: { design: { rules: { tokens: designTokens } } },
    rules: { "design/tokens": "error" },
  },
  {
    // ...and at WARN on the surfaces still being converted, so an edit to one
    // sees the reason without a wall of errors that trains people to disable
    // the rule. Each moves up to the block above as it reaches zero; the
    // ratchet (tests/design-drift.test.ts) is what stops any of them growing
    // in the meantime.
    files: [
      "src/components/account/**/*.tsx",
      "src/app/(app)/settings/**/*.tsx",
      "src/app/(app)/dashboard/students/**/*.tsx",
      "src/app/(student)/my-classes/**/*.tsx",
      "src/app/page.tsx",
      "src/app/precios/page.tsx",
    ],
    plugins: { design: { rules: { tokens: designTokens } } },
    rules: { "design/tokens": "warn" },
  },
  {
    // react-hooks/exhaustive-deps crashes ("a.getSource is not a function")
    // analyzing this hook's large async-IIFE effect body — an inline
    // eslint-disable-next-line doesn't help since the crash happens during
    // the rule's own analysis, before directive suppression applies. Disable
    // the rule for this file at the config level so it's never invoked here.
    // class-call.tsx's own connect effect hit the identical crash once its
    // async IIFE grew with the call-analytics instrumentation (docs/architecture/
    // VIDEO_CALL_POSTHOG_AUDIT.md) — same root cause, same fix.
    // material-form.tsx's refine-result effect hit it the same way once the
    // AI-editing UX follow-up added the pre-refine snapshot/banner state to
    // its body — tried factoring the body into a named helper function first,
    // which did NOT help (the crash follows the effect's reactive-value
    // analysis, not raw statement count), so this is the same fix again.
    // use-caption-feed.ts hit the identical crash the day it was written —
    // "a.getSource is not a function", reported against its useMemo. Same
    // root cause, same fix; an inline disable comment does not help, because
    // the crash happens inside the rule's own analysis, before directive
    // suppression applies.
    files: [
      "src/lib/captions/use-live-captions.ts",
      "src/lib/captions/use-caption-feed.ts",
      "src/components/video/class-call.tsx",
      "src/components/materials/material-form.tsx",
    ],
    rules: {
      "react-hooks/exhaustive-deps": "off",
    },
  },
];
