-- =====================================================================
-- SpiralClass — schema baseline
--
-- Every table, enum, index, foreign key and default that `schema.prisma`
-- expresses, applied to an empty database. This file is MACHINE-GENERATED
-- and can be regenerated byte-for-byte at any time:
--
--   pnpm --filter spiralclass-web exec prisma migrate diff \
--     --from-empty --to-schema-datamodel prisma/schema.prisma --script
--
-- so it is not meant to be read as prose. `prisma/schema.prisma` is the
-- annotated description of the same thing, and /admin/database renders it
-- as an ERD (docs/architecture/ERD.md).
--
-- What it deliberately does NOT contain is the Postgres layer Prisma's
-- schema language cannot express: partial indexes, CHECK constraints, the
-- two GiST exclusion constraints that make a double-booked slot
-- unrepresentable, the append-only audit trigger, `btree_gist`. That is
-- hand-authored and lives in the migration immediately after this one,
-- kept separate precisely so that regenerating this file can never
-- silently drop it. Neither file is the schema on its own; `migrate
-- deploy` applies both, in order.
--
-- Applying this to a database that already has tables is not the path —
-- see prisma/migrations/README.md for the baselining procedure.
-- =====================================================================

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "PackageStatus" AS ENUM ('pending', 'active', 'paused', 'expired', 'refunded');

-- CreateEnum
CREATE TYPE "BookingStatus" AS ENUM ('scheduled', 'completed', 'canceled_by_student', 'canceled_by_teacher', 'rescheduled', 'no_show');

-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('pending', 'paid', 'failed', 'refunded');

-- CreateEnum
CREATE TYPE "PaymentProvider" AS ENUM ('stripe', 'manual_transfer');

-- CreateEnum
CREATE TYPE "PaymentRail" AS ENUM ('card', 'wise', 'bank_transfer', 'unknown');

-- CreateEnum
CREATE TYPE "PayoutInstrumentKind" AS ENUM ('wise');

-- CreateEnum
CREATE TYPE "MaterialSendTiming" AS ENUM ('confirmation', 't_5d', 't_24h', 't_1h');

-- CreateEnum
CREATE TYPE "NoteAudience" AS ENUM ('teacher', 'student');

-- CreateEnum
CREATE TYPE "LibraryVisibility" AS ENUM ('at_or_below', 'exact', 'all');

-- CreateEnum
CREATE TYPE "NotificationChannel" AS ENUM ('push', 'email');

-- CreateEnum
CREATE TYPE "NotificationStatus" AS ENUM ('queued', 'sending', 'sent', 'delivered', 'failed', 'suppressed');

-- CreateEnum
CREATE TYPE "NotificationRecipientType" AS ENUM ('teacher', 'student');

-- CreateEnum
CREATE TYPE "LeadStatus" AS ENUM ('new', 'contacted', 'converted', 'archived');

-- CreateEnum
CREATE TYPE "TestimonialSource" AS ENUM ('teacher_curated', 'student_submitted');

-- CreateEnum
CREATE TYPE "OverrideTargetType" AS ENUM ('booking', 'package', 'payment', 'student', 'teacher', 'system', 'call');

-- CreateEnum
CREATE TYPE "AdminRole" AS ENUM ('superadmin', 'finance', 'support', 'tester', 'engineer');

-- CreateEnum
CREATE TYPE "ExpenseCategory" AS ENUM ('hosting', 'ai', 'dev_tools', 'monitoring', 'email', 'domain', 'other');

-- CreateEnum
CREATE TYPE "WebhookProvider" AS ENUM ('stripe', 'inngest', 'livekit');

-- CreateEnum
CREATE TYPE "DisputeStatus" AS ENUM ('warning_needs_response', 'warning_under_review', 'warning_closed', 'needs_response', 'under_review', 'charge_refunded', 'won', 'lost');

-- CreateEnum
CREATE TYPE "AccountDeletionStatus" AS ENUM ('pending', 'anonymizing', 'cancelled', 'anonymized');

-- CreateEnum
CREATE TYPE "AccountDeletionSubjectType" AS ENUM ('teacher', 'student');

-- CreateEnum
CREATE TYPE "SubscriptionPlan" AS ENUM ('free', 'monthly', 'annual', 'founding');

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'free');

-- CreateEnum
CREATE TYPE "SubscriptionInvoiceStatus" AS ENUM ('paid', 'open', 'failed', 'void');

-- CreateEnum
CREATE TYPE "SubscriptionPaymentProvider" AS ENUM ('stripe', 'manual');

-- CreateEnum
CREATE TYPE "HomeworkSubmissionStatus" AS ENUM ('draft', 'submitted', 'returned', 'graded');

-- CreateEnum
CREATE TYPE "HomeworkFeedbackDecision" AS ENUM ('approved', 'resubmission_requested', 'rejected');

-- CreateEnum
CREATE TYPE "InvitationStatus" AS ENUM ('pending', 'accepted', 'cancelled', 'expired');

-- CreateEnum
CREATE TYPE "DiscountKind" AS ENUM ('percent', 'fixed');

-- CreateEnum
CREATE TYPE "DiscountOrigin" AS ENUM ('promo', 'referral_referred', 'referral_referrer');

-- CreateEnum
CREATE TYPE "ReferralStatus" AS ENUM ('attributed', 'qualified', 'rewarded', 'void');

-- CreateEnum
CREATE TYPE "NoteKind" AS ENUM ('text', 'bookmark');

-- CreateEnum
CREATE TYPE "ClassContentSource" AS ENUM ('manual', 'ai');

-- CreateEnum
CREATE TYPE "PodcastStatus" AS ENUM ('pending', 'ready', 'failed');

-- CreateEnum
CREATE TYPE "LessonAudioSpeaker" AS ENUM ('student', 'teacher');

-- CreateEnum
CREATE TYPE "IntroVideoAnalysisStatus" AS ENUM ('pending', 'transcribing', 'transcribed', 'failed');

-- CreateEnum
CREATE TYPE "InsightCategory" AS ENUM ('pronunciation', 'grammar', 'vocabulary', 'fluency', 'comprehension');

-- CreateEnum
CREATE TYPE "ContactChangeActorType" AS ENUM ('student', 'teacher', 'admin');

-- CreateEnum
CREATE TYPE "social_preview_source" AS ENUM ('upload', 'ai', 'template', 'system');

-- CreateEnum
CREATE TYPE "social_preview_angle" AS ENUM ('meme', 'promo', 'tip', 'motivation');

-- CreateEnum
CREATE TYPE "marketing_activity_status" AS ENUM ('planned', 'ready', 'done', 'skipped');

-- CreateEnum
CREATE TYPE "acquisition_event_kind" AS ENUM ('visit', 'enquiry', 'booking', 'purchase');

-- CreateTable
CREATE TABLE "teachers" (
    "seeded_at" TIMESTAMPTZ,
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "timezone" TEXT NOT NULL,
    "country" TEXT NOT NULL DEFAULT 'MX',
    "pricing_currency" TEXT NOT NULL DEFAULT 'MXN',
    "locale" TEXT NOT NULL DEFAULT 'en',
    "locale_chosen_at" TIMESTAMP(3),
    "reading_scale" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "reading_spacing" INTEGER NOT NULL DEFAULT 0,
    "reading_tint" BOOLEAN NOT NULL DEFAULT false,
    "booking_page_locale" TEXT,
    "teaching_language" TEXT NOT NULL DEFAULT 'es',
    "buffer_min" INTEGER NOT NULL DEFAULT 10,
    "min_advance_h" INTEGER NOT NULL DEFAULT 24,
    "max_advance_days" INTEGER NOT NULL DEFAULT 60,
    "booking_slug" TEXT NOT NULL,
    "onboarding_complete_at" TIMESTAMPTZ,
    "templates_touched_at" TIMESTAMPTZ,
    "availability_touched_at" TIMESTAMPTZ,
    "marketplace_ready_at" TIMESTAMPTZ,
    "profile_completed_at" TIMESTAMPTZ,
    "phone_e164" TEXT,
    "notification_prefs" JSONB,
    "dashboard_tile_order" JSONB,
    "dashboard_layout" JSONB,
    "push_opt_in" BOOLEAN NOT NULL DEFAULT true,
    "email_opt_in" BOOLEAN NOT NULL DEFAULT true,
    "auto_surface_level_materials" BOOLEAN NOT NULL DEFAULT false,
    "headline" TEXT,
    "bio" TEXT,
    "public_whatsapp_e164" TEXT,
    "photo_path" TEXT,
    "intro_video_path" TEXT,
    "intro_video_duration_ms" INTEGER,
    "stripe_account_id" TEXT,
    "stripe_account_linked_at" TIMESTAMPTZ,
    "stripe_charges_enabled" BOOLEAN NOT NULL DEFAULT false,
    "stripe_payouts_enabled" BOOLEAN NOT NULL DEFAULT false,
    "stripe_requirements_disabled_reason" TEXT,
    "platform_region" TEXT DEFAULT 'GB',
    "disabled_at" TIMESTAMPTZ,
    "disabled_reason" TEXT,
    "referral_source" TEXT,
    "target_language" TEXT,
    "calendar_feed_token" TEXT,
    "lesson_audio_retention_opt_in" BOOLEAN NOT NULL DEFAULT false,
    "auto_record_classes" BOOLEAN NOT NULL DEFAULT false,
    "share_progress_by_default" BOOLEAN NOT NULL DEFAULT false,
    "intro_video_transcript_public_opt_in" BOOLEAN NOT NULL DEFAULT false,
    "material_tone" TEXT,
    "material_learner_age" TEXT,
    "material_language_variety" TEXT,
    "material_custom_instructions" TEXT,
    "material_vocabulary" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "teachers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "students" (
    "seeded_at" TIMESTAMPTZ,
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "auth_user_id" UUID,
    "email" TEXT,
    "phone_e164" TEXT,
    "name" TEXT NOT NULL,
    "timezone" TEXT,
    "locale" TEXT NOT NULL DEFAULT 'en',
    "locale_chosen_at" TIMESTAMP(3),
    "reading_scale" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "reading_spacing" INTEGER NOT NULL DEFAULT 0,
    "reading_tint" BOOLEAN NOT NULL DEFAULT false,
    "native_language" TEXT NOT NULL DEFAULT 'en',
    "email_opt_in" BOOLEAN NOT NULL DEFAULT true,
    "email_opt_in_at" TIMESTAMPTZ,
    "push_opt_in" BOOLEAN NOT NULL DEFAULT true,
    "notification_prefs" JSONB,
    "disabled_at" TIMESTAMPTZ,
    "disabled_reason" TEXT,
    "calendar_feed_token" TEXT,
    "photo_path" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "onboarding_complete_at" TIMESTAMPTZ,

    CONSTRAINT "students_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "student_invitations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "token_hash" TEXT NOT NULL,
    "status" "InvitationStatus" NOT NULL DEFAULT 'pending',
    "expires_at" TIMESTAMPTZ NOT NULL,
    "sent_at" TIMESTAMPTZ,
    "last_sent_at" TIMESTAMPTZ,
    "resend_count" INTEGER NOT NULL DEFAULT 0,
    "accepted_at" TIMESTAMPTZ,
    "cancelled_at" TIMESTAMPTZ,
    "reminder_sent_at" TIMESTAMPTZ,
    "accepted_by_user_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "student_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_students" (
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "custom_price_note" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "level_id" UUID,
    "interests" TEXT,
    "goals" TEXT,
    "archived_at" TIMESTAMPTZ,
    "archived_reason" TEXT,
    "onboarding_hold_at" TIMESTAMPTZ,
    "share_progress" BOOLEAN NOT NULL DEFAULT false,
    "is_minor" BOOLEAN NOT NULL DEFAULT false,
    "insights_consent_at" TIMESTAMPTZ,
    "guardian_consent_at" TIMESTAMPTZ,
    "captions_consent_at" TIMESTAMPTZ,
    "captions_guardian_consent_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teacher_students_pkey" PRIMARY KEY ("teacher_id","student_id")
);

-- CreateTable
CREATE TABLE "teacher_student_template_prices" (
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "template_id" UUID NOT NULL,
    "price_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "teacher_student_template_prices_pkey" PRIMARY KEY ("teacher_id","student_id","template_id")
);

-- CreateTable
CREATE TABLE "leads" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone_e164" TEXT,
    "message" TEXT,
    "status" "LeadStatus" NOT NULL DEFAULT 'new',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "leads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "testimonials" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "author_name" TEXT NOT NULL,
    "author_note" TEXT,
    "body" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "source" "TestimonialSource" NOT NULL DEFAULT 'teacher_curated',
    "student_id" UUID,
    "verified_at" TIMESTAMPTZ,
    "photo_path" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "testimonials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "discount_codes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "kind" "DiscountKind" NOT NULL,
    "percent_bps" INTEGER,
    "amount_minor_units" INTEGER,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "origin" "DiscountOrigin" NOT NULL DEFAULT 'promo',
    "active" BOOLEAN NOT NULL DEFAULT true,
    "max_redemptions" INTEGER,
    "per_student_limit" INTEGER NOT NULL DEFAULT 1,
    "expires_at" TIMESTAMPTZ,
    "reserved_for_student_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "discount_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "discount_redemptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "discount_code_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "package_id" UUID NOT NULL,
    "payment_id" UUID NOT NULL,
    "amount_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "discount_redemptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "referral_programs" (
    "teacher_id" UUID NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "referred_kind" "DiscountKind" NOT NULL DEFAULT 'fixed',
    "referred_percent_bps" INTEGER,
    "referred_amount_minor_units" INTEGER,
    "referrer_kind" "DiscountKind" NOT NULL DEFAULT 'fixed',
    "referrer_percent_bps" INTEGER,
    "referrer_amount_minor_units" INTEGER,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "reward_expiry_days" INTEGER,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "referral_programs_pkey" PRIMARY KEY ("teacher_id")
);

-- CreateTable
CREATE TABLE "referral_codes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "owner_student_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "referral_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "referrals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "referral_code_id" UUID NOT NULL,
    "referred_student_id" UUID NOT NULL,
    "package_id" UUID NOT NULL,
    "payment_id" UUID NOT NULL,
    "referred_discount_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "status" "ReferralStatus" NOT NULL DEFAULT 'attributed',
    "referrer_reward_code_id" UUID,
    "qualified_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "referrals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_share_groups" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "platform" TEXT NOT NULL DEFAULT 'facebook_group',
    "promo_policy" TEXT NOT NULL DEFAULT 'unknown',
    "audience_note" TEXT,
    "promo_weekdays" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
    "promo_every_days" INTEGER,
    "promo_links_allowed" BOOLEAN,
    "promo_notes" TEXT,
    "meme_brief" TEXT,
    "archived_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "teacher_share_groups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "availability_rules" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "weekday" INTEGER NOT NULL,
    "start_time" TEXT NOT NULL,
    "end_time" TEXT NOT NULL,
    "timezone" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "availability_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "blocked_dates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "starts_at" TIMESTAMPTZ NOT NULL,
    "ends_at" TIMESTAMPTZ NOT NULL,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "blocked_dates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "google_calendar_connections" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "google_email" TEXT,
    "refresh_token_enc" TEXT NOT NULL,
    "access_token" TEXT,
    "access_token_expires_at" TIMESTAMPTZ,
    "sync_enabled" BOOLEAN NOT NULL DEFAULT true,
    "last_synced_at" TIMESTAMPTZ,
    "last_sync_error" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "google_calendar_connections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "google_busy_intervals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "starts_at" TIMESTAMPTZ NOT NULL,
    "ends_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "google_busy_intervals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "package_templates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "subject" TEXT,
    "class_count" INTEGER NOT NULL,
    "single_class" BOOLEAN NOT NULL DEFAULT false,
    "class_duration_min" INTEGER NOT NULL DEFAULT 50,
    "price_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "transfer_price_minor_units" INTEGER,
    "expiration_months" INTEGER,
    "archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "package_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "packages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "template_id" UUID,
    "classes_total" INTEGER NOT NULL,
    "classes_used" INTEGER NOT NULL DEFAULT 0,
    "schedule_changes_used" INTEGER NOT NULL DEFAULT 0,
    "class_duration_min" INTEGER NOT NULL DEFAULT 50,
    "price_paid_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "custom_price_minor_units" INTEGER,
    "purchased_at" TIMESTAMPTZ NOT NULL,
    "expires_at" TIMESTAMPTZ,
    "intended_start_utc" TIMESTAMPTZ,
    "status" "PackageStatus" NOT NULL DEFAULT 'active',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "packages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bookings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "package_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "scheduled_start" TIMESTAMPTZ NOT NULL,
    "scheduled_end" TIMESTAMPTZ NOT NULL,
    "status" "BookingStatus" NOT NULL DEFAULT 'scheduled',
    "counts_against_package" BOOLEAN NOT NULL DEFAULT true,
    "reschedule_of_booking_id" UUID,
    "reschedule_count" INTEGER NOT NULL DEFAULT 0,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "buffer_min_snapshot" INTEGER NOT NULL DEFAULT 0,
    "teacher_language_override" TEXT,
    "student_language_override" TEXT,
    "vocabulary_override" TEXT,
    "buffered_end" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bookings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_notes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "audience" "NoteAudience" NOT NULL,
    "body" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "kind" "NoteKind" NOT NULL DEFAULT 'text',
    "done_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "assignments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "instructions" TEXT,
    "due_at" TIMESTAMPTZ,
    "allow_late_submission" BOOLEAN NOT NULL DEFAULT true,
    "allow_resubmission" BOOLEAN NOT NULL DEFAULT false,
    "source_material_id" UUID,
    "source_material_revision_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "homework_submissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "assignment_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "text_response" TEXT,
    "status" "HomeworkSubmissionStatus" NOT NULL DEFAULT 'draft',
    "submitted_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "homework_submissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "homework_submission_files" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "submission_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "storage_path" TEXT NOT NULL,
    "file_name" TEXT NOT NULL,
    "file_type" TEXT NOT NULL,
    "file_size" INTEGER NOT NULL,
    "uploaded_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "attempt_id" UUID,

    CONSTRAINT "homework_submission_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "homework_attempts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "submission_id" UUID NOT NULL,
    "attempt_number" INTEGER NOT NULL,
    "text_response" TEXT,
    "submitted_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "homework_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "homework_feedback" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "attempt_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "decision" "HomeworkFeedbackDecision" NOT NULL,
    "content" TEXT NOT NULL,
    "score" INTEGER,
    "ai_draft_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "homework_feedback_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "homework_ai_review_drafts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "attempt_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "instructions" TEXT,
    "content" JSONB NOT NULL,
    "model" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "discarded_at" TIMESTAMPTZ,

    CONSTRAINT "homework_ai_review_drafts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "class_content_generations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "class_content_generations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "class_content_templates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "class_content_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_summaries" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_summaries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "call_recordings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "egress_id" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'recording',
    "started_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "call_recordings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_audio" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "speaker" "LessonAudioSpeaker" NOT NULL,
    "egress_id" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'recording',
    "duration_ms" INTEGER,
    "started_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ended_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_audio_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_transcripts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "language" TEXT NOT NULL,
    "utterances" JSONB NOT NULL,
    "provider" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_transcripts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "intro_video_analyses" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "video_path" TEXT NOT NULL,
    "status" "IntroVideoAnalysisStatus" NOT NULL DEFAULT 'pending',
    "language" TEXT,
    "provider" TEXT,
    "transcript" JSONB,
    "coach_feedback" JSONB,
    "error" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "intro_video_analyses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_insights" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "category" "InsightCategory" NOT NULL,
    "summary" TEXT NOT NULL,
    "skill" TEXT,
    "evidence" TEXT,
    "suggestion" TEXT,
    "at_ms" INTEGER,
    "source" TEXT NOT NULL DEFAULT 'ai',
    "confirmed_at" TIMESTAMPTZ,
    "dismissed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_insights_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_pronunciation" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "language" TEXT NOT NULL,
    "scores" JSONB NOT NULL,
    "provider" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_pronunciation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "student_learning_profiles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "profile" JSONB NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "student_learning_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lesson_briefs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "booking_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "content" JSONB NOT NULL,
    "model" TEXT NOT NULL,
    "generated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "lesson_briefs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "vocabulary_reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "term" TEXT NOT NULL,
    "interval_days" INTEGER NOT NULL DEFAULT 0,
    "ease_factor" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
    "due_at" TIMESTAMPTZ NOT NULL,
    "last_reviewed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "vocabulary_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "levels" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "levels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "focus_tag_categories" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "focus_tag_categories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "focus_tags" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "code" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "category_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "focus_tags_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "library_materials" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "level_id" UUID,
    "booking_id" UUID,
    "visibility" "LibraryVisibility" NOT NULL DEFAULT 'at_or_below',
    "unit" TEXT,
    "position" INTEGER NOT NULL DEFAULT 0,
    "storage_path" TEXT,
    "link_url" TEXT,
    "body" TEXT,
    "content_source" "ClassContentSource",
    "label" TEXT,
    "send_timing" "MaterialSendTiming",
    "archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "library_materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "material_revisions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "material_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "source" "ClassContentSource" NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "material_revisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "material_podcasts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "material_id" UUID NOT NULL,
    "teacher_id" UUID NOT NULL,
    "status" "PodcastStatus" NOT NULL,
    "storage_path" TEXT,
    "script" TEXT,
    "duration_sec" INTEGER,
    "voice" TEXT,
    "error" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "generated_at" TIMESTAMPTZ,

    CONSTRAINT "material_podcasts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "library_material_focus_tags" (
    "library_material_id" UUID NOT NULL,
    "focus_tag_id" UUID NOT NULL,

    CONSTRAINT "library_material_focus_tags_pkey" PRIMARY KEY ("library_material_id","focus_tag_id")
);

-- CreateTable
CREATE TABLE "booking_library_materials" (
    "booking_id" UUID NOT NULL,
    "library_material_id" UUID NOT NULL,
    "send_timing" "MaterialSendTiming" NOT NULL,
    "attached_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "booking_library_materials_pkey" PRIMARY KEY ("booking_id","library_material_id")
);

-- CreateTable
CREATE TABLE "class_material_uses" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "booking_id" UUID NOT NULL,
    "material_id" UUID NOT NULL,
    "opened_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "opened_for" TEXT NOT NULL DEFAULT 'teacher',

    CONSTRAINT "class_material_uses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "student_library_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "library_material_id" UUID NOT NULL,
    "assigned_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ,
    "completed_by" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "student_library_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "student_notes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "body" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "student_notes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_payout_instruments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "kind" "PayoutInstrumentKind" NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "account_holder" TEXT,
    "wise_handle" TEXT,
    "wise_email" TEXT,
    "wise_api_profile_id" TEXT,
    "wise_api_token_enc" TEXT,
    "wise_api_key_enc" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "teacher_payout_instruments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "package_id" UUID NOT NULL,
    "amount_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "status" "PaymentStatus" NOT NULL DEFAULT 'pending',
    "provider" "PaymentProvider" NOT NULL DEFAULT 'stripe',
    "provider_payment_id" TEXT,
    "external_reference" UUID NOT NULL DEFAULT gen_random_uuid(),
    "stripe_checkout_session_id" TEXT,
    "rail" "PaymentRail" NOT NULL DEFAULT 'unknown',
    "paid_at" TIMESTAMPTZ,
    "refunded_at" TIMESTAMPTZ,
    "refund_provider_id" TEXT,
    "instrument_id" UUID,
    "payment_reference" TEXT,
    "confirmed_by" UUID,
    "confirmed_at" TIMESTAMPTZ,
    "auto_matched_at" TIMESTAMPTZ,
    "student_marked_sent_at" TIMESTAMPTZ,
    "posthog_session_id" TEXT,
    "billing_country" TEXT,
    "billing_address_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "overrides" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID,
    "target_type" "OverrideTargetType" NOT NULL,
    "target_id" UUID NOT NULL,
    "action" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "before_json" JSONB,
    "after_json" JSONB,
    "actor_admin_id" UUID,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "overrides_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "student_contact_changes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "student_id" UUID NOT NULL,
    "actor_type" "ContactChangeActorType" NOT NULL,
    "actor_teacher_id" UUID,
    "actor_admin_id" UUID,
    "before_json" JSONB NOT NULL,
    "after_json" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "student_contact_changes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "recipient_type" "NotificationRecipientType" NOT NULL,
    "recipient_id" UUID NOT NULL,
    "booking_id" UUID,
    "payment_id" UUID,
    "channel" "NotificationChannel" NOT NULL,
    "template_name" TEXT NOT NULL,
    "metadata" JSONB,
    "language_code" TEXT,
    "status" "NotificationStatus" NOT NULL DEFAULT 'queued',
    "error" TEXT,
    "provider_message_id" TEXT,
    "sent_at" TIMESTAMPTZ,
    "delivered_at" TIMESTAMPTZ,
    "failed_at" TIMESTAMPTZ,
    "read_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "web_push_subscriptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "recipient_type" "NotificationRecipientType" NOT NULL,
    "recipient_id" UUID NOT NULL,
    "endpoint" TEXT NOT NULL,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "user_agent" TEXT,
    "last_seen_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "web_push_subscriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "provider" "WebhookProvider" NOT NULL,
    "event_id" TEXT NOT NULL,
    "event_type" TEXT,
    "received_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processed_at" TIMESTAMPTZ,

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "disputes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "stripe_dispute_id" TEXT NOT NULL,
    "stripe_charge_id" TEXT NOT NULL,
    "stripe_payment_intent_id" TEXT,
    "payment_id" UUID,
    "teacher_id" UUID,
    "amount_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "status" "DisputeStatus" NOT NULL,
    "evidence_due_by" TIMESTAMPTZ,
    "is_final" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "disputes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account_deletion_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "subject_type" "AccountDeletionSubjectType" NOT NULL,
    "subject_id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "status" "AccountDeletionStatus" NOT NULL DEFAULT 'pending',
    "scheduled_for" TIMESTAMPTZ NOT NULL,
    "cancelled_at" TIMESTAMPTZ,
    "anonymized_at" TIMESTAMPTZ,
    "reason" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "account_deletion_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "alpha_allowlist_entries" (
    "email" TEXT NOT NULL,
    "added_by" TEXT,
    "note" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "alpha_allowlist_entries_pkey" PRIMARY KEY ("email")
);

-- CreateTable
CREATE TABLE "admin_users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" TEXT NOT NULL,
    "role" "AdminRole" NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by_id" UUID,
    "disabled_at" TIMESTAMPTZ,

    CONSTRAINT "admin_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "uat_checklist_state" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "target_env" TEXT NOT NULL,
    "checked_items" JSONB NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "updated_by_admin_id" UUID,

    CONSTRAINT "uat_checklist_state_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_subscriptions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "plan" "SubscriptionPlan" NOT NULL DEFAULT 'free',
    "status" "SubscriptionStatus" NOT NULL DEFAULT 'trialing',
    "locked_price_minor_units" INTEGER,
    "currency" TEXT NOT NULL DEFAULT 'GBP',
    "stripe_customer_id" TEXT,
    "stripe_subscription_id" TEXT,
    "trial_ends_at" TIMESTAMPTZ,
    "current_period_end" TIMESTAMPTZ,
    "cancel_at_period_end" BOOLEAN NOT NULL DEFAULT false,
    "canceled_at" TIMESTAMPTZ,
    "comped" BOOLEAN NOT NULL DEFAULT false,
    "billing_country" TEXT,
    "billing_address_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "teacher_subscriptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "subscription_invoices" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "period_start" TIMESTAMPTZ NOT NULL,
    "period_end" TIMESTAMPTZ NOT NULL,
    "amount_minor_units" INTEGER NOT NULL,
    "fee_minor_units" INTEGER NOT NULL DEFAULT 0,
    "net_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'GBP',
    "status" "SubscriptionInvoiceStatus" NOT NULL DEFAULT 'open',
    "provider" "SubscriptionPaymentProvider" NOT NULL DEFAULT 'stripe',
    "stripe_invoice_id" TEXT,
    "manual_payment_ref" TEXT,
    "paid_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "subscription_invoices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_expenses" (
    "id" TEXT NOT NULL,
    "vendor" TEXT NOT NULL,
    "vendor_label" TEXT,
    "category" "ExpenseCategory" NOT NULL,
    "amount_minor_units" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'MXN',
    "period_month" DATE NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_expenses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "integrations" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'other',
    "purpose" TEXT,
    "pricing_model" JSONB NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "billing_model" TEXT,
    "notes" TEXT,
    "billing_url" TEXT,
    "docs_url" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "integrations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "usage_inputs" (
    "id" TEXT NOT NULL,
    "metric" TEXT NOT NULL,
    "period_month" DATE NOT NULL,
    "value" DOUBLE PRECISION NOT NULL,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "notes" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "usage_inputs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "economics_assumptions" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "fx_usd_to_gbp" DOUBLE PRECISION NOT NULL,
    "fx_mxn_to_gbp" DOUBLE PRECISION NOT NULL,
    "fx_eur_to_gbp" DOUBLE PRECISION NOT NULL,
    "allocation_basis" TEXT NOT NULL DEFAULT 'active_teachers',
    "fx_as_of" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "economics_assumptions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "founding_cohort" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "headcount" INTEGER NOT NULL DEFAULT 0,
    "cutoff_at" TIMESTAMPTZ,
    "max_teachers" INTEGER,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "founding_cohort_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "messages" (
    "id" TEXT NOT NULL,
    "teacher_id" UUID NOT NULL,
    "student_id" UUID NOT NULL,
    "sender_role" TEXT NOT NULL,
    "body" TEXT,
    "voice_storage_path" TEXT,
    "voice_duration_ms" INTEGER,
    "video_storage_path" TEXT,
    "video_duration_ms" INTEGER,
    "image_storage_path" TEXT,
    "image_width" INTEGER,
    "image_height" INTEGER,
    "file_storage_path" TEXT,
    "file_name" TEXT,
    "file_size_bytes" INTEGER,
    "file_mime_type" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "read_at" TIMESTAMPTZ,
    "edited_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ,
    "reply_to_id" TEXT,

    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "message_reactions" (
    "id" TEXT NOT NULL,
    "message_id" TEXT NOT NULL,
    "reactor_role" TEXT NOT NULL,
    "emoji" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "message_reactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "twoFactorEnabled" BOOLEAN DEFAULT false,
    "role" TEXT,
    "banned" BOOLEAN DEFAULT false,
    "banReason" TEXT,
    "banExpires" TIMESTAMP(3),

    CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "token" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" UUID NOT NULL,
    "impersonatedBy" TEXT,

    CONSTRAINT "session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "account" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" UUID NOT NULL,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMP(3),
    "refreshTokenExpiresAt" TIMESTAMP(3),
    "scope" TEXT,
    "password" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "identifier" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "twoFactor" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "secret" TEXT NOT NULL,
    "backupCodes" TEXT NOT NULL,
    "userId" UUID NOT NULL,
    "verified" BOOLEAN DEFAULT true,
    "failedVerificationCount" INTEGER DEFAULT 0,
    "lockedUntil" TIMESTAMP(3),

    CONSTRAINT "twoFactor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "social_preview_images" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "source" "social_preview_source" NOT NULL,
    "angle" "social_preview_angle",
    "topic" TEXT,
    "prompt" TEXT,
    "provider" TEXT,
    "model" TEXT,
    "storage_path" TEXT NOT NULL,
    "width" INTEGER NOT NULL,
    "height" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "social_preview_images_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "social_previews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "share_group_id" UUID,
    "image_id" UUID NOT NULL,
    "caption" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "social_previews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teacher_marketing_profiles" (
    "teacher_id" UUID NOT NULL,
    "audiences" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "learner_locations" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "levels" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "differentiator" TEXT,
    "weekly_minutes" INTEGER NOT NULL DEFAULT 60,
    "goal_new_students_per_month" INTEGER NOT NULL DEFAULT 2,
    "meme_brief" TEXT,
    "meme_style" TEXT NOT NULL DEFAULT 'varied',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "teacher_marketing_profiles_pkey" PRIMARY KEY ("teacher_id")
);

-- CreateTable
CREATE TABLE "marketing_plans" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "week_start" DATE NOT NULL,
    "weekly_minutes" INTEGER NOT NULL DEFAULT 60,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "marketing_plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "marketing_activities" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "plan_id" UUID,
    "community_id" UUID,
    "kind" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "status" "marketing_activity_status" NOT NULL DEFAULT 'planned',
    "body" TEXT,
    "title" TEXT,
    "angle_note" TEXT,
    "reason" JSONB,
    "image_id" UUID,
    "student_id" UUID,
    "tracking_code" TEXT,
    "notes" TEXT,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "marketing_activities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "acquisition_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "teacher_id" UUID NOT NULL,
    "kind" "acquisition_event_kind" NOT NULL,
    "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visitor_hash" TEXT,
    "source" TEXT,
    "medium" TEXT,
    "campaign" TEXT,
    "content" TEXT,
    "referrer" TEXT,
    "activity_id" UUID,
    "community_id" UUID,
    "lead_id" UUID,
    "student_id" UUID,
    "package_id" UUID,
    "amount_minor_units" INTEGER,
    "currency" TEXT,
    "via_referral" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "acquisition_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "teachers_email_key" ON "teachers"("email");

-- CreateIndex
CREATE UNIQUE INDEX "teachers_booking_slug_key" ON "teachers"("booking_slug");

-- CreateIndex
CREATE UNIQUE INDEX "teachers_stripe_account_id_key" ON "teachers"("stripe_account_id");

-- CreateIndex
CREATE UNIQUE INDEX "teachers_calendar_feed_token_key" ON "teachers"("calendar_feed_token");

-- CreateIndex
CREATE INDEX "teachers_created_at_idx" ON "teachers"("created_at");

-- CreateIndex
CREATE UNIQUE INDEX "students_auth_user_id_key" ON "students"("auth_user_id");

-- CreateIndex
CREATE UNIQUE INDEX "students_calendar_feed_token_key" ON "students"("calendar_feed_token");

-- CreateIndex
CREATE UNIQUE INDEX "student_invitations_token_hash_key" ON "student_invitations"("token_hash");

-- CreateIndex
CREATE INDEX "student_invitations_teacher_id_status_idx" ON "student_invitations"("teacher_id", "status");

-- CreateIndex
CREATE INDEX "student_invitations_student_id_idx" ON "student_invitations"("student_id");

-- CreateIndex
CREATE INDEX "student_invitations_status_sent_at_idx" ON "student_invitations"("status", "sent_at");

-- CreateIndex
CREATE INDEX "teacher_student_template_prices_template_id_idx" ON "teacher_student_template_prices"("template_id");

-- CreateIndex
CREATE INDEX "leads_teacher_id_status_created_at_idx" ON "leads"("teacher_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "testimonials_teacher_id_published_sort_order_idx" ON "testimonials"("teacher_id", "published", "sort_order");

-- CreateIndex
CREATE INDEX "testimonials_student_id_idx" ON "testimonials"("student_id");

-- CreateIndex
CREATE INDEX "discount_codes_teacher_id_active_idx" ON "discount_codes"("teacher_id", "active");

-- CreateIndex
CREATE UNIQUE INDEX "discount_codes_teacher_id_code_key" ON "discount_codes"("teacher_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "discount_redemptions_package_id_key" ON "discount_redemptions"("package_id");

-- CreateIndex
CREATE UNIQUE INDEX "discount_redemptions_payment_id_key" ON "discount_redemptions"("payment_id");

-- CreateIndex
CREATE INDEX "discount_redemptions_discount_code_id_idx" ON "discount_redemptions"("discount_code_id");

-- CreateIndex
CREATE INDEX "discount_redemptions_teacher_id_idx" ON "discount_redemptions"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "referral_codes_teacher_id_code_key" ON "referral_codes"("teacher_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "referral_codes_teacher_id_owner_student_id_key" ON "referral_codes"("teacher_id", "owner_student_id");

-- CreateIndex
CREATE UNIQUE INDEX "referrals_package_id_key" ON "referrals"("package_id");

-- CreateIndex
CREATE UNIQUE INDEX "referrals_payment_id_key" ON "referrals"("payment_id");

-- CreateIndex
CREATE UNIQUE INDEX "referrals_referrer_reward_code_id_key" ON "referrals"("referrer_reward_code_id");

-- CreateIndex
CREATE INDEX "referrals_teacher_id_idx" ON "referrals"("teacher_id");

-- CreateIndex
CREATE INDEX "referrals_referral_code_id_idx" ON "referrals"("referral_code_id");

-- CreateIndex
CREATE INDEX "teacher_share_groups_teacher_id_sort_order_idx" ON "teacher_share_groups"("teacher_id", "sort_order");

-- CreateIndex
CREATE INDEX "availability_rules_teacher_id_weekday_idx" ON "availability_rules"("teacher_id", "weekday");

-- CreateIndex
CREATE INDEX "blocked_dates_teacher_id_starts_at_idx" ON "blocked_dates"("teacher_id", "starts_at");

-- CreateIndex
CREATE UNIQUE INDEX "google_calendar_connections_teacher_id_key" ON "google_calendar_connections"("teacher_id");

-- CreateIndex
CREATE INDEX "google_busy_intervals_teacher_id_starts_at_idx" ON "google_busy_intervals"("teacher_id", "starts_at");

-- CreateIndex
CREATE INDEX "package_templates_teacher_id_idx" ON "package_templates"("teacher_id");

-- CreateIndex
CREATE INDEX "packages_teacher_id_student_id_idx" ON "packages"("teacher_id", "student_id");

-- CreateIndex
CREATE INDEX "packages_status_idx" ON "packages"("status");

-- CreateIndex
CREATE INDEX "packages_teacher_id_student_id_class_duration_min_status_idx" ON "packages"("teacher_id", "student_id", "class_duration_min", "status");

-- CreateIndex
CREATE INDEX "packages_status_created_at_idx" ON "packages"("status", "created_at");

-- CreateIndex
CREATE INDEX "packages_status_expires_at_idx" ON "packages"("status", "expires_at");

-- CreateIndex
CREATE INDEX "bookings_teacher_id_scheduled_start_idx" ON "bookings"("teacher_id", "scheduled_start");

-- CreateIndex
CREATE INDEX "bookings_student_id_scheduled_start_idx" ON "bookings"("student_id", "scheduled_start");

-- CreateIndex
CREATE INDEX "bookings_status_idx" ON "bookings"("status");

-- CreateIndex
CREATE INDEX "bookings_package_id_status_idx" ON "bookings"("package_id", "status");

-- CreateIndex
CREATE INDEX "bookings_status_scheduled_end_idx" ON "bookings"("status", "scheduled_end");

-- CreateIndex
CREATE INDEX "lesson_notes_booking_id_audience_position_idx" ON "lesson_notes"("booking_id", "audience", "position");

-- CreateIndex
CREATE INDEX "lesson_notes_teacher_id_idx" ON "lesson_notes"("teacher_id");

-- CreateIndex
CREATE INDEX "assignments_booking_id_created_at_idx" ON "assignments"("booking_id", "created_at");

-- CreateIndex
CREATE INDEX "assignments_teacher_id_idx" ON "assignments"("teacher_id");

-- CreateIndex
CREATE INDEX "assignments_source_material_id_idx" ON "assignments"("source_material_id");

-- CreateIndex
CREATE INDEX "homework_submissions_student_id_idx" ON "homework_submissions"("student_id");

-- CreateIndex
CREATE INDEX "homework_submissions_teacher_id_idx" ON "homework_submissions"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "homework_submissions_assignment_id_student_id_key" ON "homework_submissions"("assignment_id", "student_id");

-- CreateIndex
CREATE INDEX "homework_submission_files_submission_id_uploaded_at_idx" ON "homework_submission_files"("submission_id", "uploaded_at");

-- CreateIndex
CREATE INDEX "homework_submission_files_teacher_id_idx" ON "homework_submission_files"("teacher_id");

-- CreateIndex
CREATE INDEX "homework_submission_files_attempt_id_idx" ON "homework_submission_files"("attempt_id");

-- CreateIndex
CREATE INDEX "homework_attempts_submission_id_idx" ON "homework_attempts"("submission_id");

-- CreateIndex
CREATE UNIQUE INDEX "homework_attempts_submission_id_attempt_number_key" ON "homework_attempts"("submission_id", "attempt_number");

-- CreateIndex
CREATE UNIQUE INDEX "homework_feedback_attempt_id_key" ON "homework_feedback"("attempt_id");

-- CreateIndex
CREATE INDEX "homework_feedback_teacher_id_idx" ON "homework_feedback"("teacher_id");

-- CreateIndex
CREATE INDEX "homework_ai_review_drafts_attempt_id_created_at_idx" ON "homework_ai_review_drafts"("attempt_id", "created_at");

-- CreateIndex
CREATE INDEX "homework_ai_review_drafts_teacher_id_created_at_idx" ON "homework_ai_review_drafts"("teacher_id", "created_at");

-- CreateIndex
CREATE INDEX "class_content_generations_teacher_id_created_at_idx" ON "class_content_generations"("teacher_id", "created_at");

-- CreateIndex
CREATE INDEX "class_content_templates_teacher_id_position_idx" ON "class_content_templates"("teacher_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "lesson_summaries_booking_id_key" ON "lesson_summaries"("booking_id");

-- CreateIndex
CREATE INDEX "lesson_summaries_teacher_id_idx" ON "lesson_summaries"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "call_recordings_egress_id_key" ON "call_recordings"("egress_id");

-- CreateIndex
CREATE INDEX "call_recordings_booking_id_idx" ON "call_recordings"("booking_id");

-- CreateIndex
CREATE INDEX "call_recordings_teacher_id_idx" ON "call_recordings"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "lesson_audio_egress_id_key" ON "lesson_audio"("egress_id");

-- CreateIndex
CREATE INDEX "lesson_audio_booking_id_idx" ON "lesson_audio"("booking_id");

-- CreateIndex
CREATE INDEX "lesson_audio_teacher_id_idx" ON "lesson_audio"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "lesson_transcripts_booking_id_key" ON "lesson_transcripts"("booking_id");

-- CreateIndex
CREATE INDEX "lesson_transcripts_teacher_id_idx" ON "lesson_transcripts"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "intro_video_analyses_teacher_id_key" ON "intro_video_analyses"("teacher_id");

-- CreateIndex
CREATE INDEX "lesson_insights_booking_id_category_idx" ON "lesson_insights"("booking_id", "category");

-- CreateIndex
CREATE INDEX "lesson_insights_teacher_id_idx" ON "lesson_insights"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "lesson_pronunciation_booking_id_key" ON "lesson_pronunciation"("booking_id");

-- CreateIndex
CREATE INDEX "lesson_pronunciation_teacher_id_idx" ON "lesson_pronunciation"("teacher_id");

-- CreateIndex
CREATE INDEX "student_learning_profiles_teacher_id_idx" ON "student_learning_profiles"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "student_learning_profiles_teacher_id_student_id_key" ON "student_learning_profiles"("teacher_id", "student_id");

-- CreateIndex
CREATE UNIQUE INDEX "lesson_briefs_booking_id_key" ON "lesson_briefs"("booking_id");

-- CreateIndex
CREATE INDEX "lesson_briefs_teacher_id_idx" ON "lesson_briefs"("teacher_id");

-- CreateIndex
CREATE INDEX "vocabulary_reviews_student_id_due_at_idx" ON "vocabulary_reviews"("student_id", "due_at");

-- CreateIndex
CREATE UNIQUE INDEX "vocabulary_reviews_teacher_id_student_id_term_key" ON "vocabulary_reviews"("teacher_id", "student_id", "term");

-- CreateIndex
CREATE INDEX "levels_teacher_id_position_idx" ON "levels"("teacher_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "levels_teacher_id_code_key" ON "levels"("teacher_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "levels_teacher_id_position_key" ON "levels"("teacher_id", "position");

-- CreateIndex
CREATE INDEX "focus_tag_categories_teacher_id_position_idx" ON "focus_tag_categories"("teacher_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "focus_tag_categories_teacher_id_code_key" ON "focus_tag_categories"("teacher_id", "code");

-- CreateIndex
CREATE INDEX "focus_tags_teacher_id_position_idx" ON "focus_tags"("teacher_id", "position");

-- CreateIndex
CREATE INDEX "focus_tags_category_id_idx" ON "focus_tags"("category_id");

-- CreateIndex
CREATE UNIQUE INDEX "focus_tags_teacher_id_code_key" ON "focus_tags"("teacher_id", "code");

-- CreateIndex
CREATE INDEX "library_materials_teacher_id_level_id_position_idx" ON "library_materials"("teacher_id", "level_id", "position");

-- CreateIndex
CREATE INDEX "library_materials_teacher_id_booking_id_idx" ON "library_materials"("teacher_id", "booking_id");

-- CreateIndex
CREATE INDEX "lib_mat_teacher_booking_archived_created_idx" ON "library_materials"("teacher_id", "booking_id", "archived", "created_at", "id");

-- CreateIndex
CREATE INDEX "lib_mat_teacher_booking_archived_label_idx" ON "library_materials"("teacher_id", "booking_id", "archived", "label");

-- CreateIndex
CREATE INDEX "material_revisions_material_id_created_at_idx" ON "material_revisions"("material_id", "created_at");

-- CreateIndex
CREATE INDEX "material_revisions_teacher_id_idx" ON "material_revisions"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "material_podcasts_material_id_key" ON "material_podcasts"("material_id");

-- CreateIndex
CREATE INDEX "material_podcasts_teacher_id_idx" ON "material_podcasts"("teacher_id");

-- CreateIndex
CREATE INDEX "library_material_focus_tags_focus_tag_id_idx" ON "library_material_focus_tags"("focus_tag_id");

-- CreateIndex
CREATE INDEX "booking_library_materials_library_material_id_idx" ON "booking_library_materials"("library_material_id");

-- CreateIndex
CREATE INDEX "class_material_uses_material_id_idx" ON "class_material_uses"("material_id");

-- CreateIndex
CREATE INDEX "class_material_uses_teacher_id_opened_at_idx" ON "class_material_uses"("teacher_id", "opened_at");

-- CreateIndex
CREATE UNIQUE INDEX "class_material_uses_booking_id_material_id_key" ON "class_material_uses"("booking_id", "material_id");

-- CreateIndex
CREATE INDEX "student_library_items_teacher_id_student_id_idx" ON "student_library_items"("teacher_id", "student_id");

-- CreateIndex
CREATE UNIQUE INDEX "student_library_items_student_id_library_material_id_key" ON "student_library_items"("student_id", "library_material_id");

-- CreateIndex
CREATE INDEX "student_notes_teacher_id_student_id_created_at_idx" ON "student_notes"("teacher_id", "student_id", "created_at");

-- CreateIndex
CREATE INDEX "teacher_payout_instruments_teacher_id_idx" ON "teacher_payout_instruments"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_payout_instruments_teacher_id_kind_key" ON "teacher_payout_instruments"("teacher_id", "kind");

-- CreateIndex
CREATE UNIQUE INDEX "payments_provider_payment_id_key" ON "payments"("provider_payment_id");

-- CreateIndex
CREATE UNIQUE INDEX "payments_external_reference_key" ON "payments"("external_reference");

-- CreateIndex
CREATE UNIQUE INDEX "payments_payment_reference_key" ON "payments"("payment_reference");

-- CreateIndex
CREATE INDEX "payments_package_id_idx" ON "payments"("package_id");

-- CreateIndex
CREATE INDEX "payments_status_idx" ON "payments"("status");

-- CreateIndex
CREATE INDEX "payments_status_created_at_idx" ON "payments"("status", "created_at");

-- CreateIndex
CREATE INDEX "payments_status_paid_at_idx" ON "payments"("status", "paid_at");

-- CreateIndex
CREATE INDEX "payments_instrument_id_idx" ON "payments"("instrument_id");

-- CreateIndex
CREATE INDEX "overrides_teacher_id_target_type_target_id_idx" ON "overrides"("teacher_id", "target_type", "target_id");

-- CreateIndex
CREATE INDEX "overrides_actor_admin_id_idx" ON "overrides"("actor_admin_id");

-- CreateIndex
CREATE INDEX "overrides_created_at_idx" ON "overrides"("created_at");

-- CreateIndex
CREATE INDEX "student_contact_changes_student_id_idx" ON "student_contact_changes"("student_id");

-- CreateIndex
CREATE UNIQUE INDEX "notifications_provider_message_id_key" ON "notifications"("provider_message_id");

-- CreateIndex
CREATE INDEX "notifications_teacher_id_created_at_idx" ON "notifications"("teacher_id", "created_at");

-- CreateIndex
CREATE INDEX "notifications_status_idx" ON "notifications"("status");

-- CreateIndex
CREATE INDEX "notifications_booking_id_idx" ON "notifications"("booking_id");

-- CreateIndex
CREATE INDEX "notifications_recipient_type_recipient_id_created_at_idx" ON "notifications"("recipient_type", "recipient_id", "created_at");

-- CreateIndex
CREATE INDEX "notifications_teacher_id_template_name_idx" ON "notifications"("teacher_id", "template_name");

-- CreateIndex
CREATE INDEX "notifications_status_created_at_idx" ON "notifications"("status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "web_push_subscriptions_endpoint_key" ON "web_push_subscriptions"("endpoint");

-- CreateIndex
CREATE INDEX "web_push_subscriptions_recipient_idx" ON "web_push_subscriptions"("recipient_type", "recipient_id");

-- CreateIndex
CREATE INDEX "webhook_events_received_at_idx" ON "webhook_events"("received_at");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_events_provider_event_unique" ON "webhook_events"("provider", "event_id");

-- CreateIndex
CREATE UNIQUE INDEX "disputes_stripe_dispute_id_key" ON "disputes"("stripe_dispute_id");

-- CreateIndex
CREATE INDEX "disputes_teacher_created_idx" ON "disputes"("teacher_id", "created_at");

-- CreateIndex
CREATE INDEX "disputes_status_idx" ON "disputes"("status");

-- CreateIndex
CREATE INDEX "disputes_is_final_created_idx" ON "disputes"("is_final", "created_at");

-- CreateIndex
CREATE INDEX "account_deletion_subject_idx" ON "account_deletion_requests"("subject_type", "subject_id");

-- CreateIndex
CREATE INDEX "account_deletion_schedule_idx" ON "account_deletion_requests"("status", "scheduled_for");

-- CreateIndex
CREATE UNIQUE INDEX "admin_users_email_key" ON "admin_users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "uat_checklist_state_target_env_key" ON "uat_checklist_state"("target_env");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_subscriptions_teacher_id_key" ON "teacher_subscriptions"("teacher_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_subscriptions_stripe_customer_id_key" ON "teacher_subscriptions"("stripe_customer_id");

-- CreateIndex
CREATE UNIQUE INDEX "teacher_subscriptions_stripe_subscription_id_key" ON "teacher_subscriptions"("stripe_subscription_id");

-- CreateIndex
CREATE INDEX "teacher_subscriptions_status_idx" ON "teacher_subscriptions"("status");

-- CreateIndex
CREATE INDEX "teacher_subscriptions_plan_idx" ON "teacher_subscriptions"("plan");

-- CreateIndex
CREATE UNIQUE INDEX "subscription_invoices_stripe_invoice_id_key" ON "subscription_invoices"("stripe_invoice_id");

-- CreateIndex
CREATE INDEX "subscription_invoices_teacher_id_period_start_idx" ON "subscription_invoices"("teacher_id", "period_start");

-- CreateIndex
CREATE INDEX "subscription_invoices_status_idx" ON "subscription_invoices"("status");

-- CreateIndex
CREATE INDEX "platform_expenses_period_month_idx" ON "platform_expenses"("period_month");

-- CreateIndex
CREATE INDEX "platform_expenses_vendor_period_month_idx" ON "platform_expenses"("vendor", "period_month");

-- CreateIndex
CREATE UNIQUE INDEX "integrations_key_key" ON "integrations"("key");

-- CreateIndex
CREATE INDEX "integrations_category_idx" ON "integrations"("category");

-- CreateIndex
CREATE INDEX "integrations_active_idx" ON "integrations"("active");

-- CreateIndex
CREATE INDEX "usage_inputs_period_month_idx" ON "usage_inputs"("period_month");

-- CreateIndex
CREATE UNIQUE INDEX "usage_inputs_metric_period_month_key" ON "usage_inputs"("metric", "period_month");

-- CreateIndex
CREATE INDEX "messages_teacher_id_student_id_created_at_idx" ON "messages"("teacher_id", "student_id", "created_at");

-- CreateIndex
CREATE INDEX "messages_reply_to_id_idx" ON "messages"("reply_to_id");

-- CreateIndex
CREATE UNIQUE INDEX "message_reactions_message_id_reactor_role_key" ON "message_reactions"("message_id", "reactor_role");

-- CreateIndex
CREATE UNIQUE INDEX "user_email_key" ON "user"("email");

-- CreateIndex
CREATE INDEX "session_userId_idx" ON "session"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "session_token_key" ON "session"("token");

-- CreateIndex
CREATE INDEX "account_userId_idx" ON "account"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "account_providerId_accountId_key" ON "account"("providerId", "accountId");

-- CreateIndex
CREATE INDEX "verification_identifier_idx" ON "verification"("identifier");

-- CreateIndex
CREATE INDEX "twoFactor_secret_idx" ON "twoFactor"("secret");

-- CreateIndex
CREATE INDEX "twoFactor_userId_idx" ON "twoFactor"("userId");

-- CreateIndex
CREATE INDEX "social_preview_images_teacher_id_created_at_idx" ON "social_preview_images"("teacher_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "social_previews_share_group_id_key" ON "social_previews"("share_group_id");

-- CreateIndex
CREATE INDEX "social_previews_teacher_id_idx" ON "social_previews"("teacher_id");

-- CreateIndex
CREATE INDEX "social_previews_image_id_idx" ON "social_previews"("image_id");

-- CreateIndex
CREATE INDEX "marketing_plans_teacher_id_week_start_idx" ON "marketing_plans"("teacher_id", "week_start");

-- CreateIndex
CREATE UNIQUE INDEX "marketing_plans_teacher_id_week_start_key" ON "marketing_plans"("teacher_id", "week_start");

-- CreateIndex
CREATE UNIQUE INDEX "marketing_activities_tracking_code_key" ON "marketing_activities"("tracking_code");

-- CreateIndex
CREATE INDEX "marketing_activities_teacher_id_status_created_at_idx" ON "marketing_activities"("teacher_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "marketing_activities_plan_id_idx" ON "marketing_activities"("plan_id");

-- CreateIndex
CREATE INDEX "marketing_activities_community_id_idx" ON "marketing_activities"("community_id");

-- CreateIndex
CREATE INDEX "acquisition_events_teacher_id_kind_occurred_at_idx" ON "acquisition_events"("teacher_id", "kind", "occurred_at");

-- CreateIndex
CREATE INDEX "acquisition_events_teacher_id_occurred_at_idx" ON "acquisition_events"("teacher_id", "occurred_at");

-- CreateIndex
CREATE INDEX "acquisition_events_activity_id_idx" ON "acquisition_events"("activity_id");

-- CreateIndex
CREATE INDEX "acquisition_events_community_id_idx" ON "acquisition_events"("community_id");

-- CreateIndex
CREATE INDEX "acquisition_events_package_id_idx" ON "acquisition_events"("package_id");

-- AddForeignKey
ALTER TABLE "teachers" ADD CONSTRAINT "teachers_id_fkey" FOREIGN KEY ("id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "students" ADD CONSTRAINT "students_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_invitations" ADD CONSTRAINT "student_invitations_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_invitations" ADD CONSTRAINT "student_invitations_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_students" ADD CONSTRAINT "teacher_students_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_students" ADD CONSTRAINT "teacher_students_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_students" ADD CONSTRAINT "teacher_students_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "levels"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_student_template_prices" ADD CONSTRAINT "teacher_student_template_prices_teacher_id_student_id_fkey" FOREIGN KEY ("teacher_id", "student_id") REFERENCES "teacher_students"("teacher_id", "student_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_student_template_prices" ADD CONSTRAINT "teacher_student_template_prices_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "package_templates"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "leads" ADD CONSTRAINT "leads_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "testimonials" ADD CONSTRAINT "testimonials_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "testimonials" ADD CONSTRAINT "testimonials_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_codes" ADD CONSTRAINT "discount_codes_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_codes" ADD CONSTRAINT "discount_codes_reserved_for_student_id_fkey" FOREIGN KEY ("reserved_for_student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_discount_code_id_fkey" FOREIGN KEY ("discount_code_id") REFERENCES "discount_codes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referral_programs" ADD CONSTRAINT "referral_programs_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referral_codes" ADD CONSTRAINT "referral_codes_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referral_codes" ADD CONSTRAINT "referral_codes_owner_student_id_fkey" FOREIGN KEY ("owner_student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_referral_code_id_fkey" FOREIGN KEY ("referral_code_id") REFERENCES "referral_codes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_referred_student_id_fkey" FOREIGN KEY ("referred_student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_referrer_reward_code_id_fkey" FOREIGN KEY ("referrer_reward_code_id") REFERENCES "discount_codes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "referrals" ADD CONSTRAINT "referrals_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_share_groups" ADD CONSTRAINT "teacher_share_groups_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "availability_rules" ADD CONSTRAINT "availability_rules_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "blocked_dates" ADD CONSTRAINT "blocked_dates_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "google_calendar_connections" ADD CONSTRAINT "google_calendar_connections_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "google_busy_intervals" ADD CONSTRAINT "google_busy_intervals_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "package_templates" ADD CONSTRAINT "package_templates_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packages" ADD CONSTRAINT "packages_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "package_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_reschedule_of_booking_id_fkey" FOREIGN KEY ("reschedule_of_booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_notes" ADD CONSTRAINT "lesson_notes_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_source_material_id_fkey" FOREIGN KEY ("source_material_id") REFERENCES "library_materials"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_source_material_revision_id_fkey" FOREIGN KEY ("source_material_revision_id") REFERENCES "material_revisions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_submissions" ADD CONSTRAINT "homework_submissions_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "assignments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_submissions" ADD CONSTRAINT "homework_submissions_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_submission_files" ADD CONSTRAINT "homework_submission_files_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "homework_submissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_submission_files" ADD CONSTRAINT "homework_submission_files_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "homework_attempts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_attempts" ADD CONSTRAINT "homework_attempts_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "homework_submissions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_feedback" ADD CONSTRAINT "homework_feedback_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "homework_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_feedback" ADD CONSTRAINT "homework_feedback_ai_draft_id_fkey" FOREIGN KEY ("ai_draft_id") REFERENCES "homework_ai_review_drafts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "homework_ai_review_drafts" ADD CONSTRAINT "homework_ai_review_drafts_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "homework_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_content_templates" ADD CONSTRAINT "class_content_templates_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_summaries" ADD CONSTRAINT "lesson_summaries_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "call_recordings" ADD CONSTRAINT "call_recordings_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_audio" ADD CONSTRAINT "lesson_audio_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_transcripts" ADD CONSTRAINT "lesson_transcripts_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "intro_video_analyses" ADD CONSTRAINT "intro_video_analyses_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_insights" ADD CONSTRAINT "lesson_insights_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_pronunciation" ADD CONSTRAINT "lesson_pronunciation_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_learning_profiles" ADD CONSTRAINT "student_learning_profiles_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_learning_profiles" ADD CONSTRAINT "student_learning_profiles_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lesson_briefs" ADD CONSTRAINT "lesson_briefs_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vocabulary_reviews" ADD CONSTRAINT "vocabulary_reviews_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "vocabulary_reviews" ADD CONSTRAINT "vocabulary_reviews_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "levels" ADD CONSTRAINT "levels_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "focus_tag_categories" ADD CONSTRAINT "focus_tag_categories_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "focus_tags" ADD CONSTRAINT "focus_tags_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "focus_tags" ADD CONSTRAINT "focus_tags_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "focus_tag_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_materials" ADD CONSTRAINT "library_materials_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_materials" ADD CONSTRAINT "library_materials_level_id_fkey" FOREIGN KEY ("level_id") REFERENCES "levels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_materials" ADD CONSTRAINT "library_materials_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material_revisions" ADD CONSTRAINT "material_revisions_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material_podcasts" ADD CONSTRAINT "material_podcasts_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "material_podcasts" ADD CONSTRAINT "material_podcasts_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_material_focus_tags" ADD CONSTRAINT "library_material_focus_tags_library_material_id_fkey" FOREIGN KEY ("library_material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "library_material_focus_tags" ADD CONSTRAINT "library_material_focus_tags_focus_tag_id_fkey" FOREIGN KEY ("focus_tag_id") REFERENCES "focus_tags"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_library_materials" ADD CONSTRAINT "booking_library_materials_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "booking_library_materials" ADD CONSTRAINT "booking_library_materials_library_material_id_fkey" FOREIGN KEY ("library_material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_material_uses" ADD CONSTRAINT "class_material_uses_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_material_uses" ADD CONSTRAINT "class_material_uses_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "class_material_uses" ADD CONSTRAINT "class_material_uses_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_library_items" ADD CONSTRAINT "student_library_items_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_library_items" ADD CONSTRAINT "student_library_items_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_library_items" ADD CONSTRAINT "student_library_items_library_material_id_fkey" FOREIGN KEY ("library_material_id") REFERENCES "library_materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_notes" ADD CONSTRAINT "student_notes_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_notes" ADD CONSTRAINT "student_notes_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_payout_instruments" ADD CONSTRAINT "teacher_payout_instruments_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_package_id_fkey" FOREIGN KEY ("package_id") REFERENCES "packages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_instrument_id_fkey" FOREIGN KEY ("instrument_id") REFERENCES "teacher_payout_instruments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "overrides" ADD CONSTRAINT "overrides_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "overrides" ADD CONSTRAINT "overrides_actor_admin_id_fkey" FOREIGN KEY ("actor_admin_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_contact_changes" ADD CONSTRAINT "student_contact_changes_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_contact_changes" ADD CONSTRAINT "student_contact_changes_actor_teacher_id_fkey" FOREIGN KEY ("actor_teacher_id") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "student_contact_changes" ADD CONSTRAINT "student_contact_changes_actor_admin_id_fkey" FOREIGN KEY ("actor_admin_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_payment_id_fkey" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_users" ADD CONSTRAINT "admin_users_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_subscriptions" ADD CONSTRAINT "teacher_subscriptions_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "subscription_invoices" ADD CONSTRAINT "subscription_invoices_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "messages" ADD CONSTRAINT "messages_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "messages" ADD CONSTRAINT "messages_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "messages" ADD CONSTRAINT "messages_reply_to_id_fkey" FOREIGN KEY ("reply_to_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "message_reactions" ADD CONSTRAINT "message_reactions_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session" ADD CONSTRAINT "session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "account" ADD CONSTRAINT "account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "twoFactor" ADD CONSTRAINT "twoFactor_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "social_preview_images" ADD CONSTRAINT "social_preview_images_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "social_previews" ADD CONSTRAINT "social_previews_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "social_previews" ADD CONSTRAINT "social_previews_share_group_id_fkey" FOREIGN KEY ("share_group_id") REFERENCES "teacher_share_groups"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "social_previews" ADD CONSTRAINT "social_previews_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "social_preview_images"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teacher_marketing_profiles" ADD CONSTRAINT "teacher_marketing_profiles_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_plans" ADD CONSTRAINT "marketing_plans_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_activities" ADD CONSTRAINT "marketing_activities_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_activities" ADD CONSTRAINT "marketing_activities_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "marketing_plans"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_activities" ADD CONSTRAINT "marketing_activities_community_id_fkey" FOREIGN KEY ("community_id") REFERENCES "teacher_share_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_activities" ADD CONSTRAINT "marketing_activities_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "social_preview_images"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketing_activities" ADD CONSTRAINT "marketing_activities_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "acquisition_events" ADD CONSTRAINT "acquisition_events_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teachers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "acquisition_events" ADD CONSTRAINT "acquisition_events_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "marketing_activities"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "acquisition_events" ADD CONSTRAINT "acquisition_events_community_id_fkey" FOREIGN KEY ("community_id") REFERENCES "teacher_share_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

