// Generates src/lib/og-font-data.ts — the brand face, base64, for Satori.
//
// WHY INLINE RATHER THAN READ FROM DISK. The first version resolved the woff
// out of node_modules at request time. It worked locally and failed the build:
// `output: standalone` does not copy node_modules, and no amount of
// outputFileTracingIncludes made `createRequire` resolution work from inside
// the built server bundle.
//
// Worse, the fallback was wrong. It returned an empty font list "so a bad read
// degrades instead of throwing" — but Satori REQUIRES at least one font and
// throws "No fonts are loaded" without one, so the safe-looking degradation
// was itself the crash. There is no graceful failure available here, which
// means the load must not be able to fail: no filesystem, no resolution, no
// I/O at all.
//
//   node scripts/og-font.mjs
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const require = createRequire(import.meta.url);
const weights = [400, 700];

const parts = weights.map((w) => {
  const file = require.resolve(
    `@fontsource/atkinson-hyperlegible/files/atkinson-hyperlegible-latin-${w}-normal.woff`,
  );
  const bytes = readFileSync(file);
  if (bytes.subarray(0, 4).toString("latin1") !== "wOFF") {
    throw new Error(`${file} is not a WOFF — Satori cannot read WOFF2.`);
  }
  return `  ${w}: "${bytes.toString("base64")}",`;
});

const out = `// GENERATED by scripts/og-font.mjs — do not edit.
//
// Atkinson Hyperlegible, latin subset, as base64.
// Copyright 2020 Braille Institute of America, Inc.
// Licensed under the SIL Open Font License, Version 1.1 — see /NOTICE.
// Inlined rather than read from disk because the standalone build does not ship
// node_modules, and Satori throws without a font — so this load must not be
// able to fail. See scripts/og-font.mjs for the full reasoning.
export const OG_FONT_BASE64: Record<400 | 700, string> = {
${parts.join("\n")}
};
`;

const target = resolve(import.meta.dirname, "../src/lib/og-font-data.ts");
writeFileSync(target, out);
console.log(`og font data written: ${(out.length / 1024).toFixed(0)} KB`);
