// Generates src/lib/seed/placeholder-video-data.ts — the seeded intro-video
// clip, base64, for scripts/seed.ts to upload.
//
//   npx tsx scripts/seed-clip.ts        (needs ffmpeg on PATH; run by hand)
//
// WHY INLINE RATHER THAN A COMMITTED .mp4 READ FROM DISK. The preview reseed
// does not run from a checkout — it runs `main()` from scripts/seed.ts inside
// the deployed Fly app (lib/inngest/functions/admin-reseed-preview.ts), and
// `output: standalone` does not ship repo files. That is the same trap
// lib/og-font.ts documents: a filesystem read works locally and silently fails
// exactly where it has to work. The existing seed-material.pdf fixture read is
// a live instance of it — wrapped in a try/catch that warns and moves on, so
// on preview the material row points at an object nobody uploaded.
//
// So the clip carries no I/O: no filesystem, no module resolution. Same answer
// og-font-data.ts already reached for the same reason.
//
// WHY IT IS GENERATED RATHER THAN DROPPED IN. Regenerable from source (the
// teacher's own monogram, held for four seconds) means nobody has to trust an
// opaque binary in the tree, and 5 KB of base64 is cheaper than the tracing
// config a committed asset would need.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
import { seedPlaceholderPhotoPng } from "@/lib/seed/placeholder-photo";

async function main() {
  const dir = mkdtempSync(join(tmpdir(), "seed-clip-"));
  const framePath = join(dir, "frame.png");
  const clipPath = join(dir, "clip.mp4");

  // The frame is the seeded teacher's own monogram, so the video card and the
  // avatar are visibly the same placeholder rather than two unrelated stand-ins.
  writeFileSync(framePath, await seedPlaceholderPhotoPng("Paula Pagos", "paula@spiralclass.test"));

  execFileSync(
    "ffmpeg",
    [
      "-loglevel",
      "error",
      "-loop",
      "1",
      "-i",
      framePath,
      "-t",
      "4",
      "-r",
      "12",
      "-vf",
      "scale=480:480",
      "-c:v",
      "libx264",
      "-pix_fmt",
      "yuv420p",
      // faststart puts `moov` ahead of `mdat` so the card can decode a first
      // frame instead of sitting on a coloured block.
      "-movflags",
      "+faststart",
      "-y",
      clipPath,
    ],
    { stdio: "inherit" },
  );

  const bytes = readFileSync(clipPath);
  if (bytes.toString("latin1", 4, 8) !== "ftyp") throw new Error("ffmpeg did not emit an MP4");

  const out = `// GENERATED by scripts/seed-clip.ts — do not edit.
//
// A 4-second silent H.264 placeholder intro video (480x480, faststart), as
// base64. Inlined rather than read from disk because the preview reseed runs
// inside the deployed standalone build, which ships no repo files — see
// scripts/seed-clip.ts for the full reasoning.
export const SEED_CLIP_BASE64 =
  "${bytes.toString("base64")}";
`;

  const target = resolve(import.meta.dirname, "../src/lib/seed/placeholder-video-data.ts");
  writeFileSync(target, out);
  console.log(`seed clip written: ${bytes.length} bytes → ${(out.length / 1024).toFixed(1)} KB`);
}

main();
