import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  buildErdGraph,
  serializeGraph,
  DBML_PATH,
  OUTPUT_PATH,
} from "../scripts/generate-erd-schema.mjs";
import type { ErdSchemaGraph } from "../src/lib/erd/types";
import { adminRouteForTable } from "../src/lib/erd/admin-routes";
import { computeLayout, nodeHeight } from "../src/lib/erd/layout";

// The DBML is regenerated by `prisma generate` (apps/web postinstall), so it is
// always present after install/CI setup. Fail loudly with a fix hint rather
// than silently skipping if it's somehow absent.
function readDbml(): string {
  if (!existsSync(DBML_PATH)) {
    throw new Error(
      `${DBML_PATH} not found — run \`pnpm --filter spiralclass-web prisma:generate\` first.`,
    );
  }
  return readFileSync(DBML_PATH, "utf8");
}

const committed = JSON.parse(readFileSync(OUTPUT_PATH, "utf8")) as ErdSchemaGraph;
const graph = buildErdGraph(readDbml());

describe("ERD schema graph — drift guard", () => {
  // If this fails, the committed schema.generated.json is stale: someone
  // changed the Prisma schema without regenerating. Fix:
  //   pnpm --filter spiralclass-web erd:generate
  it("committed JSON matches what the generator produces from the current DBML", () => {
    expect(serializeGraph(graph)).toEqual(readFileSync(OUTPUT_PATH, "utf8"));
  });

  it("is deterministic (same input → byte-identical output)", () => {
    expect(serializeGraph(buildErdGraph(readDbml()))).toEqual(serializeGraph(graph));
  });
});

describe("ERD schema graph — structural invariants", () => {
  const tableIds = new Set(committed.tables.map((t) => t.id));
  const columnsByTable = new Map(
    committed.tables.map((t) => [t.id, new Set(t.columns.map((c) => c.name))]),
  );

  it("has tables, relationships, enums and at least one schema", () => {
    expect(committed.tables.length).toBeGreaterThan(0);
    expect(committed.relationships.length).toBeGreaterThan(0);
    expect(committed.schemas.length).toBeGreaterThan(0);
  });

  it("every relationship endpoint references an existing table and its columns", () => {
    for (const rel of committed.relationships) {
      expect(tableIds, rel.id).toContain(rel.source.table);
      expect(tableIds, rel.id).toContain(rel.target.table);
      for (const col of rel.source.columns) {
        expect(columnsByTable.get(rel.source.table), `${rel.id} source col`).toContain(col);
      }
      for (const col of rel.target.columns) {
        expect(columnsByTable.get(rel.target.table), `${rel.id} target col`).toContain(col);
      }
    }
  });

  it("flags every source (FK) column as a foreign key on its table", () => {
    for (const rel of committed.relationships) {
      const table = committed.tables.find((t) => t.id === rel.source.table)!;
      for (const colName of rel.source.columns) {
        const col = table.columns.find((c) => c.name === colName)!;
        expect(col.isForeignKey, `${rel.source.table}.${colName}`).toBe(true);
      }
    }
  });

  it("gives every table a stable schema-qualified id", () => {
    for (const table of committed.tables) {
      expect(table.id).toBe(`${table.schema}.${table.name}`);
    }
    // ids are unique
    expect(new Set(committed.tables.map((t) => t.id)).size).toBe(committed.tables.length);
  });

  it("only emits known cardinalities", () => {
    const known = new Set(["one-to-one", "one-to-many", "many-to-one", "many-to-many"]);
    for (const rel of committed.relationships) {
      expect(known).toContain(rel.cardinality);
    }
  });
});

describe("ERD admin-route map", () => {
  it("maps known tables to existing admin routes and nothing else", () => {
    expect(adminRouteForTable("teachers")).toBe("/admin/teachers");
    expect(adminRouteForTable("teacher_subscriptions")).toBe("/admin/subscriptions");
    expect(adminRouteForTable("does_not_exist")).toBeNull();
  });

  it("only points at tables that exist in the schema", () => {
    const names = new Set(committed.tables.map((t) => t.name));
    for (const table of ["teachers", "students", "packages", "disputes", "notifications"]) {
      expect(names, table).toContain(table);
      expect(adminRouteForTable(table)).not.toBeNull();
    }
  });
});

describe("ERD layout", () => {
  it("nodeHeight grows when a table is expanded", () => {
    const table = committed.tables[0];
    expect(nodeHeight(table, true)).toBeGreaterThan(nodeHeight(table, false));
  });

  it("computeLayout returns a position for every table", async () => {
    const positions = await computeLayout(committed.tables, committed.relationships, new Set());
    for (const table of committed.tables) {
      const pos = positions.get(table.id);
      expect(pos, table.id).toBeDefined();
      expect(Number.isFinite(pos!.x)).toBe(true);
      expect(Number.isFinite(pos!.y)).toBe(true);
    }
  });
});
