import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The email logo is a real image.
 *
 * WHY THIS IS A TEST AND NOT A COMMENT. `mark-ink.png` shipped for weeks as a
 * 96x96 PNG containing a few stray pixels of the spiral in one corner and
 * nothing else, so every transactional email opened with a blank box above the
 * wordmark. It was generated by `qlmanage -t`, which produces a Quick Look
 * THUMBNAIL rather than a render, and it failed silently.
 *
 * Every check it had passed. The file existed. It was a valid PNG. It was the
 * right dimensions. Production served it 200 with the right content-type. What
 * nobody checked was whether there was a picture in it — and that took a person
 * opening an email to notice.
 *
 * A PNG of almost nothing compresses to almost nothing, so size is a blunt but
 * honest proxy for "has ink in it": the broken file was 1,140 bytes and the
 * correct one is over 3,000.
 */
describe("the email logo", () => {
  const png = readFileSync(join(__dirname, "..", "..", "public", "brand", "mark-ink.png"));

  it("is a PNG", () => {
    expect(png.subarray(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
  });

  it("is 96px square — 2x the 48px it displays at", () => {
    // Width and height live at bytes 16-24 of the IHDR chunk.
    expect(png.readUInt32BE(16)).toBe(96);
    expect(png.readUInt32BE(20)).toBe(96);
  });

  it("actually contains a mark rather than a mostly-empty canvas", () => {
    // The exact regression. 2,000 sits well above the 1,140-byte blank and well
    // below the ~3,200 a real render produces, so it catches the failure
    // without tripping on ordinary compression drift.
    expect(
      png.length,
      "mark-ink.png looks blank — regenerate with scripts/brand-assets.mjs",
    ).toBeGreaterThan(2000);
  });
});
