import { describe, expect, it } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * No file may still carry the retired brand.
 *
 * WHY. D-138 renamed the product and D-140 replaced the palette, and between
 * them they left the old terracotta in every surface no guard could see. Found
 * one at a time, by eye, over a day:
 *
 *   - `<meta name="theme-color">` — the mobile address bar, in a PRIMARY colour
 *     that was never a background.
 *   - `manifest.ts` `theme_color` — the same mistake again, in a second file,
 *     found only because the first one was.
 *   - `src/app/icon.svg` — the browser-tab favicon, whole cloth.
 *   - `public/brand/whatsapp-group-icon.svg` — hand-drawn, in a directory whose
 *     own header says everything in it is generated.
 *   - The OG card's gradient end, a dark terracotta the new indigo graded into.
 *   - The visual gallery's own stylesheet — the design evidence, styled in the
 *     brand the evidence supersedes.
 *
 * Every one was invisible to `theme-parity` (palette vs CSS only) and to the
 * drift scanner (which counts arbitrary values, not wrong ones). This checks
 * the thing itself: the retired hexes must not appear anywhere.
 */

const ROOTS = ["src", "public", "scripts"].map((d) => join(__dirname, "..", "..", d));

/** The pre-D-140 palette. Kept as literals deliberately — deriving them from
 * anything current would be the tautology that let the type scale ship 11px
 * text while asserting a 17px floor. */
/** The same colours written as rgb() triples. The email shell carried
 * `rgba(184,71,46,0.04)` — the terracotta primary — straight through a guard
 * that only knew about hex, which is a good reminder that a scanner sees the
 * spellings you gave it and no others. */
const RETIRED_RGB = ["184,71,46", "251,247,240", "232,177,75", "31,20,16", "142,53,34"];

const RETIRED = [
  "#B8472E", // terracotta primary
  "#B7472D", // its earlier spelling
  "#FBF7F0", // cream ground
  "#FAF6EE", // its earlier spelling
  "#E8B14B", // old gold
  "#D6A24E", // old gold, second spelling
  "#1F1410", // old ink
  "#1E130F", // old ink, second spelling
  "#8E3522", // the OG gradient end
];

/** Files whose JOB is to mention the retired values. */
const ALLOWED = [
  "lib/theme-color.ts", // explains the bug in a comment
  "tests/config/retired-brand.test.ts",
  "tests/seo/theme-color.test.ts",
  "tests/design-drift.test.ts", // uses one as scanner input
  "api/og/social-preview", // names the old gradient end in a comment
];

function walk(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (!["node_modules", ".next", "coverage"].includes(entry)) walk(full, out);
    } else if (/\.(tsx?|svg|css|mjs|json|html)$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

const rel = (f: string) => f.split("/apps/web/")[1] ?? f;

describe("the retired brand", () => {
  const files = ROOTS.flatMap((r) => walk(r));

  it("finds files to check", () => {
    // Guards the guard — a walk returning nothing would pass silently.
    expect(files.length).toBeGreaterThan(300);
  });

  it("appears in no file that is not explicitly about it", () => {
    const offenders: string[] = [];
    for (const file of files) {
      if (ALLOWED.some((a) => file.includes(a))) continue;
      const source = readFileSync(file, "utf8");
      for (const hex of RETIRED) {
        if (source.toUpperCase().includes(hex.toUpperCase())) {
          offenders.push(`${file.split("/apps/web/")[1] ?? file}: ${hex}`);
        }
      }
    }
    expect(
      offenders,
      `These carry the pre-D-140 brand. Every colour comes from the palette, and ` +
        `every static asset in public/brand/ is generated by scripts/brand-assets.mjs ` +
        `— regenerate it rather than editing the file:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("appears in no rgb() triple either", () => {
    const offenders: string[] = [];
    for (const file of files) {
      if (ALLOWED.some((a) => file.includes(a))) continue;
      const source = readFileSync(file, "utf8");
      for (const triple of RETIRED_RGB) {
        // Tolerate the spacing people actually write.
        const pattern = new RegExp(triple.split(",").join("\\s*,\\s*"));
        if (pattern.test(source)) {
          offenders.push(`${rel(file)}: rgb(${triple})`);
        }
      }
    }
    expect(
      offenders,
      `The retired brand, written as rgb() rather than hex:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });
});
