// AUTO-GENERATED by scripts/generate-help-content.mjs from docs/help/**/*.md.
// Do not hand-edit — change the source .md file and regenerate:
//   node scripts/generate-help-content.mjs

import type { ContentDoc } from "./types";

export const GENERATED_HELP_DOCS: readonly ContentDoc[] = [
  {
    slug: "getting-started",
    audience: "teacher",
    title: { en: `Set up your teaching account`, "es-MX": `Configura tu cuenta de profesor` },
    summary: {
      en: `Set up your profile, availability, and first class packages so students can book you.`,
      "es-MX": `Configura tu perfil, tu disponibilidad y tus primeros paquetes de clases para que los alumnos puedan reservar contigo.`,
    },
    body: {
      en: `## Purpose

Set up your profile, availability, and first class packages so students can book you.

## Before you start

- You need an email address you can open now.
- Have your teaching hours, lesson lengths, and prices ready.

## Steps

1. Choose **Create account** and enter your name and email address.
2. Enter the six-digit code sent to your email.
3. Confirm your timezone and contact details.
4. Add the days and times when you teach. Set your buffer time, minimum notice, and how far ahead students may book.
5. Create at least one package or single-class option with its duration, price, and expiry period.
6. Review your public booking page and finish setup.



## Tips

- Use the timezone where you normally teach.
- Leave a buffer between lessons so students cannot book you back-to-back.
- Your booking page becomes available after setup is complete.

Suggested video: **“Set Up Your Teaching Account (3 minutes)”**

## Troubleshooting

**I did not receive a code.** Check spam or junk mail, then request a new code. Codes expire after five minutes.

**I cannot finish availability.** Add at least one working-hours range and make sure your ranges do not overlap.

## Questions

**Can I change this later?** Yes. Open Settings to edit your profile, availability, and packages.

**Do I need a paid plan to start?** No. New teachers begin with a 30-day Pro trial and no card is required.
`,
      "es-MX": `## Propósito

Configura tu perfil, tu disponibilidad y tus primeros paquetes de clases para que los alumnos puedan reservar contigo.

## Antes de empezar

- Necesitas un correo que puedas abrir ahora mismo.
- Ten a la mano tus horarios de clase, la duración de tus lecciones y tus precios.

## Pasos

1. Elige **Crear cuenta** e ingresa tu nombre y correo electrónico.
2. Ingresa el código de seis dígitos que recibiste por correo.
3. Confirma tu zona horaria y tus datos de contacto.
4. Agrega los días y horarios en que das clase. Configura tu tiempo de descanso entre clases, tu aviso mínimo y con cuánta anticipación pueden reservar los alumnos.
5. Crea al menos un paquete u opción de clase individual con su duración, precio y periodo de vigencia.
6. Revisa tu página pública de reservas y termina la configuración.



## Consejos

- Usa la zona horaria en la que normalmente das clase.
- Deja un margen entre lecciones para que los alumnos no puedan reservarte de forma consecutiva.
- Tu página de reservas queda disponible en cuanto termines la configuración.

Video sugerido: **"Configura tu cuenta de profesor (3 minutos)"**

## Solución de problemas

**No recibí un código.** Revisa spam o correo no deseado y pide un código nuevo. Los códigos caducan a los cinco minutos.

**No puedo terminar mi disponibilidad.** Agrega al menos un rango de horario y asegúrate de que tus rangos no se traslapen.

## Preguntas

**¿Puedo cambiar esto después?** Sí. Abre Configuración para editar tu perfil, disponibilidad y paquetes.

**¿Necesito un plan de pago para empezar?** No. Los nuevos profesores comienzan con una prueba gratuita de Pro de 30 días y no se requiere tarjeta.
`,
    },
    publicFaq: true,
  },
  {
    slug: "settings-and-subscription",
    audience: "teacher",
    title: {
      en: `Manage settings and your plan`,
      "es-MX": `Administra tu configuración y tu plan`,
    },
    summary: {
      en: `Update your profile and calendar connection, control notifications, and manage your SpiralClass Free or Pro plan.`,
      "es-MX": `Actualiza tu perfil y tu conexión de calendario, controla tus notificaciones y administra tu plan Free o Pro de SpiralClass.`,
    },
    body: {
      en: `## Purpose

Update your profile and calendar connection, control notifications, and manage your SpiralClass Free or Pro plan.

## Before you start

- You must be signed in as a teacher.
- Keep access to your email if you plan to change your sign-in address.

## Steps

### Update account settings

1. Open **Settings**.
2. Edit your name, phone number, timezone, or other available profile details.
3. Save.

To change your email, enter the new address and complete the verification code sent there.

### Connect or disconnect Google Calendar

1. Open **Settings → Calendar**.
2. Choose **Connect Google Calendar** and approve access.
3. Return to SpiralClass and check that the connection is active.
4. Toggle sync off or disconnect whenever needed.

### Upgrade or manage Pro

1. Open the billing or upgrade screen.
2. Choose the available plan and complete payment.
3. Use the customer portal to update your payment method or cancel.

## Tips

- Your plan is what you pay SpiralClass for the software. It is not what it
  costs you to get paid: a payment made through Stripe carries Stripe's own
  processing fee, charged to your own Stripe account. See
  [Create packages and manage payments](packages-and-payments.md).
- Your Pro access continues until the end of a paid period if you cancel.
- After a trial ends, your account moves to Free rather than being locked.
- A failed renewal gives you seven days to update payment details before access moves to Free.

## Troubleshooting

**Why are some tools locked?** They may require Pro or be limited by your current plan.

**Why can’t I delete my account?** Account deletion is blocked while you have unused paid classes outstanding.

## Questions

**Can I export my data?** Yes. Request an export from account settings.

**Can I cancel an account deletion request?** Yes, during the 30-day grace period.
`,
      "es-MX": `## Propósito

Actualiza tu perfil y tu conexión de calendario, controla tus notificaciones y administra tu plan Free o Pro de SpiralClass.

## Antes de empezar

- Debes tener sesión iniciada como profesor.
- Conserva acceso a tu correo si planeas cambiar tu dirección de inicio de sesión.

## Pasos

### Actualizar la configuración de tu cuenta

1. Abre **Configuración**.
2. Edita tu nombre, teléfono, zona horaria u otros datos de perfil disponibles.
3. Guarda.

Para cambiar tu correo, ingresa la nueva dirección y completa el código de verificación que se envía a esa dirección.

### Conectar o desconectar Google Calendar

1. Abre **Configuración → Calendario**.
2. Elige **Conectar Google Calendar** y aprueba el acceso.
3. Regresa a SpiralClass y verifica que la conexión esté activa.
4. Desactiva la sincronización o desconéctala cuando lo necesites.

### Actualizar o administrar Pro

1. Abre la pantalla de facturación o de actualización de plan.
2. Elige el plan disponible y completa el pago.
3. Usa el portal de cliente para actualizar tu método de pago o cancelar.

## Consejos

- Tu plan es lo que le pagas a SpiralClass por el software. No es lo que te
  cuesta cobrar: un pago hecho por Stripe lleva su comisión de procesamiento,
  que se cobra en tu propia cuenta de Stripe. Consulta
  [Crea paquetes y administra pagos](packages-and-payments.md).
- Tu acceso a Pro continúa hasta el final de un periodo pagado si cancelas.
- Cuando termina una prueba gratuita, tu cuenta pasa a Free en vez de bloquearse.
- Un cobro fallido te da siete días para actualizar tus datos de pago antes de que tu cuenta pase a Free.

## Solución de problemas

**¿Por qué algunas herramientas están bloqueadas?** Es posible que requieran Pro o que estén limitadas por tu plan actual.

**¿Por qué no puedo eliminar mi cuenta?** La eliminación de cuenta se bloquea mientras tengas clases pagadas sin usar pendientes.

## Preguntas

**¿Puedo exportar mis datos?** Sí. Solicita una exportación desde la configuración de tu cuenta.

**¿Puedo cancelar una solicitud de eliminación de cuenta?** Sí, durante el periodo de gracia de 30 días.
`,
    },
    publicFaq: true,
  },
  {
    slug: "students",
    audience: "teacher",
    title: { en: `Manage students`, "es-MX": `Administra alumnos` },
    summary: {
      en: `Add students to your roster, invite them to use SpiralClass, keep private notes, and archive a student when lessons pause.`,
      "es-MX": `Agrega alumnos a tu lista, invítalos a usar SpiralClass, guarda notas privadas y archiva a un alumno cuando se pausen las clases.`,
    },
    body: {
      en: `## Purpose

Add students to your roster, invite them to use SpiralClass, keep private notes, and archive a student when lessons pause.

## Before you start

- You must be signed in as a teacher.
- For an invitation, use the student’s current email address.

## Steps

### Add one student

1. Open **Students**.
2. Select **Add student**.
3. Enter the requested details and save.

### Invite a student

1. Open the student’s profile.
2. Choose **Invite** or **Resend invitation**.
3. Ask the student to open the email and sign in with that same email address.

Invitation links are valid for 30 days.

### Add many students (web)

1. Open the bulk-invite screen.
2. Paste names and email addresses, one student per line.
3. Review invalid or duplicate entries.
4. Send invitations for the valid entries.

### Add a private note or archive a student

1. Open the student profile.
2. Use **Notes** to save a private note, or choose **Archive** to pause the roster entry.
3. Add a reason if useful and confirm.



## Tips

- Private notes are visible only to you.
- Archiving does not delete the student, their packages, past lessons, or their sign-in access. You can reactivate them later.
- Students added in bulk stay quiet until you choose to enable their notifications.

## Troubleshooting

**The invitation does not work.** The student must sign in with the exact email you invited. Resend the invitation if it expired.

**Why can’t I add a student?** Your plan may have reached its student limit. Check your plan or upgrade.

## Questions

**Can I change a student’s contact details?** Yes. Open their profile and save the change. A student can also update their own details.

**Does archiving cancel future lessons?** No. Review upcoming lessons separately before archiving.
`,
      "es-MX": `## Propósito

Agrega alumnos a tu lista, invítalos a usar SpiralClass, guarda notas privadas y archiva a un alumno cuando se pausen las clases.

## Antes de empezar

- Debes tener sesión iniciada como profesor.
- Para una invitación, usa el correo actual del alumno.

## Pasos

### Agregar un alumno

1. Abre **Alumnos**.
2. Selecciona **Agregar alumno**.
3. Ingresa los datos solicitados y guarda.

### Invitar a un alumno

1. Abre el perfil del alumno.
2. Elige **Invitar** o **Reenviar invitación**.
3. Pide al alumno que abra el correo e inicie sesión con ese mismo correo.

Los enlaces de invitación son válidos por 30 días.

### Agregar varios alumnos (web)

1. Abre la pantalla de invitación masiva.
2. Pega nombres y correos, un alumno por línea.
3. Revisa los registros inválidos o duplicados.
4. Envía las invitaciones para los registros válidos.

### Agregar una nota privada o archivar a un alumno

1. Abre el perfil del alumno.
2. Usa **Notas** para guardar una nota privada, o elige **Archivar** para pausar el registro.
3. Agrega un motivo si es útil y confirma.



## Consejos

- Las notas privadas solo son visibles para ti.
- Archivar no elimina al alumno, sus paquetes, sus clases pasadas ni su acceso de inicio de sesión. Puedes reactivarlo después.
- Los alumnos agregados de forma masiva no reciben notificaciones hasta que decidas activarlas.

## Solución de problemas

**La invitación no funciona.** El alumno debe iniciar sesión con el correo exacto al que invitaste. Reenvía la invitación si caducó.

**¿Por qué no puedo agregar un alumno?** Tu plan puede haber llegado a su límite de alumnos. Revisa tu plan o actualízalo.

## Preguntas

**¿Puedo cambiar los datos de contacto de un alumno?** Sí. Abre su perfil y guarda el cambio. El alumno también puede actualizar sus propios datos.

**¿Archivar cancela las clases futuras?** No. Revisa las clases próximas por separado antes de archivar.
`,
    },
  },
  {
    slug: "availability-and-booking",
    audience: "teacher",
    title: {
      en: `Set availability and manage classes`,
      "es-MX": `Configura tu disponibilidad y administra tus clases`,
    },
    summary: {
      en: `Choose when students can book you, block time off, and manage booked classes.`,
      "es-MX": `Elige cuándo pueden reservarte los alumnos, bloquea tiempo libre y administra las clases ya reservadas.`,
    },
    body: {
      en: `## Purpose

Choose when students can book you, block time off, and manage booked classes.

## Before you start

- You must have completed teacher setup.
- Set your timezone before adding working hours.

## Steps

### Change working hours

1. Open **Settings** and then **Availability**.
2. Add, edit, or remove your weekly time ranges.
3. Adjust buffer time, minimum notice, or booking window if needed.
4. Save.

### Block time off

1. Open **Settings** and then **Blocked dates**.
2. Tap a day on the calendar. Tap a second day to block everything in between, or block the one day on its own. You can also type the dates into the **From** and **To** fields.
3. Add a reason if you want one. A student whose class the block cancels is shown it.
4. Press **Block**.

Before you press it, the screen tells you how many classes are booked in the days you picked, and a dot under a date means a class is booked that day. If a block overlaps scheduled classes, those classes are cancelled, the class credit returns to the student, and the student is notified.

Removing a block later gives those days back and lets students book them again. It does not un-cancel the classes the block already cancelled.

### Book or cancel for a student

1. Open the student or class calendar.
2. Select an available time to book on the student’s behalf, or open a class and choose **Cancel**.
3. Give a reason when cancelling and confirm.

### Change the date or time of a class

1. Open the class and choose **Manage class → Change date and time**.
2. Pick a new day and time. Only times that fit your hours, blocks, buffer and existing classes are offered, and the class’s current time is not one of them.
3. Confirm. The class moves, your student is told the new time, and the change is recorded in the class history.



## Tips

- Blocked days are struck through on the calendar, so you can see what is already off before you pick.
- Students see only times that fit your working hours, blocks, buffers, and booking notice.
- You can book a student yourself even when your normal minimum notice would prevent a student from doing so.

## Troubleshooting

**I cannot save my hours.** Make sure time ranges do not overlap and that at least one range remains.

**A slot disappeared.** It may have been booked, blocked, or no longer meets the booking notice rules.

## Questions

**Can I connect Google Calendar?** Yes. In **Settings → Calendar**, connect your Google account. Busy events help prevent conflicting bookings.

**Can I cancel a completed or no-show class?** Yes. Choose Cancel and provide the required reason; the class credit is returned.

**Can I move a class that starts in less than 24 hours?** Yes. The 24-hour rule applies to your student, not to you — and moving a class does not use up any of the schedule changes included with the package.

**Can I move a class that has already happened?** No. A completed, cancelled or no-show class cannot be moved. Cancel it, or restore it first, then book the new time.
`,
      "es-MX": `## Propósito

Elige cuándo pueden reservarte los alumnos, bloquea tiempo libre y administra las clases ya reservadas.

## Antes de empezar

- Debes haber terminado la configuración de profesor.
- Configura tu zona horaria antes de agregar horarios de trabajo.

## Pasos

### Cambiar tus horarios de trabajo

1. Abre **Configuración** y luego **Disponibilidad**.
2. Agrega, edita o elimina tus rangos de horario semanales.
3. Ajusta el tiempo de descanso, el aviso mínimo o la ventana de reservación si lo necesitas.
4. Guarda.

### Bloquear una fecha

1. Abre **Configuración** y luego **Fechas bloqueadas**.
2. Toca un día en el calendario. Toca un segundo día para bloquear todo lo que hay entre ambos, o bloquea solo ese día. También puedes escribir las fechas en los campos **Desde** y **Hasta**.
3. Agrega un motivo si quieres. El alumno al que el bloqueo le cancele una clase lo verá.
4. Presiona **Bloquear**.

Antes de presionarlo, la pantalla te dice cuántas clases hay reservadas en los días que elegiste, y un punto debajo de una fecha significa que ese día hay una clase reservada. Si un bloqueo se traslapa con clases ya programadas, esas clases se cancelan, el crédito de la clase se devuelve al alumno y se le notifica.

Quitar un bloqueo después devuelve esos días y los alumnos pueden reservarlos otra vez. No revierte las clases que el bloqueo ya canceló.

### Reservar o cancelar una clase por un alumno

1. Abre el calendario del alumno o de la clase.
2. Selecciona un horario disponible para reservar en nombre del alumno, o abre una clase y elige **Cancelar**.
3. Indica un motivo al cancelar y confirma.

### Cambiar la fecha o la hora de una clase

1. Abre la clase y elige **Gestionar clase → Cambiar fecha y hora**.
2. Elige un día y un horario nuevos. Solo aparecen los horarios que respetan tus horas, bloqueos, descansos y clases ya reservadas, y el horario actual de la clase no es uno de ellos.
3. Confirma. La clase se mueve, tu alumno recibe aviso del nuevo horario y el cambio queda registrado en el historial de la clase.



## Consejos

- Los días bloqueados aparecen tachados en el calendario, así ves lo que ya está libre antes de elegir.
- Los alumnos solo ven los horarios que respetan tus horas de trabajo, bloqueos, descansos y aviso de reservación.
- Puedes reservar a un alumno tú mismo incluso cuando tu aviso mínimo normal le impediría reservar a él.

## Solución de problemas

**No puedo guardar mis horarios.** Asegúrate de que los rangos de horario no se traslapen y de que quede al menos un rango.

**Un horario desapareció.** Puede que ya se haya reservado, bloqueado, o que ya no cumpla con las reglas de aviso de reservación.

## Preguntas

**¿Puedo conectar Google Calendar?** Sí. En **Configuración → Calendario**, conecta tu cuenta de Google. Los eventos marcados como ocupado ayudan a evitar reservas en conflicto.

**¿Puedo cancelar una clase completada o una ausencia?** Sí. Elige Cancelar e indica el motivo requerido; el crédito de la clase se devuelve.

**¿Puedo mover una clase que empieza en menos de 24 horas?** Sí. La regla de 24 horas es para tu alumno, no para ti — y mover una clase no consume los cambios de horario incluidos en el paquete.

**¿Puedo mover una clase que ya ocurrió?** No. Una clase completada, cancelada o con ausencia no se puede mover. Cancélala, o restitúyela primero y luego reserva el horario nuevo.
`,
    },
    publicFaq: true,
  },
  {
    slug: "packages-and-payments",
    audience: "teacher",
    title: {
      en: `Create packages and manage payments`,
      "es-MX": `Crea paquetes y administra pagos`,
    },
    summary: {
      en: `Create lesson offers, record an existing package, and manage payments and refunds.`,
      "es-MX": `Crea ofertas de clases, registra un paquete ya existente y administra pagos y reembolsos.`,
    },
    body: {
      en: `## Purpose

Create lesson offers, record an existing package, and manage payments and refunds.

## Before you start

- You must be signed in as a teacher.
- Have the number of classes, lesson duration, price, and expiry period ready.

## Steps

### Create or edit an offer

1. Open **Settings → Templates**.
2. Add or edit an offer with a name, class count or single-class option, duration, price, and expiry period.
3. Save all changes.

Removing an existing offer archives it. It does not remove packages students already bought.

### Record a package you sold elsewhere

1. Open the student profile.
2. Choose **Add package**.
3. Enter total classes and classes remaining. Add price or expiry details if needed.
4. Save.

### Confirm a transfer or issue a card refund

1. Open the payment or package details.
2. For a bank transfer or Wise, confirm receipt only after the money has
   actually arrived in your account.
3. For an eligible card payment, choose **Refund**, add the reason, and confirm.



## What it costs you to get paid

Two different costs, from two different companies. Only the first is ours.

- **Your SpiralClass plan** — what you pay us for the software. That is the
  only money SpiralClass takes from you. We charge no commission on your lesson
  income, on any plan, including Free.
- **Stripe's processing fee** — what Stripe charges you for handling a payment
  made through Stripe. Your student pays you directly: the money goes into your
  own Stripe account, and Stripe takes its fee there before paying out to your
  bank. SpiralClass never holds that money and receives no part of that fee.
  Stripe sets the rate for your country and the method your student used, so
  check [Stripe's own pricing](https://stripe.com/pricing) for what applies to
  you. This covers **every** method Stripe offers at checkout — cards, and the
  local bank-transfer or cash options it may show your student. A bank transfer
  made inside Stripe checkout is still a Stripe payment and still carries the
  fee.
- **Wise** — your student transfers the money straight to your Wise account. It
  never passes through Stripe, so there is no Stripe fee at all. Wise or your
  own bank may still charge you for receiving money.

This is why a package can carry a lower Wise price than its Stripe price: you
keep more of a Wise transfer, so you can pass some of that on. Both prices are
yours to set, and neither is required.

Refunds and disputes are handled on your Stripe account too. Stripe's fee
policy on a refunded payment is Stripe's, not ours.

## Tips

- Set a clear expiry period. Unused classes cannot be booked after the package expires.
- Students see one combined available balance when more than one eligible package applies.
- A paid card package activates once the payment is confirmed. A transfer package activates when you confirm receipt.

## Troubleshooting

**A student cannot book.** Check that they have an active, unexpired package with a matching lesson duration.

**Why can’t I add another offer?** Free plans have a limit on active templates. Upgrade or archive an offer you no longer use.

## Questions

**Can I change a package after a student buys it?** Existing purchased packages retain their own details. Update the template for future purchases.

**What happens after a refund?** The student’s remaining credit from that payment is removed and both of you are notified.
`,
      "es-MX": `## Propósito

Crea ofertas de clases, registra un paquete ya existente y administra pagos y reembolsos.

## Antes de empezar

- Debes tener sesión iniciada como profesor.
- Ten a la mano el número de clases, la duración de la lección, el precio y el periodo de vigencia.

## Pasos

### Crear o editar una oferta

1. Abre **Configuración → Plantillas**.
2. Agrega o edita una oferta con un nombre, número de clases u opción de clase individual, duración, precio y periodo de vigencia.
3. Guarda todos los cambios.

Eliminar una oferta existente la archiva. No elimina los paquetes que los alumnos ya compraron.

### Registrar un paquete que vendiste por fuera

1. Abre el perfil del alumno.
2. Elige **Agregar paquete**.
3. Ingresa el total de clases y las clases restantes. Agrega el precio o la vigencia si lo necesitas.
4. Guarda.

### Confirmar una transferencia o emitir un reembolso con tarjeta

1. Abre los detalles del pago o del paquete.
2. Para una transferencia bancaria o Wise, confirma la recepción solo
   después de que el dinero haya llegado a tu cuenta.
3. Para un pago con tarjeta elegible, elige **Reembolsar**, agrega el motivo y confirma.



## Cuánto te cuesta cobrar

Son dos costos distintos, de dos empresas distintas. Solo el primero es nuestro.

- **Tu plan de SpiralClass** — lo que nos pagas por el software. Ese es el único
  dinero que SpiralClass te cobra. No nos quedamos con comisión sobre lo que
  ganas dando clases, en ningún plan, incluido el Gratis.
- **La comisión de Stripe** — lo que Stripe te cobra por procesar un pago hecho
  por Stripe. Tu alumno te paga directamente a ti: el dinero entra a tu propia
  cuenta de Stripe, y ahí Stripe cobra su comisión antes de depositarte en el
  banco. SpiralClass nunca retiene ese dinero ni recibe parte de esa comisión.
  Stripe fija la tarifa según tu país y el método que usó tu alumno, así que
  revisa [los precios de Stripe](https://stripe.com/pricing) para ver cuál te
  aplica. Esto cubre **todos** los métodos que Stripe ofrece al pagar — tarjetas
  y también las opciones locales de transferencia o pago en efectivo que le
  muestre a tu alumno. Una transferencia hecha dentro del checkout de Stripe
  sigue siendo un pago por Stripe y sigue llevando la comisión.
- **Wise** — tu alumno transfiere el dinero directo a tu cuenta de Wise. Nunca
  pasa por Stripe, así que no hay ninguna comisión de Stripe. Wise o tu banco sí
  podrían cobrarte por recibir el dinero.

Por eso un paquete puede tener un precio por Wise más bajo que su precio por
Stripe: te queda más de una transferencia por Wise, así que puedes pasarle parte
del ahorro a tu alumno. Los dos precios los defines tú, y ninguno es
obligatorio.

Los reembolsos y las disputas también se manejan en tu cuenta de Stripe. Lo que
Stripe haga con su comisión en un pago reembolsado es cosa de Stripe, no
nuestra.

## Consejos

- Define un periodo de vigencia claro. Las clases sin usar no se pueden reservar después de que el paquete vence.
- Los alumnos ven un solo saldo disponible combinado cuando aplica más de un paquete elegible.
- Un paquete pagado con tarjeta se activa en cuanto se confirma el pago. Un paquete pagado por transferencia se activa cuando confirmas la recepción.

## Solución de problemas

**Un alumno no puede reservar.** Verifica que tenga un paquete activo y vigente con una duración de lección que coincida.

**¿Por qué no puedo agregar otra oferta?** Los planes gratuitos tienen un límite de plantillas activas. Actualiza tu plan o archiva una oferta que ya no uses.

## Preguntas

**¿Puedo cambiar un paquete después de que un alumno lo compra?** Los paquetes ya comprados conservan sus propios detalles. Actualiza la plantilla para futuras compras.

**¿Qué pasa después de un reembolso?** Se elimina el crédito restante del alumno de ese pago y se les notifica a ambos.
`,
    },
    publicFaq: true,
  },
  {
    slug: "discounts-and-referrals",
    audience: "teacher",
    title: { en: `Offer discounts and referrals`, "es-MX": `Ofrece descuentos y referidos` },
    summary: {
      en: `Create a discount code for prospective students or run a referral programme that rewards current students for successful introductions.`,
      "es-MX": `Crea un código de descuento para posibles alumnos u opera un programa de referidos que premie a tus alumnos actuales por recomendaciones exitosas.`,
    },
    body: {
      en: `## Purpose

Create a discount code for prospective students or run a referral programme that rewards current students for successful introductions.

## Before you start

- You must be signed in as a teacher.
- Decide the discount or reward you can afford before publishing it.

## Steps

### Create a discount code

1. Open **Discounts**.
2. Choose **Create discount code**.
3. Set the code, percentage or fixed discount, and any expiry or redemption limits.
4. Save and share the code yourself.

Students enter a valid code when they pay for a package.

### Turn on referrals

1. Open **Referrals**.
2. Turn the programme on.
3. Set the friend’s discount, the referrer’s reward, and the reward expiry period.
4. Save.

Eligible students can then share their personal referral link or code. A reward is created only after the referred student’s first payment is confirmed.



## Tips

- Add an expiry or redemption limit to time-sensitive offers.
- Share codes through the channels you already use; SpiralClass does not send promotions on your behalf.
- Referral rewards are removed if the qualifying payment is refunded before the reward is used.

## Troubleshooting

**A discount does not apply.** Check its expiry, limits, and whether it is valid for that student and package.

**Why did a student not receive a referral reward?** The referred student’s payment must be a valid first purchase and must be confirmed first.

## Questions

**Can a student refer themselves?** No.

**Can I use a discount and a referral reward together?** The checkout screen applies the eligible offer according to the rules shown there.
`,
      "es-MX": `## Propósito

Crea un código de descuento para posibles alumnos u opera un programa de referidos que premie a tus alumnos actuales por recomendaciones exitosas.

## Antes de empezar

- Debes tener sesión iniciada como profesor.
- Decide el descuento o la recompensa que puedes ofrecer antes de publicarlo.

## Pasos

### Crear un código de descuento

1. Abre **Descuentos**.
2. Elige **Crear código de descuento**.
3. Define el código, el porcentaje o monto fijo de descuento, y cualquier límite de vigencia o de usos.
4. Guarda y comparte el código tú mismo.

Los alumnos ingresan un código válido cuando pagan un paquete.

### Activar referidos

1. Abre **Referidos**.
2. Activa el programa.
3. Define el descuento para el amigo, la recompensa para quien refiere y el periodo de vigencia de la recompensa.
4. Guarda.

Los alumnos elegibles pueden entonces compartir su enlace o código personal de referido. La recompensa se crea solo después de que se confirma el primer pago del alumno referido.



## Consejos

- Agrega una vigencia o límite de usos a las ofertas por tiempo limitado.
- Comparte los códigos por los canales que ya usas; SpiralClass no envía promociones en tu nombre.
- Las recompensas de referidos se eliminan si el pago que las originó se reembolsa antes de usarse.

## Solución de problemas

**Un descuento no se aplica.** Revisa su vigencia, sus límites y si es válido para ese alumno y ese paquete.

**¿Por qué un alumno no recibió una recompensa de referido?** El pago del alumno referido debe ser una primera compra válida y debe estar confirmado primero.

## Preguntas

**¿Un alumno puede referirse a sí mismo?** No.

**¿Puedo usar un descuento y una recompensa de referido juntos?** La pantalla de pago aplica la oferta elegible según las reglas que se muestran ahí.
`,
    },
  },
  {
    slug: "classes-materials-and-homework",
    audience: "teacher",
    title: {
      en: `Prepare classes, materials, and homework`,
      "es-MX": `Prepara clases, materiales y tareas`,
    },
    summary: {
      en: `Use class notes and learning materials to prepare a lesson, then assign and review homework.`,
      "es-MX": `Usa notas de clase y materiales de aprendizaje para preparar una lección, y luego asigna y revisa tareas.`,
    },
    body: {
      en: `## Purpose

Use class notes and learning materials to prepare a lesson, then assign and review homework.

## Before you start

- Open a student’s booked class.
- Some AI tools require Pro and may have a monthly limit.

## Steps

### Add notes and class content

1. Open the class detail page.
2. Add private teaching cues and, if needed, student-facing notes.
3. Open the class content or materials panel.
4. Write content, select an existing material, upload a file or link, or generate a draft if available.
5. Review, edit, and save.

Students can always view saved class content. They see student-facing notes only shortly before and after the lesson.

### Build your materials library

1. Open **Materials**.
2. Choose **Add material**.
3. Write, generate, upload, or add a link; select a level and save.
4. Attach a library item to a class or assign it from a student profile.

### Assign and review homework

1. Open a class and choose **Homework → Add**.
2. Add a title, instructions, due date, and submission options; save.
3. When a student submits work, open **Review**.
4. Add feedback and an optional score, then choose **Approve**, **Request resubmission**, or **Reject**.



## Tips

- Keep private cues separate from student-facing instructions.
- Saving material with a homework or exercise block may create a homework draft; delete it if you do not want to assign it.
- A review decision cannot be changed afterward, so check your feedback first.

## Troubleshooting

**The student cannot see homework.** Confirm the assignment was saved on the correct class.

**AI generation is unavailable.** Check your Pro access and monthly allowance, then try again later if you reached the limit.

## Questions

**Can a student submit homework on the web?** Yes. They open the assignment from their class page and submit there.

**Can I attach more than one library item?** Yes, you can choose multiple existing items for a class.
`,
      "es-MX": `## Propósito

Usa notas de clase y materiales de aprendizaje para preparar una lección, y luego asigna y revisa tareas.

## Antes de empezar

- Abre una clase reservada de un alumno.
- Algunas herramientas de IA requieren Pro y pueden tener un límite mensual.

## Pasos

### Agregar notas y contenido de clase

1. Abre la página de detalle de la clase.
2. Agrega pistas privadas de enseñanza y, si es necesario, notas visibles para el alumno.
3. Abre el panel de contenido de clase o materiales.
4. Escribe contenido, selecciona un material existente, sube un archivo o enlace, o genera un borrador si está disponible.
5. Revisa, edita y guarda.

Los alumnos siempre pueden ver el contenido de clase guardado. Solo ven las notas visibles para ellos poco antes y después de la lección.

### Construir tu biblioteca de materiales

1. Abre **Materiales**.
2. Elige **Agregar material**.
3. Escribe, genera, sube o agrega un enlace; selecciona un nivel y guarda.
4. Adjunta un elemento de la biblioteca a una clase o asígnalo desde el perfil de un alumno.

### Asignar y revisar tareas

1. Abre una clase y elige **Tareas → Agregar**.
2. Agrega un título, instrucciones, fecha límite y opciones de entrega; guarda.
3. Cuando un alumno entrega su trabajo, abre **Revisar**.
4. Agrega comentarios y una calificación opcional, y luego elige **Aprobar**, **Solicitar reenvío** o **Rechazar**.



## Consejos

- Mantén las pistas privadas separadas de las instrucciones visibles para el alumno.
- Guardar un material con un bloque de tarea o ejercicio puede crear un borrador de tarea; elimínalo si no quieres asignarlo.
- Una decisión de revisión no se puede cambiar después, así que revisa tus comentarios antes.

## Solución de problemas

**El alumno no puede ver la tarea.** Confirma que la asignación se guardó en la clase correcta.

**La generación con IA no está disponible.** Revisa tu acceso a Pro y tu límite mensual; si llegaste al límite, intenta más tarde.

## Preguntas

**¿Un alumno puede entregar tareas desde la web?** Sí. Abre la tarea desde la página de su clase y la entrega ahí.

**¿Puedo adjuntar más de un elemento de la biblioteca?** Sí, puedes elegir varios elementos existentes para una clase.
`,
    },
  },
  {
    slug: "live-calls",
    audience: "teacher",
    title: { en: `Join live calls`, "es-MX": `Únete a videollamadas en vivo` },
    summary: {
      en: `Join a scheduled lesson, control your camera and microphone, share your screen, and use supported teaching tools during a call.`,
      "es-MX": `Únete a una lección programada, controla tu cámara y micrófono, comparte tu pantalla y usa las herramientas de enseñanza disponibles durante una llamada.`,
    },
    body: {
      en: `## Purpose

Join a scheduled lesson, control your camera and microphone, share your screen, and use supported teaching tools during a call.

## Before you start

- Open an upcoming scheduled class near its start time.
- Allow camera and microphone access when your device asks.
- Use a reliable internet connection and headphones when possible.

## Steps

1. Open the upcoming class from your dashboard or class list.
2. Select **Join call** when it appears.
3. Check your camera and microphone.
4. Use the call controls to mute, turn your camera on or off, share your screen, or nudge the student.
5. Minimize the call if you need to view another part of SpiralClass; the call stays active.
6. Leave the call when the lesson ends.



## Tips

- Only one person can share a screen at a time.
- On mobile, screen sharing is available on Android; it is not available on iPhone or iPad.
- Recording and live captions appear only when they are enabled for your account and class.

Suggested video: **“Join and Run a Live Lesson (2 minutes)”**

## Troubleshooting

**I cannot join.** Refresh the class page, check your connection, and allow camera and microphone permissions.

**The student has not joined.** Use the nudge control if it is available, then wait for them to join.

## Questions

**Can I record a lesson?** If recording is available to you, start and stop it from the call controls. A recording indicator is shown while it runs.

**Can I keep the call open while checking messages?** Yes. Minimize it instead of leaving.
`,
      "es-MX": `## Propósito

Únete a una lección programada, controla tu cámara y micrófono, comparte tu pantalla y usa las herramientas de enseñanza disponibles durante una llamada.

## Antes de empezar

- Abre una clase próxima programada cerca de su hora de inicio.
- Permite el acceso a la cámara y al micrófono cuando tu dispositivo lo pida.
- Usa una conexión a internet confiable y audífonos si es posible.

## Pasos

1. Abre la clase próxima desde tu panel o tu lista de clases.
2. Selecciona **Unirse a la llamada** cuando aparezca.
3. Revisa tu cámara y micrófono.
4. Usa los controles de llamada para silenciarte, activar o desactivar tu cámara, compartir pantalla o avisar al alumno.
5. Minimiza la llamada si necesitas ver otra parte de SpiralClass; la llamada sigue activa.
6. Sal de la llamada cuando termine la lección.



## Consejos

- Solo una persona puede compartir pantalla a la vez.
- En dispositivos móviles, compartir pantalla está disponible en Android; no está disponible en iPhone ni iPad.
- La grabación y los subtítulos en vivo aparecen solo cuando están habilitados para tu cuenta y tu clase.

Video sugerido: **"Únete y da una lección en vivo (2 minutos)"**

## Solución de problemas

**No puedo unirme.** Actualiza la página de la clase, revisa tu conexión y permite los permisos de cámara y micrófono.

**El alumno no se ha unido.** Usa el control para avisarle si está disponible, y luego espera a que se una.

## Preguntas

**¿Puedo grabar una lección?** Si tienes disponible la grabación, actívala y desactívala desde los controles de llamada. Se muestra un indicador de grabación mientras está activa.

**¿Puedo mantener la llamada abierta mientras reviso mensajes?** Sí. Minimízala en vez de salir.
`,
    },
  },
  {
    slug: "messages-and-notifications",
    audience: "teacher",
    title: { en: `Messages and notifications`, "es-MX": `Mensajes y notificaciones` },
    summary: {
      en: `Talk with your students and choose how SpiralClass keeps you informed.`,
      "es-MX": `Habla con tus alumnos y elige cómo te mantiene informado SpiralClass.`,
    },
    body: {
      en: `## Purpose

Talk with your students and choose how SpiralClass keeps you informed.

## Before you start

- You must be signed in as a teacher.
- You can message eligible students in your roster.

## Steps

### Send a message

1. Open **Messages**.
2. Open an existing conversation or select an eligible student.
3. Write a message or attach a voice note, video, image, or file.
4. Send.

To edit a text-only message, choose Edit within 15 minutes. To delete a message for everyone, choose Delete within about two and a half days.

### Change notifications

1. Open **Settings → Notifications**.
2. Turn categories or email/push delivery on or off.
3. Save your changes.
4. To silence one student’s general notifications, open that student’s profile and adjust their notification setting.



## Tips

- Open a conversation to mark its messages as read.
- Important payment, billing, and sign-in messages cannot be switched off.
- If push is unavailable, SpiralClass may send an email instead.

## Troubleshooting

**I cannot edit a message.** Only text-only messages can be edited, and only during the 15-minute editing period.

**I am not getting notifications.** Check your notification settings and your phone’s permission for SpiralClass notifications.

## Questions

**Can I undo a deletion?** No. Deleted messages cannot be restored.

**Will the student know I read a message?** Opening the conversation updates the read state.
`,
      "es-MX": `## Propósito

Habla con tus alumnos y elige cómo te mantiene informado SpiralClass.

## Antes de empezar

- Debes tener sesión iniciada como profesor.
- Puedes enviar mensajes a los alumnos elegibles de tu lista.

## Pasos

### Enviar un mensaje

1. Abre **Mensajes**.
2. Abre una conversación existente o selecciona un alumno elegible.
3. Escribe un mensaje o adjunta una nota de voz, video, imagen o archivo.
4. Envía.

Para editar un mensaje de solo texto, elige Editar dentro de los primeros 15 minutos. Para eliminar un mensaje para todos, elige Eliminar dentro de aproximadamente dos días y medio.

### Cambiar notificaciones

1. Abre **Configuración → Notificaciones**.
2. Activa o desactiva categorías o la entrega por correo/push.
3. Guarda tus cambios.
4. Para silenciar las notificaciones generales de un alumno en particular, abre su perfil y ajusta su configuración de notificaciones.



## Consejos

- Abre una conversación para marcar sus mensajes como leídos.
- Los mensajes importantes de pago, facturación e inicio de sesión no se pueden desactivar.
- Si push no está disponible, SpiralClass puede enviar un correo en su lugar.

## Solución de problemas

**No puedo editar un mensaje.** Solo se pueden editar los mensajes de solo texto, y únicamente durante el periodo de edición de 15 minutos.

**No estoy recibiendo notificaciones.** Revisa tu configuración de notificaciones y el permiso de notificaciones de SpiralClass en tu teléfono.

## Preguntas

**¿Puedo deshacer una eliminación?** No. Los mensajes eliminados no se pueden restaurar.

**¿El alumno sabrá que leí un mensaje?** Abrir la conversación actualiza el estado de leído.
`,
    },
  },
  {
    slug: "student-progress-reports",
    audience: "teacher",
    title: { en: `Student progress reports`, "es-MX": `Informes de progreso del alumno` },
    summary: {
      en: `Review learning insights from lessons, prepare for the next class, and choose whether a student can see a simplified progress view.`,
      "es-MX": `Revisa hallazgos de aprendizaje de las lecciones, prepárate para la siguiente clase y elige si un alumno puede ver una vista simplificada de su progreso.`,
    },
    body: {
      en: `## Purpose

Review learning insights from lessons, prepare for the next class, and choose whether a student can see a simplified progress view.

## Before you start

- Open a student profile or a completed class.
- Progress insights depend on the relevant learning features being available and on the student’s consent where requested.

## Steps

1. Open a student profile to view their focus areas and vocabulary progress.
2. Use the consent controls before enabling eligible learning insights. For a minor, complete the additional consent step.
3. Choose whether to **Share progress with student**.
4. Before a class, open the preparation card and add helpful cues to your lesson notes.
5. After an analyzed class, review each finding. Choose **Confirm**, **Edit**, or **Dismiss**, or add your own finding.



## Tips

- Student-facing progress is simplified; students do not see your detailed evidence or internal lesson findings.
- Treat suggestions as teaching support. Review them before relying on them in a lesson.

## Troubleshooting

**I cannot see insights.** The class may not yet be ready, the feature may not be available, or the required consent may be missing.

**The student cannot see progress.** Turn on **Share progress with student** from their profile.

## Questions

**Can I change a finding?** You can edit or dismiss a suggested finding before confirming it.

**What does the student see?** They see encouraging progress groupings and, where available, vocabulary review cards.
`,
      "es-MX": `## Propósito

Revisa hallazgos de aprendizaje de las lecciones, prepárate para la siguiente clase y elige si un alumno puede ver una vista simplificada de su progreso.

## Antes de empezar

- Abre el perfil de un alumno o una clase completada.
- Los hallazgos de progreso dependen de que las funciones de aprendizaje correspondientes estén disponibles y, cuando se requiera, del consentimiento del alumno.

## Pasos

1. Abre el perfil de un alumno para ver sus áreas de enfoque y su progreso de vocabulario.
2. Usa los controles de consentimiento antes de activar los hallazgos de aprendizaje elegibles. Para un menor de edad, completa el paso adicional de consentimiento.
3. Elige si **Compartir progreso con el alumno**.
4. Antes de una clase, abre la tarjeta de preparación y agrega pistas útiles a tus notas de lección.
5. Después de una clase analizada, revisa cada hallazgo. Elige **Confirmar**, **Editar** o **Descartar**, o agrega tu propio hallazgo.



## Consejos

- El progreso visible para el alumno está simplificado; los alumnos no ven tu evidencia detallada ni tus hallazgos internos de la lección.
- Trata las sugerencias como apoyo de enseñanza. Revísalas antes de basarte en ellas durante una lección.

## Solución de problemas

**No puedo ver hallazgos.** Puede que la clase aún no esté lista, que la función no esté disponible, o que falte el consentimiento requerido.

**El alumno no puede ver su progreso.** Activa **Compartir progreso con el alumno** desde su perfil.

## Preguntas

**¿Puedo cambiar un hallazgo?** Puedes editar o descartar un hallazgo sugerido antes de confirmarlo.

**¿Qué ve el alumno?** Ve agrupaciones de progreso alentadoras y, cuando esté disponible, tarjetas de repaso de vocabulario.
`,
    },
  },
  {
    slug: "faq",
    audience: "teacher",
    title: {
      en: `Teacher frequently asked questions`,
      "es-MX": `Preguntas frecuentes para profesores`,
    },
    summary: {
      en: `Find quick answers to common questions about using SpiralClass as a teacher.`,
      "es-MX": `Encuentra respuestas rápidas a preguntas comunes sobre cómo usar SpiralClass como profesor.`,
    },
    body: {
      en: `## Purpose

Find quick answers to common questions about using SpiralClass as a teacher.

## Before you start

- Sign in to your teacher account.
- Open the linked guide when an answer needs more detail.

## Questions

### Getting started

**How do students find me?** Share your public booking page after you finish onboarding.

**Can I use SpiralClass before paying for Pro?** Yes. New teachers start with a 30-day Pro trial, then move to Free unless they subscribe.

### Students and classes

**Does archiving remove a student?** No. It pauses that roster entry and can be reversed.

**What happens when I block dates with existing classes?** The affected classes are cancelled and the student receives their class credit back.

**Can I book a class for a student?** Yes, from your dashboard or calendar.

### Packages and payments

**When does a package expire?** On the expiry date set for that package. Remaining classes cannot be booked afterward.

**Can I record a payment received outside SpiralClass?** Yes. Add an active package from the student profile.

**Does SpiralClass take a cut of what my students pay me?** No. Your students pay you directly and we take no commission on any plan. Your plan is the only money we charge you.

**So why is a payment slightly less than the price I set?** Because Stripe charges its own processing fee for handling it, on your own Stripe account. That fee is Stripe's — SpiralClass receives no part of it — and Stripe sets the rate for your country and the method your student used. See [Stripe's pricing](https://stripe.com/pricing), or [Create packages and manage payments](packages-and-payments.md) for the full picture.

**Is there a way to avoid the Stripe fee?** Take payment through Wise instead — your student transfers straight to your Wise account, so the money never passes through Stripe and carries no Stripe fee. Your own bank or Wise may still charge you for receiving money. Note that a bank transfer offered _inside_ Stripe checkout is still a Stripe payment and still carries the fee.

### Teaching tools

**Who can see my lesson notes?** Students see only the student-facing notes during the class window. Your private cues remain private.

**Can students submit homework on the web?** Yes. They open the assignment from the class page, write their answer, attach any files and submit.

## Still need help?

Check the relevant guide in the [Teacher Help Centre](index.md), then contact your usual SpiralClass support channel if the issue continues.

## Tips

- Check your timezone, package balance, and class time before changing a booking.
- Keep student contact details current so invitations and notices arrive correctly.

## Troubleshooting

If something on screen differs from these answers, do not repeat a payment or booking. Take a screenshot and contact support.
`,
      "es-MX": `## Propósito

Encuentra respuestas rápidas a preguntas comunes sobre cómo usar SpiralClass como profesor.

## Antes de empezar

- Inicia sesión en tu cuenta de profesor.
- Abre la guía enlazada cuando una respuesta necesite más detalle.

## Preguntas

### Primeros pasos

**¿Cómo me encuentran los alumnos?** Comparte tu página pública de reservas en cuanto termines la configuración.

**¿Puedo usar SpiralClass antes de pagar Pro?** Sí. Los nuevos profesores comienzan con una prueba gratuita de Pro de 30 días, y luego pasan a Free a menos que se suscriban.

### Alumnos y clases

**¿Archivar elimina a un alumno?** No. Pausa ese registro de la lista y se puede revertir.

**¿Qué pasa cuando bloqueo fechas con clases existentes?** Las clases afectadas se cancelan y el alumno recibe de vuelta su crédito de clase.

**¿Puedo reservar una clase por un alumno?** Sí, desde tu panel o tu calendario.

### Paquetes y pagos

**¿Cuándo vence un paquete?** En la fecha de vencimiento establecida para ese paquete. Las clases restantes ya no se pueden reservar después.

**¿Puedo registrar un pago recibido fuera de SpiralClass?** Sí. Agrega un paquete activo desde el perfil del alumno.

**¿SpiralClass se queda con una parte de lo que me pagan mis alumnos?** No. Tus alumnos te pagan directamente a ti y no cobramos comisión en ningún plan. Tu plan es lo único que te cobramos.

**¿Entonces por qué un pago llega un poco por debajo del precio que puse?** Porque Stripe cobra su propia comisión por procesarlo, en tu propia cuenta de Stripe. Esa comisión es de Stripe — SpiralClass no recibe ninguna parte — y Stripe fija la tarifa según tu país y el método que usó tu alumno. Consulta [los precios de Stripe](https://stripe.com/pricing), o [Crea paquetes y administra pagos](packages-and-payments.md) para el panorama completo.

**¿Hay forma de evitar la comisión de Stripe?** Cobra por Wise — tu alumno transfiere directo a tu cuenta de Wise, así que el dinero nunca pasa por Stripe y no lleva comisión de Stripe. Tu banco o Wise sí podrían cobrarte por recibir el dinero. Ojo: una transferencia ofrecida _dentro_ del checkout de Stripe sigue siendo un pago por Stripe y sigue llevando la comisión.

### Herramientas de enseñanza

**¿Quién puede ver mis notas de lección?** Los alumnos solo ven las notas visibles para ellos durante la ventana de la clase. Tus pistas privadas permanecen privadas.

**¿Los alumnos pueden entregar tareas desde la web?** Sí. Abren la tarea desde la página de la clase, escriben su respuesta, adjuntan archivos y la entregan.

## ¿Sigues necesitando ayuda?

Consulta la guía correspondiente en el [Centro de ayuda para profesores](index.es-MX.md) y luego contacta tu canal habitual de soporte de SpiralClass si el problema continúa.

## Consejos

- Revisa tu zona horaria, el saldo de tu paquete y la hora de la clase antes de cambiar una reserva.
- Mantén actualizados los datos de contacto de tus alumnos para que las invitaciones y avisos lleguen correctamente.

## Solución de problemas

Si algo en pantalla difiere de estas respuestas, no repitas un pago o una reserva. Toma una captura de pantalla y contacta a soporte.
`,
    },
  },
  {
    slug: "getting-started",
    audience: "student",
    title: { en: `Sign in and get started`, "es-MX": `Inicia sesión y comienza` },
    summary: {
      en: `Access your lessons, materials, packages, and messages.`,
      "es-MX": `Accede a tus lecciones, materiales, paquetes y mensajes.`,
    },
    body: {
      en: `## Purpose

Access your lessons, materials, packages, and messages.

## Before you start

- Use the email address your teacher invited or the email used when you bought a package.
- Have access to that email inbox.

## Steps

1. Open **Sign in**.
2. Enter your email address.
3. Enter the six-digit code sent to your email.
4. Open **My classes** to see your lessons, or use the student tabs.

You can also choose **Sign in with Google** where it is offered.



## Tips

- Codes expire after five minutes, so enter them promptly.
- If your teacher invited you, sign in with the same email used for the invitation.
- After buying a package from a teacher’s booking page, use the email from checkout to sign in later.

Suggested video: **“Your First Steps as a Student (1 minute)”**

## Troubleshooting

**I did not receive a code.** Check spam or junk mail, then request a new code.

**My invitation does not connect to my lessons.** Make sure you signed in with the exact invited email address.

## Questions

**Do I need a password?** No. SpiralClass signs you in with an email code or, where available, Google.
`,
      "es-MX": `## Propósito

Accede a tus lecciones, materiales, paquetes y mensajes.

## Antes de empezar

- Usa el correo al que tu profesor te invitó o el correo que usaste al comprar un paquete.
- Ten acceso a esa bandeja de entrada.

## Pasos

1. Abre **Iniciar sesión**.
2. Ingresa tu correo electrónico.
3. Ingresa el código de seis dígitos que recibiste por correo.
4. Abre **Mis clases** para ver tus lecciones, o usa las pestañas de alumno.

También puedes elegir **Iniciar sesión con Google** donde esté disponible.



## Consejos

- Los códigos caducan a los cinco minutos, así que ingrésalos pronto.
- Si tu profesor te invitó, inicia sesión con el mismo correo de la invitación.
- Después de comprar un paquete desde la página de reservas de un profesor, usa el correo del pago para iniciar sesión más adelante.

Video sugerido: **"Tus primeros pasos como alumno (1 minuto)"**

## Solución de problemas

**No recibí un código.** Revisa spam o correo no deseado y pide un código nuevo.

**Mi invitación no se conecta con mis lecciones.** Asegúrate de haber iniciado sesión con el correo exacto al que te invitaron.

## Preguntas

**¿Necesito una contraseña?** No. SpiralClass te da acceso con un código por correo o, donde esté disponible, con Google.
`,
    },
  },
  {
    slug: "account-settings",
    audience: "student",
    title: { en: `Manage your account`, "es-MX": `Administra tu cuenta` },
    summary: {
      en: `Update your details, change your sign-in email, control notifications, request your data, or request account deletion.`,
      "es-MX": `Actualiza tus datos, cambia tu correo de inicio de sesión, controla tus notificaciones, solicita tus datos o solicita la eliminación de tu cuenta.`,
    },
    body: {
      en: `## Purpose

Update your details, change your sign-in email, control notifications, request your data, or request account deletion.

## Before you start

- You must be signed in.
- Keep access to your email if you plan to change your sign-in address.

## Steps

### Update your details

1. Open **Account** or **Settings**.
2. Edit your name, phone number, timezone, or available profile details.
3. Save.

### Change your sign-in email

1. Open the email-change option.
2. Enter your new email address.
3. Enter the verification code sent to that new address.
4. Confirm the change.

### Request data or account deletion

1. Open the data or account section of settings.
2. Choose **Export my data** to download your information.
3. Choose **Delete account** and confirm if you want to request deletion.
4. Return to this screen to cancel a pending deletion request during the grace period.



## Tips

- Update your timezone before booking lessons while travelling.
- Keep your email current so you can receive sign-in codes and lesson notices.
- Account deletion has a 30-day grace period.

## Troubleshooting

**I cannot change my email.** Check that you entered the code sent to the new address before it expired.

**I cannot request deletion.** Deletion is blocked while you have unused paid classes. Book, use, or resolve them first.

## Questions

**Will deleting my account happen immediately?** No. You have 30 days to cancel the request.

**Can I change notification preferences?** Yes. Open **Notifications** in account settings.
`,
      "es-MX": `## Propósito

Actualiza tus datos, cambia tu correo de inicio de sesión, controla tus notificaciones, solicita tus datos o solicita la eliminación de tu cuenta.

## Antes de empezar

- Debes tener sesión iniciada.
- Conserva acceso a tu correo si planeas cambiar tu dirección de inicio de sesión.

## Pasos

### Actualizar tus datos

1. Abre **Cuenta** o **Configuración**.
2. Edita tu nombre, teléfono, zona horaria u otros datos de perfil disponibles.
3. Guarda.

### Cambiar tu correo de inicio de sesión

1. Abre la opción de cambio de correo.
2. Ingresa tu nuevo correo electrónico.
3. Ingresa el código de verificación enviado a esa nueva dirección.
4. Confirma el cambio.

### Solicitar tus datos o la eliminación de tu cuenta

1. Abre la sección de datos o de cuenta en configuración.
2. Elige **Exportar mis datos** para descargar tu información.
3. Elige **Eliminar cuenta** y confirma si quieres solicitar la eliminación.
4. Regresa a esta pantalla para cancelar una solicitud de eliminación pendiente durante el periodo de gracia.



## Consejos

- Actualiza tu zona horaria antes de reservar lecciones mientras viajas.
- Mantén tu correo actualizado para recibir códigos de inicio de sesión y avisos de lecciones.
- La eliminación de cuenta tiene un periodo de gracia de 30 días.

## Solución de problemas

**No puedo cambiar mi correo.** Verifica que ingresaste el código enviado a la nueva dirección antes de que caducara.

**No puedo solicitar la eliminación.** La eliminación se bloquea mientras tengas clases pagadas sin usar. Resérvalas, úsalas o resuélvelas primero.

## Preguntas

**¿Se eliminará mi cuenta de inmediato?** No. Tienes 30 días para cancelar la solicitud.

**¿Puedo cambiar mis preferencias de notificación?** Sí. Abre **Notificaciones** en la configuración de tu cuenta.
`,
    },
  },
  {
    slug: "buying-packages-and-payments",
    audience: "student",
    title: { en: `Buy packages and pay`, "es-MX": `Compra paquetes y paga` },
    summary: {
      en: `Buy lesson packages from your teacher and understand when they are ready to use.`,
      "es-MX": `Compra paquetes de lecciones con tu profesor y entiende cuándo quedan listos para usarse.`,
    },
    body: {
      en: `## Purpose

Buy lesson packages from your teacher and understand when they are ready to use.

## Before you start

- Open your teacher’s booking page or sign in to buy again.
- Choose the package that matches the lesson length you want.

## Steps

### Pay by card

1. Choose a package.
2. Add a valid discount code if you have one.
3. Select card payment and complete the payment screen.
4. Wait for the confirmation. Your package becomes ready once payment is confirmed.

### Pay by bank transfer

Your teacher may offer a transfer instead of, or alongside, card payment —
Wise, or a bank account in her own country (SPEI in Mexico, PIX in Brazil,
and so on).

1. Choose the transfer option shown at checkout.
2. Wise gives you a payment link. A bank account gives you the account
   details to enter in your own banking app — check the bank name shown
   matches the one your app displays before you send.
3. Use the payment reference exactly as shown. It is how your teacher
   identifies your payment.
4. Send the transfer.
5. Select **I already sent it** if shown.
6. Wait for your teacher to confirm receipt. The package then becomes ready.



## Tips

- Keep the payment reference exactly as shown for a transfer. It is the only
  thing tying your payment to your package.
- A discount must be valid before checkout to reduce the price.
- Check the package expiry date. Unused classes cannot be booked after it expires.

## Troubleshooting

**My package is not active yet.** Card payments need confirmation. Transfers need your teacher to confirm receipt, which can take longer.

**My discount code does not work.** It may be expired, used up, unavailable for this package, or not valid for your account.

## Questions

**Can I buy without an account?** Yes. You can buy from a teacher’s public booking page, then sign in later using the email from checkout.

**What happens after a refund?** The payment is refunded and any remaining classes from that package are removed. We email you when it is issued, and the money goes back to the same payment method you paid with — usually within 5 to 10 business days, depending on your bank.
`,
      "es-MX": `## Propósito

Compra paquetes de lecciones con tu profesor y entiende cuándo quedan listos para usarse.

## Antes de empezar

- Abre la página de reservas de tu profesor o inicia sesión para comprar de nuevo.
- Elige el paquete que coincida con la duración de lección que quieres.

## Pasos

### Pagar con tarjeta

1. Elige un paquete.
2. Agrega un código de descuento válido si tienes uno.
3. Selecciona pago con tarjeta y completa la pantalla de pago.
4. Espera la confirmación. Tu paquete queda listo en cuanto se confirma el pago.

### Pagar por transferencia

Tu profesor puede ofrecer transferencia además de, o en lugar de, pago con
tarjeta: Wise, o una cuenta bancaria en su propio país (SPEI en México, PIX
en Brasil, etc.).

1. Elige la opción de transferencia que aparece al pagar.
2. Wise te da un enlace de pago. Una cuenta bancaria te da los datos para
   capturarlos en tu app del banco — verifica que el banco que se muestra
   coincida con el que ves en tu app antes de enviar.
3. Usa la referencia de pago exactamente como se muestra. Así identifica tu
   profesor tu pago.
4. Envía la transferencia.
5. Selecciona **Ya lo envié** si aparece la opción.
6. Espera a que tu profesor confirme la recepción. El paquete queda listo
   entonces.



## Consejos

- Conserva la referencia de pago exactamente como se muestra. Es lo único que
  liga tu pago con tu paquete.
- Un descuento debe ser válido antes del pago para reducir el precio.
- Revisa la fecha de vencimiento del paquete. Las clases sin usar no se pueden reservar después de que vence.

## Solución de problemas

**Mi paquete todavía no está activo.** Los pagos con tarjeta necesitan confirmación. Las transferencias necesitan que tu profesor confirme la recepción, lo cual puede tardar más.

**Mi código de descuento no funciona.** Puede estar vencido, agotado, no disponible para este paquete, o no válido para tu cuenta.

## Preguntas

**¿Puedo comprar sin tener una cuenta?** Sí. Puedes comprar desde la página pública de reservas de un profesor y luego iniciar sesión más tarde usando el correo del pago.

**¿Qué pasa después de un reembolso?** El pago se reembolsa y se eliminan las clases restantes de ese paquete. Te avisamos por correo cuando se emite, y el dinero regresa al mismo método de pago que usaste, normalmente en 5 a 10 días hábiles según tu banco.
`,
    },
  },
  {
    slug: "booking-and-managing-lessons",
    audience: "student",
    title: {
      en: `Book, cancel, or move a lesson`,
      "es-MX": `Reserva, cancela o cambia una lección`,
    },
    summary: {
      en: `Choose a lesson time and manage changes to booked lessons.`,
      "es-MX": `Elige un horario de lección y administra los cambios a las lecciones ya reservadas.`,
    },
    body: {
      en: `## Purpose

Choose a lesson time and manage changes to booked lessons.

## Before you start

- You must be signed in.
- You need an active, unexpired package with an available class for the lesson length.

## Steps

### Book a lesson

1. Open **Book** or **My classes**.
2. Choose an available day and time.
3. Confirm the lesson.
4. Check the confirmation screen and your upcoming classes.

### Cancel a lesson

1. Open the lesson in **My classes**.
2. Choose **Cancel** and confirm.
3. Read the result shown on screen.

### Move a lesson

1. Open the lesson and choose **Reschedule**.
2. Choose a new available time.
3. Confirm the change.



## Tips

- Check the date, time, and timezone before confirming.
- Your teacher’s calendar already accounts for their working hours and time off.
- Use the next-available option when you need the earliest open time.

## Troubleshooting

**I cannot book.** Your package may be used up or expired, the slot may no longer be available, or the slot may be too soon under your teacher’s booking rules.

**I cannot reschedule.** Changes depend on the lesson timing and the remaining change allowance for your package. Choose Cancel if the app offers that option, or contact your teacher.

## Questions

**What happens if I cancel less than 24 hours before a lesson?** The app tells you the result before it completes the cancellation. Your teacher’s class-change rules apply.

**Why did an available slot disappear?** Another booking, a calendar change, or an updated availability rule may have made it unavailable.
`,
      "es-MX": `## Propósito

Elige un horario de lección y administra los cambios a las lecciones ya reservadas.

## Antes de empezar

- Debes tener sesión iniciada.
- Necesitas un paquete activo y vigente con una clase disponible para esa duración de lección.

## Pasos

### Reservar una lección

1. Abre **Reservar** o **Mis clases**.
2. Elige un día y horario disponible.
3. Confirma la lección.
4. Revisa la pantalla de confirmación y tus próximas clases.

### Cancelar una lección

1. Abre la lección en **Mis clases**.
2. Elige **Cancelar** y confirma.
3. Lee el resultado que se muestra en pantalla.

### Cambiar una lección

1. Abre la lección y elige **Reprogramar**.
2. Elige un nuevo horario disponible.
3. Confirma el cambio.



## Consejos

- Revisa la fecha, hora y zona horaria antes de confirmar.
- El calendario de tu profesor ya toma en cuenta su horario de trabajo y sus días libres.
- Usa la opción de próximo horario disponible cuando necesites el espacio más cercano.

## Solución de problemas

**No puedo reservar.** Tu paquete puede estar agotado o vencido, el horario ya no está disponible, o el horario es demasiado próximo según las reglas de reserva de tu profesor.

**No puedo reprogramar.** Los cambios dependen del tiempo de la lección y del margen de cambios restante de tu paquete. Elige Cancelar si la app ofrece esa opción, o contacta a tu profesor.

## Preguntas

**¿Qué pasa si cancelo con menos de 24 horas de anticipación?** La app te indica el resultado antes de completar la cancelación. Aplican las reglas de cambio de clase de tu profesor.

**¿Por qué desapareció un horario disponible?** Otra reserva, un cambio de calendario o una regla de disponibilidad actualizada pueden haberlo dejado no disponible.
`,
    },
  },
  {
    slug: "live-lessons",
    audience: "student",
    title: { en: `Join a live lesson`, "es-MX": `Únete a una lección en vivo` },
    summary: {
      en: `Join your scheduled lesson and use the camera, microphone, and other call controls.`,
      "es-MX": `Únete a tu lección programada y usa la cámara, el micrófono y otros controles de llamada.`,
    },
    body: {
      en: `## Purpose

Join your scheduled lesson and use the camera, microphone, and other call controls.

## Before you start

- Open an upcoming lesson close to its start time.
- Allow camera and microphone access when asked.
- Use a reliable internet connection and headphones when possible.

## Steps

1. Open the upcoming class in **My classes**.
2. Select **Join call** when it appears.
3. Check your camera and microphone.
4. Use the controls to mute, turn your camera on or off, share your screen, or nudge your teacher if needed.
5. Minimize the call if you need to open another part of SpiralClass; it stays active.
6. Leave the call when the lesson ends.



## Tips

- Only one person can share a screen at a time.
- On mobile, screen sharing is available on Android. It is not available on iPhone or iPad.
- Your teacher may make class materials available from the call or class page.

Suggested video: **“Join Your First Live Lesson (1 minute)”**

## Troubleshooting

**I cannot join the call.** Check your connection, refresh the class page, and allow camera and microphone permissions.

**I cannot hear anyone.** Check your device volume, headphones, and mute control.

## Questions

**Can I leave the call open while I check a message?** Yes. Minimize the call instead of leaving it.
`,
      "es-MX": `## Propósito

Únete a tu lección programada y usa la cámara, el micrófono y otros controles de llamada.

## Antes de empezar

- Abre una lección próxima cerca de su hora de inicio.
- Permite el acceso a la cámara y al micrófono cuando se solicite.
- Usa una conexión a internet confiable y audífonos si es posible.

## Pasos

1. Abre la clase próxima en **Mis clases**.
2. Selecciona **Unirse a la llamada** cuando aparezca.
3. Revisa tu cámara y micrófono.
4. Usa los controles para silenciarte, activar o desactivar tu cámara, compartir pantalla o avisar a tu profesor si lo necesitas.
5. Minimiza la llamada si necesitas abrir otra parte de SpiralClass; sigue activa.
6. Sal de la llamada cuando termine la lección.



## Consejos

- Solo una persona puede compartir pantalla a la vez.
- En dispositivos móviles, compartir pantalla está disponible en Android. No está disponible en iPhone ni iPad.
- Tu profesor puede poner materiales de clase disponibles desde la llamada o la página de la clase.

Video sugerido: **"Únete a tu primera lección en vivo (1 minuto)"**

## Solución de problemas

**No puedo unirme a la llamada.** Revisa tu conexión, actualiza la página de la clase y permite los permisos de cámara y micrófono.

**No escucho a nadie.** Revisa el volumen de tu dispositivo, tus audífonos y el control de silencio.

## Preguntas

**¿Puedo dejar la llamada abierta mientras reviso un mensaje?** Sí. Minimiza la llamada en vez de salir.
`,
    },
  },
  {
    slug: "materials-and-homework",
    audience: "student",
    title: { en: `Materials and homework`, "es-MX": `Materiales y tareas` },
    summary: {
      en: `Find learning materials for your level and complete homework assigned to a class.`,
      "es-MX": `Encuentra materiales de aprendizaje para tu nivel y completa las tareas asignadas a una clase.`,
    },
    body: {
      en: `## Purpose

Find learning materials for your level and complete homework assigned to a class.

## Before you start

- Sign in to your student account.
- Homework is written and submitted in your browser, on the assignment page.

## Steps

### View materials

1. Open **Materials** or a class detail page.
2. Choose a material to read, open, download, or listen to when available.
3. Open class content from the relevant lesson whenever you need it.

You may see materials selected for your level, materials assigned directly to you, and materials attached to a class.

### Submit homework

1. Open the class with the homework card.
2. Open the assignment.
3. Write your answer. It saves as a draft while you work.
4. Add files if needed. Each file can be up to 25 MB.
5. Select **Submit**.
6. Return to the assignment later to read feedback.



## Tips

- Your draft is saved automatically, including when your connection drops.
- Submit before the due date when possible.
- Only submit when you are ready: the work becomes read-only unless your teacher reopens it.

## Troubleshooting

**I cannot submit.** The due date may have passed without late submissions allowed, or the assignment may already be final.

**I cannot see homework feedback.** Your teacher may not have reviewed the submission yet.

## Questions

**Can I submit again?** Yes, when your teacher requests a resubmission or rejects the previous attempt.

**Can I view class content after the lesson?** Yes. Saved class content remains available from the class page.
`,
      "es-MX": `## Propósito

Encuentra materiales de aprendizaje para tu nivel y completa las tareas asignadas a una clase.

## Antes de empezar

- Inicia sesión en tu cuenta de alumno.
- Las tareas se escriben y se entregan desde tu navegador, en la página de la tarea.

## Pasos

### Ver materiales

1. Abre **Materiales** o la página de detalle de una clase.
2. Elige un material para leer, abrir, descargar o escuchar cuando esté disponible.
3. Abre el contenido de clase desde la lección correspondiente cuando lo necesites.

Puedes ver materiales seleccionados para tu nivel, materiales asignados directamente a ti, y materiales adjuntos a una clase.

### Entregar una tarea

1. Abre la clase con la tarjeta de tarea.
2. Abre la asignación.
3. Escribe tu respuesta. Se guarda como borrador mientras trabajas.
4. Agrega archivos si es necesario. Cada archivo puede pesar hasta 25 MB.
5. Selecciona **Entregar**.
6. Regresa a la asignación más tarde para leer los comentarios.



## Consejos

- Tu borrador se guarda automáticamente, incluso si se cae tu conexión.
- Entrega antes de la fecha límite cuando sea posible.
- Entrega solo cuando estés listo: el trabajo se vuelve de solo lectura a menos que tu profesor lo reabra.

## Solución de problemas

**No puedo entregar.** Puede que la fecha límite ya haya pasado sin permitir entregas tardías, o que la asignación ya sea final.

**No puedo ver los comentarios de la tarea.** Puede que tu profesor aún no haya revisado la entrega.

## Preguntas

**¿Puedo entregar de nuevo?** Sí, cuando tu profesor solicita un reenvío o rechaza el intento anterior.

**¿Puedo ver el contenido de clase después de la lección?** Sí. El contenido de clase guardado sigue disponible desde la página de la clase.
`,
    },
  },
  {
    slug: "progress",
    audience: "student",
    title: { en: `View your progress`, "es-MX": `Consulta tu progreso` },
    summary: {
      en: `See the progress your teacher has chosen to share and review vocabulary when it is available.`,
      "es-MX": `Consulta el progreso que tu profesor ha decidido compartir y repasa vocabulario cuando esté disponible.`,
    },
    body: {
      en: `## Purpose

See the progress your teacher has chosen to share and review vocabulary when it is available.

## Before you start

- You must be signed in as a student.
- Your teacher must turn on progress sharing for you.

## Steps

1. Open **Your progress** for the relevant teacher.
2. Review the areas marked as improving and the areas worth practising.
3. If vocabulary cards are available, open one card at a time.
4. Flip the card to see its context, then choose **Again**, **Hard**, **Good**, or **Easy** to continue.



## Tips

- Progress is shown separately for each teacher.
- Use the vocabulary review regularly. Choose the answer that best reflects how well you remembered it.

## Troubleshooting

**I cannot see Your progress.** Your teacher may not have turned sharing on yet, or there may not be progress ready to show.

**I do not see vocabulary cards.** Vocabulary review appears only when relevant vocabulary is available.

## Questions

**Can I see my teacher’s detailed lesson notes?** No. Your progress view is a student-friendly summary.

**Can I change the progress findings?** No. Ask your teacher if you have a question about them.
`,
      "es-MX": `## Propósito

Consulta el progreso que tu profesor ha decidido compartir y repasa vocabulario cuando esté disponible.

## Antes de empezar

- Debes tener sesión iniciada como alumno.
- Tu profesor debe activar el compartir progreso contigo.

## Pasos

1. Abre **Tu progreso** para el profesor correspondiente.
2. Revisa las áreas marcadas como en mejora y las áreas que vale la pena practicar.
3. Si hay tarjetas de vocabulario disponibles, abre una tarjeta a la vez.
4. Voltea la tarjeta para ver su contexto y luego elige **De nuevo**, **Difícil**, **Bien** o **Fácil** para continuar.



## Consejos

- El progreso se muestra por separado para cada profesor.
- Usa el repaso de vocabulario con regularidad. Elige la respuesta que mejor refleje qué tan bien lo recordaste.

## Solución de problemas

**No puedo ver Tu progreso.** Puede que tu profesor aún no haya activado el compartir, o que todavía no haya progreso listo para mostrar.

**No veo tarjetas de vocabulario.** El repaso de vocabulario aparece solo cuando hay vocabulario relevante disponible.

## Preguntas

**¿Puedo ver las notas detalladas de lección de mi profesor?** No. Tu vista de progreso es un resumen pensado para alumnos.

**¿Puedo cambiar los hallazgos de progreso?** No. Pregúntale a tu profesor si tienes dudas sobre ellos.
`,
    },
  },
  {
    slug: "messages-and-notifications",
    audience: "student",
    title: { en: `Messages and notifications`, "es-MX": `Mensajes y notificaciones` },
    summary: {
      en: `Message your teacher and control how SpiralClass notifies you about lessons and learning.`,
      "es-MX": `Envía mensajes a tu profesor y controla cómo te notifica SpiralClass sobre lecciones y aprendizaje.`,
    },
    body: {
      en: `## Purpose

Message your teacher and control how SpiralClass notifies you about lessons and learning.

## Before you start

- Sign in to your student account.
- Your teacher must be an active connection in SpiralClass.

## Steps

### Send a message

1. Open **Messages**.
2. Open your conversation with the teacher.
3. Write a message or attach a voice note, video, image, or file.
4. Send.

You can edit a text-only message within 15 minutes. You can delete a message for everyone within about two and a half days.

### Change notification settings

1. Open **Account → Notifications**.
2. Turn categories or email/push delivery on or off.
3. Save your changes.



## Tips

- Open a conversation to mark messages as read.
- If push notifications are unavailable, you may receive an email instead.
- Payment, sign-in, and certain important lesson notices cannot be turned off.

## Troubleshooting

**I am not receiving notifications.** Check the notification switches in SpiralClass and your phone’s permission for notifications.

**I cannot edit a message.** Editing is only for text-only messages during the 15-minute editing period.

## Questions

**Can I undo a deleted message?** No. Deleting a message cannot be undone.

**Why did I get an email as well as a notification?** Important notices may use every available contact method. Unread messages can also be followed by email.
`,
      "es-MX": `## Propósito

Envía mensajes a tu profesor y controla cómo te notifica SpiralClass sobre lecciones y aprendizaje.

## Antes de empezar

- Inicia sesión en tu cuenta de alumno.
- Tu profesor debe ser una conexión activa en SpiralClass.

## Pasos

### Enviar un mensaje

1. Abre **Mensajes**.
2. Abre tu conversación con el profesor.
3. Escribe un mensaje o adjunta una nota de voz, video, imagen o archivo.
4. Envía.

Puedes editar un mensaje de solo texto dentro de los primeros 15 minutos. Puedes eliminar un mensaje para todos dentro de aproximadamente dos días y medio.

### Cambiar la configuración de notificaciones

1. Abre **Cuenta → Notificaciones**.
2. Activa o desactiva categorías o la entrega por correo/push.
3. Guarda tus cambios.



## Consejos

- Abre una conversación para marcar los mensajes como leídos.
- Si las notificaciones push no están disponibles, puedes recibir un correo en su lugar.
- Los avisos de pago, inicio de sesión y ciertos avisos importantes de lección no se pueden desactivar.

## Solución de problemas

**No estoy recibiendo notificaciones.** Revisa los interruptores de notificación en SpiralClass y el permiso de notificaciones de tu teléfono.

**No puedo editar un mensaje.** Solo se pueden editar los mensajes de solo texto, durante el periodo de edición de 15 minutos.

## Preguntas

**¿Puedo deshacer un mensaje eliminado?** No. Eliminar un mensaje no se puede deshacer.

**¿Por qué recibí un correo además de una notificación?** Los avisos importantes pueden usar todos los medios de contacto disponibles. Los mensajes no leídos también pueden seguirse por correo.
`,
    },
  },
  {
    slug: "faq",
    audience: "student",
    title: {
      en: `Student frequently asked questions`,
      "es-MX": `Preguntas frecuentes para alumnos`,
    },
    summary: {
      en: `Find quick answers to common questions about using SpiralClass as a student.`,
      "es-MX": `Encuentra respuestas rápidas a preguntas comunes sobre cómo usar SpiralClass como alumno.`,
    },
    body: {
      en: `## Purpose

Find quick answers to common questions about using SpiralClass as a student.

## Before you start

- Sign in with the email address connected to your teacher or purchase.
- Open the linked guide when an answer needs more detail.

## Questions

### Sign-in and account

**Do I need a password?** No. Sign in with an email code or, where available, Google.

**Why is my invitation not working?** Sign in with the exact email address your teacher invited.

### Packages and booking

**Why can’t I book a lesson?** You may need an active package, an open slot, or a lesson time that meets your teacher’s booking notice.

**What happens when a package expires?** Any unused classes in that package can no longer be booked.

**Can I cancel or move a lesson?** Yes, from the class page when the lesson and your package’s remaining change allowance permit it.

### Learning

**Where are my learning materials?** Open **Materials** or the relevant class page.

**Can I submit homework in a browser?** Yes. Open the class, open the assignment, write your answer and select **Submit**.

**Why can’t I see progress reports?** Your teacher controls whether their progress view is shared with you.

### Live lessons and messages

**What should I do if I cannot join a call?** Check your connection and device permissions, then refresh the class page.

**Can I edit or remove a message?** Text-only messages can be edited within 15 minutes; messages can be deleted for everyone within about two and a half days.

## Still need help?

Check the relevant guide in the [Student Help Centre](index.md), then contact your teacher or usual SpiralClass support channel if the issue continues.

## Tips

- Check the lesson date, time, and timezone before confirming a booking.
- Keep the email on your account current so you receive sign-in codes.

## Troubleshooting

If something on screen differs from these answers, do not repeat a payment or booking. Take a screenshot and contact your teacher or support.
`,
      "es-MX": `## Propósito

Encuentra respuestas rápidas a preguntas comunes sobre cómo usar SpiralClass como alumno.

## Antes de empezar

- Inicia sesión con el correo conectado a tu profesor o a tu compra.
- Abre la guía enlazada cuando una respuesta necesite más detalle.

## Preguntas

### Inicio de sesión y cuenta

**¿Necesito una contraseña?** No. Inicia sesión con un código por correo o, donde esté disponible, con Google.

**¿Por qué no funciona mi invitación?** Inicia sesión con el correo exacto al que tu profesor te invitó.

### Paquetes y reservas

**¿Por qué no puedo reservar una lección?** Puede que necesites un paquete activo, un horario disponible, o una hora de lección que cumpla con el aviso de reserva de tu profesor.

**¿Qué pasa cuando vence un paquete?** Las clases sin usar de ese paquete ya no se pueden reservar.

**¿Puedo cancelar o cambiar una lección?** Sí, desde la página de la clase cuando la lección y el margen de cambios restante de tu paquete lo permitan.

### Aprendizaje

**¿Dónde están mis materiales de aprendizaje?** Abre **Materiales** o la página de la clase correspondiente.

**¿Puedo entregar tareas desde un navegador?** Sí. Abre la clase, abre la tarea, escribe tu respuesta y selecciona **Entregar**.

**¿Por qué no puedo ver informes de progreso?** Tu profesor controla si su vista de progreso se comparte contigo.

### Lecciones en vivo y mensajes

**¿Qué hago si no puedo unirme a una llamada?** Revisa tu conexión y los permisos de tu dispositivo, y luego actualiza la página de la clase.

**¿Puedo editar o eliminar un mensaje?** Los mensajes de solo texto se pueden editar dentro de los primeros 15 minutos; los mensajes se pueden eliminar para todos dentro de aproximadamente dos días y medio.

## ¿Sigues necesitando ayuda?

Consulta la guía correspondiente en el [Centro de ayuda para alumnos](index.es-MX.md) y luego contacta a tu profesor o a tu canal habitual de soporte de SpiralClass si el problema continúa.

## Consejos

- Revisa la fecha, hora y zona horaria de la lección antes de confirmar una reserva.
- Mantén actualizado el correo de tu cuenta para recibir los códigos de inicio de sesión.

## Solución de problemas

Si algo en pantalla difiere de estas respuestas, no repitas un pago o una reserva. Toma una captura de pantalla y contacta a tu profesor o a soporte.
`,
    },
  },
];
