// SpiralClass — static localized country names (ISO-3166-1 alpha-2 → { en, es-MX }).
//
// Generated from the platform ICU/CLDR data via Intl.DisplayNames so the names
// are correct and consistent, but shipped STATICALLY: React Native (Hermes) has
// no reliable Intl.DisplayNames at runtime, so relying on it there rendered raw
// codes ("MX", "US") in the picker. This catalog is the single source of truth
// countryLabel() reads, so web and mobile render identical names on every
// device. Regenerate with the snippet in countries.ts if COUNTRY_CODES changes.

export const COUNTRY_NAMES: Record<string, { en: string; "es-MX": string }> = {
  AD: { en: "Andorra", "es-MX": "Andorra" },
  AE: { en: "United Arab Emirates", "es-MX": "Emiratos Árabes Unidos" },
  AF: { en: "Afghanistan", "es-MX": "Afganistán" },
  AG: { en: "Antigua & Barbuda", "es-MX": "Antigua y Barbuda" },
  AI: { en: "Anguilla", "es-MX": "Anguila" },
  AL: { en: "Albania", "es-MX": "Albania" },
  AM: { en: "Armenia", "es-MX": "Armenia" },
  AO: { en: "Angola", "es-MX": "Angola" },
  AQ: { en: "Antarctica", "es-MX": "Antártida" },
  AR: { en: "Argentina", "es-MX": "Argentina" },
  AS: { en: "American Samoa", "es-MX": "Samoa Americana" },
  AT: { en: "Austria", "es-MX": "Austria" },
  AU: { en: "Australia", "es-MX": "Australia" },
  AW: { en: "Aruba", "es-MX": "Aruba" },
  AX: { en: "Åland Islands", "es-MX": "Islas Åland" },
  AZ: { en: "Azerbaijan", "es-MX": "Azerbaiyán" },
  BA: { en: "Bosnia & Herzegovina", "es-MX": "Bosnia y Herzegovina" },
  BB: { en: "Barbados", "es-MX": "Barbados" },
  BD: { en: "Bangladesh", "es-MX": "Bangladés" },
  BE: { en: "Belgium", "es-MX": "Bélgica" },
  BF: { en: "Burkina Faso", "es-MX": "Burkina Faso" },
  BG: { en: "Bulgaria", "es-MX": "Bulgaria" },
  BH: { en: "Bahrain", "es-MX": "Baréin" },
  BI: { en: "Burundi", "es-MX": "Burundi" },
  BJ: { en: "Benin", "es-MX": "Benín" },
  BL: { en: "St. Barthélemy", "es-MX": "San Bartolomé" },
  BM: { en: "Bermuda", "es-MX": "Bermudas" },
  BN: { en: "Brunei", "es-MX": "Brunéi" },
  BO: { en: "Bolivia", "es-MX": "Bolivia" },
  BQ: { en: "Caribbean Netherlands", "es-MX": "Caribe neerlandés" },
  BR: { en: "Brazil", "es-MX": "Brasil" },
  BS: { en: "Bahamas", "es-MX": "Bahamas" },
  BT: { en: "Bhutan", "es-MX": "Bután" },
  BV: { en: "Bouvet Island", "es-MX": "Isla Bouvet" },
  BW: { en: "Botswana", "es-MX": "Botsuana" },
  BY: { en: "Belarus", "es-MX": "Bielorrusia" },
  BZ: { en: "Belize", "es-MX": "Belice" },
  CA: { en: "Canada", "es-MX": "Canadá" },
  CC: { en: "Cocos (Keeling) Islands", "es-MX": "Islas Cocos" },
  CD: { en: "Congo - Kinshasa", "es-MX": "República Democrática del Congo" },
  CF: { en: "Central African Republic", "es-MX": "República Centroafricana" },
  CG: { en: "Congo - Brazzaville", "es-MX": "República del Congo" },
  CH: { en: "Switzerland", "es-MX": "Suiza" },
  CI: { en: "Côte d’Ivoire", "es-MX": "Côte d’Ivoire" },
  CK: { en: "Cook Islands", "es-MX": "Islas Cook" },
  CL: { en: "Chile", "es-MX": "Chile" },
  CM: { en: "Cameroon", "es-MX": "Camerún" },
  CN: { en: "China", "es-MX": "China" },
  CO: { en: "Colombia", "es-MX": "Colombia" },
  CR: { en: "Costa Rica", "es-MX": "Costa Rica" },
  CU: { en: "Cuba", "es-MX": "Cuba" },
  CV: { en: "Cape Verde", "es-MX": "Cabo Verde" },
  CW: { en: "Curaçao", "es-MX": "Curazao" },
  CX: { en: "Christmas Island", "es-MX": "Isla de Navidad" },
  CY: { en: "Cyprus", "es-MX": "Chipre" },
  CZ: { en: "Czechia", "es-MX": "Chequia" },
  DE: { en: "Germany", "es-MX": "Alemania" },
  DJ: { en: "Djibouti", "es-MX": "Yibuti" },
  DK: { en: "Denmark", "es-MX": "Dinamarca" },
  DM: { en: "Dominica", "es-MX": "Dominica" },
  DO: { en: "Dominican Republic", "es-MX": "República Dominicana" },
  DZ: { en: "Algeria", "es-MX": "Argelia" },
  EC: { en: "Ecuador", "es-MX": "Ecuador" },
  EE: { en: "Estonia", "es-MX": "Estonia" },
  EG: { en: "Egypt", "es-MX": "Egipto" },
  EH: { en: "Western Sahara", "es-MX": "Sáhara Occidental" },
  ER: { en: "Eritrea", "es-MX": "Eritrea" },
  ES: { en: "Spain", "es-MX": "España" },
  ET: { en: "Ethiopia", "es-MX": "Etiopía" },
  FI: { en: "Finland", "es-MX": "Finlandia" },
  FJ: { en: "Fiji", "es-MX": "Fiyi" },
  FK: { en: "Falkland Islands", "es-MX": "Islas Malvinas" },
  FM: { en: "Micronesia", "es-MX": "Micronesia" },
  FO: { en: "Faroe Islands", "es-MX": "Islas Feroe" },
  FR: { en: "France", "es-MX": "Francia" },
  GA: { en: "Gabon", "es-MX": "Gabón" },
  GB: { en: "United Kingdom", "es-MX": "Reino Unido" },
  GD: { en: "Grenada", "es-MX": "Granada" },
  GE: { en: "Georgia", "es-MX": "Georgia" },
  GF: { en: "French Guiana", "es-MX": "Guayana Francesa" },
  GG: { en: "Guernsey", "es-MX": "Guernsey" },
  GH: { en: "Ghana", "es-MX": "Ghana" },
  GI: { en: "Gibraltar", "es-MX": "Gibraltar" },
  GL: { en: "Greenland", "es-MX": "Groenlandia" },
  GM: { en: "Gambia", "es-MX": "Gambia" },
  GN: { en: "Guinea", "es-MX": "Guinea" },
  GP: { en: "Guadeloupe", "es-MX": "Guadalupe" },
  GQ: { en: "Equatorial Guinea", "es-MX": "Guinea Ecuatorial" },
  GR: { en: "Greece", "es-MX": "Grecia" },
  GS: {
    en: "South Georgia & South Sandwich Islands",
    "es-MX": "Islas Georgia del Sur y Sándwich del Sur",
  },
  GT: { en: "Guatemala", "es-MX": "Guatemala" },
  GU: { en: "Guam", "es-MX": "Guam" },
  GW: { en: "Guinea-Bissau", "es-MX": "Guinea-Bisáu" },
  GY: { en: "Guyana", "es-MX": "Guyana" },
  HK: { en: "Hong Kong SAR China", "es-MX": "RAE de Hong Kong (China)" },
  HM: { en: "Heard & McDonald Islands", "es-MX": "Islas Heard y McDonald" },
  HN: { en: "Honduras", "es-MX": "Honduras" },
  HR: { en: "Croatia", "es-MX": "Croacia" },
  HT: { en: "Haiti", "es-MX": "Haití" },
  HU: { en: "Hungary", "es-MX": "Hungría" },
  ID: { en: "Indonesia", "es-MX": "Indonesia" },
  IE: { en: "Ireland", "es-MX": "Irlanda" },
  IL: { en: "Israel", "es-MX": "Israel" },
  IM: { en: "Isle of Man", "es-MX": "Isla de Man" },
  IN: { en: "India", "es-MX": "India" },
  IO: { en: "British Indian Ocean Territory", "es-MX": "Territorio Británico del Océano Índico" },
  IQ: { en: "Iraq", "es-MX": "Irak" },
  IR: { en: "Iran", "es-MX": "Irán" },
  IS: { en: "Iceland", "es-MX": "Islandia" },
  IT: { en: "Italy", "es-MX": "Italia" },
  JE: { en: "Jersey", "es-MX": "Jersey" },
  JM: { en: "Jamaica", "es-MX": "Jamaica" },
  JO: { en: "Jordan", "es-MX": "Jordania" },
  JP: { en: "Japan", "es-MX": "Japón" },
  KE: { en: "Kenya", "es-MX": "Kenia" },
  KG: { en: "Kyrgyzstan", "es-MX": "Kirguistán" },
  KH: { en: "Cambodia", "es-MX": "Camboya" },
  KI: { en: "Kiribati", "es-MX": "Kiribati" },
  KM: { en: "Comoros", "es-MX": "Comoras" },
  KN: { en: "St. Kitts & Nevis", "es-MX": "San Cristóbal y Nieves" },
  KP: { en: "North Korea", "es-MX": "Corea del Norte" },
  KR: { en: "South Korea", "es-MX": "Corea del Sur" },
  KW: { en: "Kuwait", "es-MX": "Kuwait" },
  KY: { en: "Cayman Islands", "es-MX": "Islas Caimán" },
  KZ: { en: "Kazakhstan", "es-MX": "Kazajistán" },
  LA: { en: "Laos", "es-MX": "Laos" },
  LB: { en: "Lebanon", "es-MX": "Líbano" },
  LC: { en: "St. Lucia", "es-MX": "Santa Lucía" },
  LI: { en: "Liechtenstein", "es-MX": "Liechtenstein" },
  LK: { en: "Sri Lanka", "es-MX": "Sri Lanka" },
  LR: { en: "Liberia", "es-MX": "Liberia" },
  LS: { en: "Lesotho", "es-MX": "Lesoto" },
  LT: { en: "Lithuania", "es-MX": "Lituania" },
  LU: { en: "Luxembourg", "es-MX": "Luxemburgo" },
  LV: { en: "Latvia", "es-MX": "Letonia" },
  LY: { en: "Libya", "es-MX": "Libia" },
  MA: { en: "Morocco", "es-MX": "Marruecos" },
  MC: { en: "Monaco", "es-MX": "Mónaco" },
  MD: { en: "Moldova", "es-MX": "Moldavia" },
  ME: { en: "Montenegro", "es-MX": "Montenegro" },
  MF: { en: "St. Martin", "es-MX": "San Martín" },
  MG: { en: "Madagascar", "es-MX": "Madagascar" },
  MH: { en: "Marshall Islands", "es-MX": "Islas Marshall" },
  MK: { en: "North Macedonia", "es-MX": "Macedonia del Norte" },
  ML: { en: "Mali", "es-MX": "Mali" },
  MM: { en: "Myanmar (Burma)", "es-MX": "Myanmar (Birmania)" },
  MN: { en: "Mongolia", "es-MX": "Mongolia" },
  MO: { en: "Macao SAR China", "es-MX": "RAE de Macao (China)" },
  MP: { en: "Northern Mariana Islands", "es-MX": "Islas Marianas del Norte" },
  MQ: { en: "Martinique", "es-MX": "Martinica" },
  MR: { en: "Mauritania", "es-MX": "Mauritania" },
  MS: { en: "Montserrat", "es-MX": "Montserrat" },
  MT: { en: "Malta", "es-MX": "Malta" },
  MU: { en: "Mauritius", "es-MX": "Mauricio" },
  MV: { en: "Maldives", "es-MX": "Maldivas" },
  MW: { en: "Malawi", "es-MX": "Malaui" },
  MX: { en: "Mexico", "es-MX": "México" },
  MY: { en: "Malaysia", "es-MX": "Malasia" },
  MZ: { en: "Mozambique", "es-MX": "Mozambique" },
  NA: { en: "Namibia", "es-MX": "Namibia" },
  NC: { en: "New Caledonia", "es-MX": "Nueva Caledonia" },
  NE: { en: "Niger", "es-MX": "Níger" },
  NF: { en: "Norfolk Island", "es-MX": "Isla Norfolk" },
  NG: { en: "Nigeria", "es-MX": "Nigeria" },
  NI: { en: "Nicaragua", "es-MX": "Nicaragua" },
  NL: { en: "Netherlands", "es-MX": "Países Bajos" },
  NO: { en: "Norway", "es-MX": "Noruega" },
  NP: { en: "Nepal", "es-MX": "Nepal" },
  NR: { en: "Nauru", "es-MX": "Nauru" },
  NU: { en: "Niue", "es-MX": "Niue" },
  NZ: { en: "New Zealand", "es-MX": "Nueva Zelanda" },
  OM: { en: "Oman", "es-MX": "Omán" },
  PA: { en: "Panama", "es-MX": "Panamá" },
  PE: { en: "Peru", "es-MX": "Perú" },
  PF: { en: "French Polynesia", "es-MX": "Polinesia Francesa" },
  PG: { en: "Papua New Guinea", "es-MX": "Papúa Nueva Guinea" },
  PH: { en: "Philippines", "es-MX": "Filipinas" },
  PK: { en: "Pakistan", "es-MX": "Pakistán" },
  PL: { en: "Poland", "es-MX": "Polonia" },
  PM: { en: "St. Pierre & Miquelon", "es-MX": "San Pedro y Miquelón" },
  PN: { en: "Pitcairn Islands", "es-MX": "Islas Pitcairn" },
  PR: { en: "Puerto Rico", "es-MX": "Puerto Rico" },
  PS: { en: "Palestinian Territories", "es-MX": "Territorios Palestinos" },
  PT: { en: "Portugal", "es-MX": "Portugal" },
  PW: { en: "Palau", "es-MX": "Palaos" },
  PY: { en: "Paraguay", "es-MX": "Paraguay" },
  QA: { en: "Qatar", "es-MX": "Catar" },
  RE: { en: "Réunion", "es-MX": "Reunión" },
  RO: { en: "Romania", "es-MX": "Rumania" },
  RS: { en: "Serbia", "es-MX": "Serbia" },
  RU: { en: "Russia", "es-MX": "Rusia" },
  RW: { en: "Rwanda", "es-MX": "Ruanda" },
  SA: { en: "Saudi Arabia", "es-MX": "Arabia Saudita" },
  SB: { en: "Solomon Islands", "es-MX": "Islas Salomón" },
  SC: { en: "Seychelles", "es-MX": "Seychelles" },
  SD: { en: "Sudan", "es-MX": "Sudán" },
  SE: { en: "Sweden", "es-MX": "Suecia" },
  SG: { en: "Singapore", "es-MX": "Singapur" },
  SH: { en: "St. Helena", "es-MX": "Santa Elena" },
  SI: { en: "Slovenia", "es-MX": "Eslovenia" },
  SJ: { en: "Svalbard & Jan Mayen", "es-MX": "Svalbard y Jan Mayen" },
  SK: { en: "Slovakia", "es-MX": "Eslovaquia" },
  SL: { en: "Sierra Leone", "es-MX": "Sierra Leona" },
  SM: { en: "San Marino", "es-MX": "San Marino" },
  SN: { en: "Senegal", "es-MX": "Senegal" },
  SO: { en: "Somalia", "es-MX": "Somalia" },
  SR: { en: "Suriname", "es-MX": "Surinam" },
  SS: { en: "South Sudan", "es-MX": "Sudán del Sur" },
  ST: { en: "São Tomé & Príncipe", "es-MX": "Santo Tomé y Príncipe" },
  SV: { en: "El Salvador", "es-MX": "El Salvador" },
  SX: { en: "Sint Maarten", "es-MX": "Sint Maarten" },
  SY: { en: "Syria", "es-MX": "Siria" },
  SZ: { en: "Eswatini", "es-MX": "Eswatini" },
  TC: { en: "Turks & Caicos Islands", "es-MX": "Islas Turcas y Caicos" },
  TD: { en: "Chad", "es-MX": "Chad" },
  TF: { en: "French Southern Territories", "es-MX": "Territorios Australes Franceses" },
  TG: { en: "Togo", "es-MX": "Togo" },
  TH: { en: "Thailand", "es-MX": "Tailandia" },
  TJ: { en: "Tajikistan", "es-MX": "Tayikistán" },
  TK: { en: "Tokelau", "es-MX": "Tokelau" },
  TL: { en: "Timor-Leste", "es-MX": "Timor Oriental" },
  TM: { en: "Turkmenistan", "es-MX": "Turkmenistán" },
  TN: { en: "Tunisia", "es-MX": "Túnez" },
  TO: { en: "Tonga", "es-MX": "Tonga" },
  TR: { en: "Türkiye", "es-MX": "Turquía" },
  TT: { en: "Trinidad & Tobago", "es-MX": "Trinidad y Tobago" },
  TV: { en: "Tuvalu", "es-MX": "Tuvalu" },
  TW: { en: "Taiwan", "es-MX": "Taiwán" },
  TZ: { en: "Tanzania", "es-MX": "Tanzania" },
  UA: { en: "Ukraine", "es-MX": "Ucrania" },
  UG: { en: "Uganda", "es-MX": "Uganda" },
  UM: { en: "U.S. Outlying Islands", "es-MX": "Islas menores alejadas de EE. UU." },
  US: { en: "United States", "es-MX": "Estados Unidos" },
  UY: { en: "Uruguay", "es-MX": "Uruguay" },
  UZ: { en: "Uzbekistan", "es-MX": "Uzbekistán" },
  VA: { en: "Vatican City", "es-MX": "Ciudad del Vaticano" },
  VC: { en: "St. Vincent & Grenadines", "es-MX": "San Vicente y las Granadinas" },
  VE: { en: "Venezuela", "es-MX": "Venezuela" },
  VG: { en: "British Virgin Islands", "es-MX": "Islas Vírgenes Británicas" },
  VI: { en: "U.S. Virgin Islands", "es-MX": "Islas Vírgenes de EE. UU." },
  VN: { en: "Vietnam", "es-MX": "Vietnam" },
  VU: { en: "Vanuatu", "es-MX": "Vanuatu" },
  WF: { en: "Wallis & Futuna", "es-MX": "Wallis y Futuna" },
  WS: { en: "Samoa", "es-MX": "Samoa" },
  YE: { en: "Yemen", "es-MX": "Yemen" },
  YT: { en: "Mayotte", "es-MX": "Mayotte" },
  ZA: { en: "South Africa", "es-MX": "Sudáfrica" },
  ZM: { en: "Zambia", "es-MX": "Zambia" },
  ZW: { en: "Zimbabwe", "es-MX": "Zimbabue" },
};
