// SpiralClass — static localized country names: ISO-3166-1 alpha-2 → one name
// per registered UI locale.
//
// Filled in by scripts/generate-locale-names.mjs from the platform's CLDR data
// (Intl.DisplayNames), and shipped STATICALLY rather than asked of Intl at
// render: the server and the browser each carry their own CLDR, and where the
// two disagree on a name, a name rendered on both is a hydration mismatch and
// a picker sorted by name comes out in two orders. This catalog is the single
// source of truth countryLabel() reads.
//
// The type is keyed by AppLocale on purpose: registering a locale makes this
// table fail to compile until the generator has been run for it. The generator
// only ever ADDS a missing column, so it never renames a country behind
// someone's back.

import type { AppLocale } from "./i18n/locales";

export const COUNTRY_NAMES: Record<string, Record<AppLocale, string>> = {
  AD: { en: "Andorra", es: "Andorra", fr: "Andorre" },
  AE: { en: "United Arab Emirates", es: "Emiratos Árabes Unidos", fr: "Émirats arabes unis" },
  AF: { en: "Afghanistan", es: "Afganistán", fr: "Afghanistan" },
  AG: { en: "Antigua & Barbuda", es: "Antigua y Barbuda", fr: "Antigua-et-Barbuda" },
  AI: { en: "Anguilla", es: "Anguila", fr: "Anguilla" },
  AL: { en: "Albania", es: "Albania", fr: "Albanie" },
  AM: { en: "Armenia", es: "Armenia", fr: "Arménie" },
  AO: { en: "Angola", es: "Angola", fr: "Angola" },
  AQ: { en: "Antarctica", es: "Antártida", fr: "Antarctique" },
  AR: { en: "Argentina", es: "Argentina", fr: "Argentine" },
  AS: { en: "American Samoa", es: "Samoa Americana", fr: "Samoa américaines" },
  AT: { en: "Austria", es: "Austria", fr: "Autriche" },
  AU: { en: "Australia", es: "Australia", fr: "Australie" },
  AW: { en: "Aruba", es: "Aruba", fr: "Aruba" },
  AX: { en: "Åland Islands", es: "Islas Åland", fr: "Îles Åland" },
  AZ: { en: "Azerbaijan", es: "Azerbaiyán", fr: "Azerbaïdjan" },
  BA: { en: "Bosnia & Herzegovina", es: "Bosnia y Herzegovina", fr: "Bosnie-Herzégovine" },
  BB: { en: "Barbados", es: "Barbados", fr: "Barbade" },
  BD: { en: "Bangladesh", es: "Bangladés", fr: "Bangladesh" },
  BE: { en: "Belgium", es: "Bélgica", fr: "Belgique" },
  BF: { en: "Burkina Faso", es: "Burkina Faso", fr: "Burkina Faso" },
  BG: { en: "Bulgaria", es: "Bulgaria", fr: "Bulgarie" },
  BH: { en: "Bahrain", es: "Baréin", fr: "Bahreïn" },
  BI: { en: "Burundi", es: "Burundi", fr: "Burundi" },
  BJ: { en: "Benin", es: "Benín", fr: "Bénin" },
  BL: { en: "St. Barthélemy", es: "San Bartolomé", fr: "Saint-Barthélemy" },
  BM: { en: "Bermuda", es: "Bermudas", fr: "Bermudes" },
  BN: { en: "Brunei", es: "Brunéi", fr: "Brunei" },
  BO: { en: "Bolivia", es: "Bolivia", fr: "Bolivie" },
  BQ: { en: "Caribbean Netherlands", es: "Caribe neerlandés", fr: "Pays-Bas caribéens" },
  BR: { en: "Brazil", es: "Brasil", fr: "Brésil" },
  BS: { en: "Bahamas", es: "Bahamas", fr: "Bahamas" },
  BT: { en: "Bhutan", es: "Bután", fr: "Bhoutan" },
  BV: { en: "Bouvet Island", es: "Isla Bouvet", fr: "Île Bouvet" },
  BW: { en: "Botswana", es: "Botsuana", fr: "Botswana" },
  BY: { en: "Belarus", es: "Bielorrusia", fr: "Biélorussie" },
  BZ: { en: "Belize", es: "Belice", fr: "Belize" },
  CA: { en: "Canada", es: "Canadá", fr: "Canada" },
  CC: { en: "Cocos (Keeling) Islands", es: "Islas Cocos", fr: "Îles Cocos" },
  CD: { en: "Congo - Kinshasa", es: "República Democrática del Congo", fr: "Congo-Kinshasa" },
  CF: {
    en: "Central African Republic",
    es: "República Centroafricana",
    fr: "République centrafricaine",
  },
  CG: { en: "Congo - Brazzaville", es: "República del Congo", fr: "Congo-Brazzaville" },
  CH: { en: "Switzerland", es: "Suiza", fr: "Suisse" },
  CI: { en: "Côte d’Ivoire", es: "Côte d’Ivoire", fr: "Côte d’Ivoire" },
  CK: { en: "Cook Islands", es: "Islas Cook", fr: "Îles Cook" },
  CL: { en: "Chile", es: "Chile", fr: "Chili" },
  CM: { en: "Cameroon", es: "Camerún", fr: "Cameroun" },
  CN: { en: "China", es: "China", fr: "Chine" },
  CO: { en: "Colombia", es: "Colombia", fr: "Colombie" },
  CR: { en: "Costa Rica", es: "Costa Rica", fr: "Costa Rica" },
  CU: { en: "Cuba", es: "Cuba", fr: "Cuba" },
  CV: { en: "Cape Verde", es: "Cabo Verde", fr: "Cap-Vert" },
  CW: { en: "Curaçao", es: "Curazao", fr: "Curaçao" },
  CX: { en: "Christmas Island", es: "Isla de Navidad", fr: "Île Christmas" },
  CY: { en: "Cyprus", es: "Chipre", fr: "Chypre" },
  CZ: { en: "Czechia", es: "Chequia", fr: "Tchéquie" },
  DE: { en: "Germany", es: "Alemania", fr: "Allemagne" },
  DJ: { en: "Djibouti", es: "Yibuti", fr: "Djibouti" },
  DK: { en: "Denmark", es: "Dinamarca", fr: "Danemark" },
  DM: { en: "Dominica", es: "Dominica", fr: "Dominique" },
  DO: { en: "Dominican Republic", es: "República Dominicana", fr: "République dominicaine" },
  DZ: { en: "Algeria", es: "Argelia", fr: "Algérie" },
  EC: { en: "Ecuador", es: "Ecuador", fr: "Équateur" },
  EE: { en: "Estonia", es: "Estonia", fr: "Estonie" },
  EG: { en: "Egypt", es: "Egipto", fr: "Égypte" },
  EH: { en: "Western Sahara", es: "Sáhara Occidental", fr: "Sahara occidental" },
  ER: { en: "Eritrea", es: "Eritrea", fr: "Érythrée" },
  ES: { en: "Spain", es: "España", fr: "Espagne" },
  ET: { en: "Ethiopia", es: "Etiopía", fr: "Éthiopie" },
  FI: { en: "Finland", es: "Finlandia", fr: "Finlande" },
  FJ: { en: "Fiji", es: "Fiyi", fr: "Fidji" },
  FK: { en: "Falkland Islands", es: "Islas Malvinas", fr: "Îles Malouines" },
  FM: { en: "Micronesia", es: "Micronesia", fr: "Micronésie" },
  FO: { en: "Faroe Islands", es: "Islas Feroe", fr: "Îles Féroé" },
  FR: { en: "France", es: "Francia", fr: "France" },
  GA: { en: "Gabon", es: "Gabón", fr: "Gabon" },
  GB: { en: "United Kingdom", es: "Reino Unido", fr: "Royaume-Uni" },
  GD: { en: "Grenada", es: "Granada", fr: "Grenade" },
  GE: { en: "Georgia", es: "Georgia", fr: "Géorgie" },
  GF: { en: "French Guiana", es: "Guayana Francesa", fr: "Guyane française" },
  GG: { en: "Guernsey", es: "Guernsey", fr: "Guernesey" },
  GH: { en: "Ghana", es: "Ghana", fr: "Ghana" },
  GI: { en: "Gibraltar", es: "Gibraltar", fr: "Gibraltar" },
  GL: { en: "Greenland", es: "Groenlandia", fr: "Groenland" },
  GM: { en: "Gambia", es: "Gambia", fr: "Gambie" },
  GN: { en: "Guinea", es: "Guinea", fr: "Guinée" },
  GP: { en: "Guadeloupe", es: "Guadalupe", fr: "Guadeloupe" },
  GQ: { en: "Equatorial Guinea", es: "Guinea Ecuatorial", fr: "Guinée équatoriale" },
  GR: { en: "Greece", es: "Grecia", fr: "Grèce" },
  GS: {
    en: "South Georgia & South Sandwich Islands",
    es: "Islas Georgia del Sur y Sándwich del Sur",
    fr: "Géorgie du Sud-et-les Îles Sandwich du Sud",
  },
  GT: { en: "Guatemala", es: "Guatemala", fr: "Guatemala" },
  GU: { en: "Guam", es: "Guam", fr: "Guam" },
  GW: { en: "Guinea-Bissau", es: "Guinea-Bisáu", fr: "Guinée-Bissau" },
  GY: { en: "Guyana", es: "Guyana", fr: "Guyana" },
  HK: {
    en: "Hong Kong SAR China",
    es: "RAE de Hong Kong (China)",
    fr: "R.A.S. chinoise de Hong Kong",
  },
  HM: {
    en: "Heard & McDonald Islands",
    es: "Islas Heard y McDonald",
    fr: "Îles Heard-et-MacDonald",
  },
  HN: { en: "Honduras", es: "Honduras", fr: "Honduras" },
  HR: { en: "Croatia", es: "Croacia", fr: "Croatie" },
  HT: { en: "Haiti", es: "Haití", fr: "Haïti" },
  HU: { en: "Hungary", es: "Hungría", fr: "Hongrie" },
  ID: { en: "Indonesia", es: "Indonesia", fr: "Indonésie" },
  IE: { en: "Ireland", es: "Irlanda", fr: "Irlande" },
  IL: { en: "Israel", es: "Israel", fr: "Israël" },
  IM: { en: "Isle of Man", es: "Isla de Man", fr: "Île de Man" },
  IN: { en: "India", es: "India", fr: "Inde" },
  IO: {
    en: "British Indian Ocean Territory",
    es: "Territorio Británico del Océano Índico",
    fr: "Territoire britannique de l’océan Indien",
  },
  IQ: { en: "Iraq", es: "Irak", fr: "Irak" },
  IR: { en: "Iran", es: "Irán", fr: "Iran" },
  IS: { en: "Iceland", es: "Islandia", fr: "Islande" },
  IT: { en: "Italy", es: "Italia", fr: "Italie" },
  JE: { en: "Jersey", es: "Jersey", fr: "Jersey" },
  JM: { en: "Jamaica", es: "Jamaica", fr: "Jamaïque" },
  JO: { en: "Jordan", es: "Jordania", fr: "Jordanie" },
  JP: { en: "Japan", es: "Japón", fr: "Japon" },
  KE: { en: "Kenya", es: "Kenia", fr: "Kenya" },
  KG: { en: "Kyrgyzstan", es: "Kirguistán", fr: "Kirghizstan" },
  KH: { en: "Cambodia", es: "Camboya", fr: "Cambodge" },
  KI: { en: "Kiribati", es: "Kiribati", fr: "Kiribati" },
  KM: { en: "Comoros", es: "Comoras", fr: "Comores" },
  KN: { en: "St. Kitts & Nevis", es: "San Cristóbal y Nieves", fr: "Saint-Christophe-et-Niévès" },
  KP: { en: "North Korea", es: "Corea del Norte", fr: "Corée du Nord" },
  KR: { en: "South Korea", es: "Corea del Sur", fr: "Corée du Sud" },
  KW: { en: "Kuwait", es: "Kuwait", fr: "Koweït" },
  KY: { en: "Cayman Islands", es: "Islas Caimán", fr: "Îles Caïmans" },
  KZ: { en: "Kazakhstan", es: "Kazajistán", fr: "Kazakhstan" },
  LA: { en: "Laos", es: "Laos", fr: "Laos" },
  LB: { en: "Lebanon", es: "Líbano", fr: "Liban" },
  LC: { en: "St. Lucia", es: "Santa Lucía", fr: "Sainte-Lucie" },
  LI: { en: "Liechtenstein", es: "Liechtenstein", fr: "Liechtenstein" },
  LK: { en: "Sri Lanka", es: "Sri Lanka", fr: "Sri Lanka" },
  LR: { en: "Liberia", es: "Liberia", fr: "Liberia" },
  LS: { en: "Lesotho", es: "Lesoto", fr: "Lesotho" },
  LT: { en: "Lithuania", es: "Lituania", fr: "Lituanie" },
  LU: { en: "Luxembourg", es: "Luxemburgo", fr: "Luxembourg" },
  LV: { en: "Latvia", es: "Letonia", fr: "Lettonie" },
  LY: { en: "Libya", es: "Libia", fr: "Libye" },
  MA: { en: "Morocco", es: "Marruecos", fr: "Maroc" },
  MC: { en: "Monaco", es: "Mónaco", fr: "Monaco" },
  MD: { en: "Moldova", es: "Moldavia", fr: "Moldavie" },
  ME: { en: "Montenegro", es: "Montenegro", fr: "Monténégro" },
  MF: { en: "St. Martin", es: "San Martín", fr: "Saint-Martin" },
  MG: { en: "Madagascar", es: "Madagascar", fr: "Madagascar" },
  MH: { en: "Marshall Islands", es: "Islas Marshall", fr: "Îles Marshall" },
  MK: { en: "North Macedonia", es: "Macedonia del Norte", fr: "Macédoine du Nord" },
  ML: { en: "Mali", es: "Mali", fr: "Mali" },
  MM: { en: "Myanmar (Burma)", es: "Myanmar (Birmania)", fr: "Myanmar (Birmanie)" },
  MN: { en: "Mongolia", es: "Mongolia", fr: "Mongolie" },
  MO: { en: "Macao SAR China", es: "RAE de Macao (China)", fr: "R.A.S. chinoise de Macao" },
  MP: {
    en: "Northern Mariana Islands",
    es: "Islas Marianas del Norte",
    fr: "Îles Mariannes du Nord",
  },
  MQ: { en: "Martinique", es: "Martinica", fr: "Martinique" },
  MR: { en: "Mauritania", es: "Mauritania", fr: "Mauritanie" },
  MS: { en: "Montserrat", es: "Montserrat", fr: "Montserrat" },
  MT: { en: "Malta", es: "Malta", fr: "Malte" },
  MU: { en: "Mauritius", es: "Mauricio", fr: "Maurice" },
  MV: { en: "Maldives", es: "Maldivas", fr: "Maldives" },
  MW: { en: "Malawi", es: "Malaui", fr: "Malawi" },
  MX: { en: "Mexico", es: "México", fr: "Mexique" },
  MY: { en: "Malaysia", es: "Malasia", fr: "Malaisie" },
  MZ: { en: "Mozambique", es: "Mozambique", fr: "Mozambique" },
  NA: { en: "Namibia", es: "Namibia", fr: "Namibie" },
  NC: { en: "New Caledonia", es: "Nueva Caledonia", fr: "Nouvelle-Calédonie" },
  NE: { en: "Niger", es: "Níger", fr: "Niger" },
  NF: { en: "Norfolk Island", es: "Isla Norfolk", fr: "Île Norfolk" },
  NG: { en: "Nigeria", es: "Nigeria", fr: "Nigeria" },
  NI: { en: "Nicaragua", es: "Nicaragua", fr: "Nicaragua" },
  NL: { en: "Netherlands", es: "Países Bajos", fr: "Pays-Bas" },
  NO: { en: "Norway", es: "Noruega", fr: "Norvège" },
  NP: { en: "Nepal", es: "Nepal", fr: "Népal" },
  NR: { en: "Nauru", es: "Nauru", fr: "Nauru" },
  NU: { en: "Niue", es: "Niue", fr: "Niue" },
  NZ: { en: "New Zealand", es: "Nueva Zelanda", fr: "Nouvelle-Zélande" },
  OM: { en: "Oman", es: "Omán", fr: "Oman" },
  PA: { en: "Panama", es: "Panamá", fr: "Panama" },
  PE: { en: "Peru", es: "Perú", fr: "Pérou" },
  PF: { en: "French Polynesia", es: "Polinesia Francesa", fr: "Polynésie française" },
  PG: { en: "Papua New Guinea", es: "Papúa Nueva Guinea", fr: "Papouasie-Nouvelle-Guinée" },
  PH: { en: "Philippines", es: "Filipinas", fr: "Philippines" },
  PK: { en: "Pakistan", es: "Pakistán", fr: "Pakistan" },
  PL: { en: "Poland", es: "Polonia", fr: "Pologne" },
  PM: { en: "St. Pierre & Miquelon", es: "San Pedro y Miquelón", fr: "Saint-Pierre-et-Miquelon" },
  PN: { en: "Pitcairn Islands", es: "Islas Pitcairn", fr: "Îles Pitcairn" },
  PR: { en: "Puerto Rico", es: "Puerto Rico", fr: "Porto Rico" },
  PS: {
    en: "Palestinian Territories",
    es: "Territorios Palestinos",
    fr: "Territoires palestiniens",
  },
  PT: { en: "Portugal", es: "Portugal", fr: "Portugal" },
  PW: { en: "Palau", es: "Palaos", fr: "Palaos" },
  PY: { en: "Paraguay", es: "Paraguay", fr: "Paraguay" },
  QA: { en: "Qatar", es: "Catar", fr: "Qatar" },
  RE: { en: "Réunion", es: "Reunión", fr: "La Réunion" },
  RO: { en: "Romania", es: "Rumania", fr: "Roumanie" },
  RS: { en: "Serbia", es: "Serbia", fr: "Serbie" },
  RU: { en: "Russia", es: "Rusia", fr: "Russie" },
  RW: { en: "Rwanda", es: "Ruanda", fr: "Rwanda" },
  SA: { en: "Saudi Arabia", es: "Arabia Saudita", fr: "Arabie saoudite" },
  SB: { en: "Solomon Islands", es: "Islas Salomón", fr: "Îles Salomon" },
  SC: { en: "Seychelles", es: "Seychelles", fr: "Seychelles" },
  SD: { en: "Sudan", es: "Sudán", fr: "Soudan" },
  SE: { en: "Sweden", es: "Suecia", fr: "Suède" },
  SG: { en: "Singapore", es: "Singapur", fr: "Singapour" },
  SH: { en: "St. Helena", es: "Santa Elena", fr: "Sainte-Hélène" },
  SI: { en: "Slovenia", es: "Eslovenia", fr: "Slovénie" },
  SJ: { en: "Svalbard & Jan Mayen", es: "Svalbard y Jan Mayen", fr: "Svalbard et Jan Mayen" },
  SK: { en: "Slovakia", es: "Eslovaquia", fr: "Slovaquie" },
  SL: { en: "Sierra Leone", es: "Sierra Leona", fr: "Sierra Leone" },
  SM: { en: "San Marino", es: "San Marino", fr: "Saint-Marin" },
  SN: { en: "Senegal", es: "Senegal", fr: "Sénégal" },
  SO: { en: "Somalia", es: "Somalia", fr: "Somalie" },
  SR: { en: "Suriname", es: "Surinam", fr: "Suriname" },
  SS: { en: "South Sudan", es: "Sudán del Sur", fr: "Soudan du Sud" },
  ST: { en: "São Tomé & Príncipe", es: "Santo Tomé y Príncipe", fr: "Sao Tomé-et-Principe" },
  SV: { en: "El Salvador", es: "El Salvador", fr: "Salvador" },
  SX: { en: "Sint Maarten", es: "Sint Maarten", fr: "Saint-Martin (partie néerlandaise)" },
  SY: { en: "Syria", es: "Siria", fr: "Syrie" },
  SZ: { en: "Eswatini", es: "Eswatini", fr: "Eswatini" },
  TC: { en: "Turks & Caicos Islands", es: "Islas Turcas y Caicos", fr: "Îles Turques-et-Caïques" },
  TD: { en: "Chad", es: "Chad", fr: "Tchad" },
  TF: {
    en: "French Southern Territories",
    es: "Territorios Australes Franceses",
    fr: "Terres australes françaises",
  },
  TG: { en: "Togo", es: "Togo", fr: "Togo" },
  TH: { en: "Thailand", es: "Tailandia", fr: "Thaïlande" },
  TJ: { en: "Tajikistan", es: "Tayikistán", fr: "Tadjikistan" },
  TK: { en: "Tokelau", es: "Tokelau", fr: "Tokelau" },
  TL: { en: "Timor-Leste", es: "Timor Oriental", fr: "Timor oriental" },
  TM: { en: "Turkmenistan", es: "Turkmenistán", fr: "Turkménistan" },
  TN: { en: "Tunisia", es: "Túnez", fr: "Tunisie" },
  TO: { en: "Tonga", es: "Tonga", fr: "Tonga" },
  TR: { en: "Türkiye", es: "Turquía", fr: "Turquie" },
  TT: { en: "Trinidad & Tobago", es: "Trinidad y Tobago", fr: "Trinité-et-Tobago" },
  TV: { en: "Tuvalu", es: "Tuvalu", fr: "Tuvalu" },
  TW: { en: "Taiwan", es: "Taiwán", fr: "Taïwan" },
  TZ: { en: "Tanzania", es: "Tanzania", fr: "Tanzanie" },
  UA: { en: "Ukraine", es: "Ucrania", fr: "Ukraine" },
  UG: { en: "Uganda", es: "Uganda", fr: "Ouganda" },
  UM: {
    en: "U.S. Outlying Islands",
    es: "Islas menores alejadas de EE. UU.",
    fr: "Îles mineures éloignées des États-Unis",
  },
  US: { en: "United States", es: "Estados Unidos", fr: "États-Unis" },
  UY: { en: "Uruguay", es: "Uruguay", fr: "Uruguay" },
  UZ: { en: "Uzbekistan", es: "Uzbekistán", fr: "Ouzbékistan" },
  VA: { en: "Vatican City", es: "Ciudad del Vaticano", fr: "État de la Cité du Vatican" },
  VC: {
    en: "St. Vincent & Grenadines",
    es: "San Vicente y las Granadinas",
    fr: "Saint-Vincent-et-les Grenadines",
  },
  VE: { en: "Venezuela", es: "Venezuela", fr: "Venezuela" },
  VG: {
    en: "British Virgin Islands",
    es: "Islas Vírgenes Británicas",
    fr: "Îles Vierges britanniques",
  },
  VI: {
    en: "U.S. Virgin Islands",
    es: "Islas Vírgenes de EE. UU.",
    fr: "Îles Vierges des États-Unis",
  },
  VN: { en: "Vietnam", es: "Vietnam", fr: "Viêt Nam" },
  VU: { en: "Vanuatu", es: "Vanuatu", fr: "Vanuatu" },
  WF: { en: "Wallis & Futuna", es: "Wallis y Futuna", fr: "Wallis-et-Futuna" },
  WS: { en: "Samoa", es: "Samoa", fr: "Samoa" },
  YE: { en: "Yemen", es: "Yemen", fr: "Yémen" },
  YT: { en: "Mayotte", es: "Mayotte", fr: "Mayotte" },
  ZA: { en: "South Africa", es: "Sudáfrica", fr: "Afrique du Sud" },
  ZM: { en: "Zambia", es: "Zambia", fr: "Zambie" },
  ZW: { en: "Zimbabwe", es: "Zimbabue", fr: "Zimbabwe" },
};
