// The canonical ISO 639-1 languages, named from CLDR in every registered UI
// locale. Deprecated aliases (iw, in, jw, ji, mo) and CLDR name collisions
// (tw) were left out when the list was first drawn up.
//
// The names are filled in by scripts/generate-locale-names.mjs, which adds a
// column for a newly registered locale and never rewrites a name already
// here. The rows themselves — which codes exist, and their `asr` and `gen`
// flags — are edited by hand.
// Languages outside ISO 639-1 are not in the registry today; add them as a
// hand-curated list beside this file.

import type { Language } from "./languages";

export const WORLD_LANGUAGES: readonly Language[] = [
  { code: "aa", label: { en: "Afar", es: "afar", fr: "afar" }, asr: false, gen: false },
  { code: "ab", label: { en: "Abkhazian", es: "abjasio", fr: "abkhaze" }, asr: false, gen: false },
  { code: "ae", label: { en: "Avestan", es: "avéstico", fr: "avestique" }, asr: false, gen: false },
  {
    code: "af",
    label: { en: "Afrikaans", es: "afrikáans", fr: "afrikaans" },
    asr: false,
    gen: false,
  },
  { code: "ak", label: { en: "Akan", es: "akan", fr: "akan" }, asr: false, gen: false },
  { code: "am", label: { en: "Amharic", es: "amárico", fr: "amharique" }, asr: false, gen: false },
  {
    code: "an",
    label: { en: "Aragonese", es: "aragonés", fr: "aragonais" },
    asr: false,
    gen: false,
  },
  { code: "ar", label: { en: "Arabic", es: "árabe", fr: "arabe" }, asr: false, gen: true },
  { code: "as", label: { en: "Assamese", es: "asamés", fr: "assamais" }, asr: false, gen: false },
  { code: "av", label: { en: "Avaric", es: "avar", fr: "avar" }, asr: false, gen: false },
  { code: "ay", label: { en: "Aymara", es: "aimara", fr: "aymara" }, asr: false, gen: false },
  {
    code: "az",
    label: { en: "Azerbaijani", es: "azerbaiyano", fr: "azerbaïdjanais" },
    asr: false,
    gen: false,
  },
  { code: "ba", label: { en: "Bashkir", es: "baskir", fr: "bachkir" }, asr: false, gen: false },
  {
    code: "be",
    label: { en: "Belarusian", es: "bielorruso", fr: "biélorusse" },
    asr: false,
    gen: false,
  },
  { code: "bg", label: { en: "Bulgarian", es: "búlgaro", fr: "bulgare" }, asr: false, gen: false },
  {
    code: "bh",
    label: { en: "Bhojpuri", es: "bhoshpuri", fr: "bhodjpouri" },
    asr: false,
    gen: false,
  },
  { code: "bi", label: { en: "Bislama", es: "bislama", fr: "bichelamar" }, asr: false, gen: false },
  { code: "bm", label: { en: "Bambara", es: "bambara", fr: "bambara" }, asr: false, gen: false },
  { code: "bn", label: { en: "Bangla", es: "bengalí", fr: "bengali" }, asr: false, gen: true },
  { code: "bo", label: { en: "Tibetan", es: "tibetano", fr: "tibétain" }, asr: false, gen: false },
  { code: "br", label: { en: "Breton", es: "bretón", fr: "breton" }, asr: false, gen: false },
  { code: "bs", label: { en: "Bosnian", es: "bosnio", fr: "bosniaque" }, asr: false, gen: false },
  { code: "ca", label: { en: "Catalan", es: "catalán", fr: "catalan" }, asr: false, gen: false },
  {
    code: "ce",
    label: { en: "Chechen", es: "checheno", fr: "tchétchène" },
    asr: false,
    gen: false,
  },
  { code: "ch", label: { en: "Chamorro", es: "chamorro", fr: "chamorro" }, asr: false, gen: false },
  { code: "co", label: { en: "Corsican", es: "corso", fr: "corse" }, asr: false, gen: false },
  { code: "cr", label: { en: "Cree", es: "cree", fr: "cree" }, asr: false, gen: false },
  { code: "cs", label: { en: "Czech", es: "checo", fr: "tchèque" }, asr: false, gen: true },
  {
    code: "cu",
    label: { en: "Church Slavic", es: "eslavo eclesiástico", fr: "slavon d’église" },
    asr: false,
    gen: false,
  },
  {
    code: "cv",
    label: { en: "Chuvash", es: "chuvasio", fr: "tchouvache" },
    asr: false,
    gen: false,
  },
  { code: "cy", label: { en: "Welsh", es: "galés", fr: "gallois" }, asr: false, gen: false },
  { code: "da", label: { en: "Danish", es: "danés", fr: "danois" }, asr: false, gen: true },
  { code: "de", label: { en: "German", es: "alemán", fr: "allemand" }, asr: true, gen: true },
  { code: "dv", label: { en: "Divehi", es: "divehi", fr: "maldivien" }, asr: false, gen: false },
  { code: "dz", label: { en: "Dzongkha", es: "dzongkha", fr: "dzongkha" }, asr: false, gen: false },
  { code: "ee", label: { en: "Ewe", es: "ewé", fr: "éwé" }, asr: false, gen: false },
  { code: "el", label: { en: "Greek", es: "griego", fr: "grec" }, asr: false, gen: true },
  { code: "en", label: { en: "English", es: "inglés", fr: "anglais" }, asr: true, gen: true },
  {
    code: "eo",
    label: { en: "Esperanto", es: "esperanto", fr: "espéranto" },
    asr: false,
    gen: false,
  },
  { code: "es", label: { en: "Spanish", es: "español", fr: "espagnol" }, asr: true, gen: true },
  { code: "et", label: { en: "Estonian", es: "estonio", fr: "estonien" }, asr: false, gen: false },
  { code: "eu", label: { en: "Basque", es: "euskera", fr: "basque" }, asr: false, gen: false },
  { code: "fa", label: { en: "Persian", es: "persa", fr: "persan" }, asr: false, gen: true },
  { code: "ff", label: { en: "Fula", es: "fula", fr: "peul" }, asr: false, gen: false },
  { code: "fi", label: { en: "Finnish", es: "finés", fr: "finnois" }, asr: false, gen: true },
  { code: "fj", label: { en: "Fijian", es: "fiyiano", fr: "fidjien" }, asr: false, gen: false },
  { code: "fo", label: { en: "Faroese", es: "feroés", fr: "féroïen" }, asr: false, gen: false },
  { code: "fr", label: { en: "French", es: "francés", fr: "français" }, asr: true, gen: true },
  {
    code: "fy",
    label: { en: "Western Frisian", es: "frisón occidental", fr: "frison occidental" },
    asr: false,
    gen: false,
  },
  { code: "ga", label: { en: "Irish", es: "irlandés", fr: "irlandais" }, asr: false, gen: false },
  {
    code: "gd",
    label: { en: "Scottish Gaelic", es: "gaélico escocés", fr: "gaélique écossais" },
    asr: false,
    gen: false,
  },
  { code: "gl", label: { en: "Galician", es: "gallego", fr: "galicien" }, asr: false, gen: false },
  { code: "gn", label: { en: "Guarani", es: "guaraní", fr: "guarani" }, asr: false, gen: false },
  {
    code: "gu",
    label: { en: "Gujarati", es: "guyaratí", fr: "goudjarati" },
    asr: false,
    gen: false,
  },
  { code: "gv", label: { en: "Manx", es: "manés", fr: "mannois" }, asr: false, gen: false },
  { code: "ha", label: { en: "Hausa", es: "hausa", fr: "haoussa" }, asr: false, gen: false },
  { code: "he", label: { en: "Hebrew", es: "hebreo", fr: "hébreu" }, asr: false, gen: true },
  { code: "hi", label: { en: "Hindi", es: "hindi", fr: "hindi" }, asr: true, gen: true },
  {
    code: "ho",
    label: { en: "Hiri Motu", es: "hiri motu", fr: "hiri motu" },
    asr: false,
    gen: false,
  },
  { code: "hr", label: { en: "Croatian", es: "croata", fr: "croate" }, asr: false, gen: false },
  {
    code: "ht",
    label: { en: "Haitian Creole", es: "haitiano", fr: "créole haïtien" },
    asr: false,
    gen: false,
  },
  { code: "hu", label: { en: "Hungarian", es: "húngaro", fr: "hongrois" }, asr: false, gen: true },
  { code: "hy", label: { en: "Armenian", es: "armenio", fr: "arménien" }, asr: false, gen: false },
  { code: "hz", label: { en: "Herero", es: "herero", fr: "héréro" }, asr: false, gen: false },
  {
    code: "ia",
    label: { en: "Interlingua", es: "interlingua", fr: "interlingua" },
    asr: false,
    gen: false,
  },
  {
    code: "id",
    label: { en: "Indonesian", es: "indonesio", fr: "indonésien" },
    asr: false,
    gen: true,
  },
  {
    code: "ie",
    label: { en: "Interlingue", es: "interlingue", fr: "interlingue" },
    asr: false,
    gen: false,
  },
  { code: "ig", label: { en: "Igbo", es: "igbo", fr: "igbo" }, asr: false, gen: false },
  {
    code: "ii",
    label: { en: "Sichuan Yi", es: "yi de Sichuán", fr: "yi du Sichuan" },
    asr: false,
    gen: false,
  },
  { code: "ik", label: { en: "Inupiaq", es: "inupiaq", fr: "inupiaq" }, asr: false, gen: false },
  { code: "io", label: { en: "Ido", es: "ido", fr: "ido" }, asr: false, gen: false },
  {
    code: "is",
    label: { en: "Icelandic", es: "islandés", fr: "islandais" },
    asr: false,
    gen: false,
  },
  { code: "it", label: { en: "Italian", es: "italiano", fr: "italien" }, asr: true, gen: true },
  {
    code: "iu",
    label: { en: "Inuktitut", es: "inuktitut", fr: "inuktitut" },
    asr: false,
    gen: false,
  },
  { code: "ja", label: { en: "Japanese", es: "japonés", fr: "japonais" }, asr: true, gen: true },
  { code: "jv", label: { en: "Javanese", es: "javanés", fr: "javanais" }, asr: false, gen: false },
  {
    code: "ka",
    label: { en: "Georgian", es: "georgiano", fr: "géorgien" },
    asr: false,
    gen: false,
  },
  { code: "kg", label: { en: "Kongo", es: "kongo", fr: "kikongo" }, asr: false, gen: false },
  { code: "ki", label: { en: "Kikuyu", es: "kikuyu", fr: "kikuyu" }, asr: false, gen: false },
  { code: "kj", label: { en: "Kuanyama", es: "kuanyama", fr: "kuanyama" }, asr: false, gen: false },
  { code: "kk", label: { en: "Kazakh", es: "kazajo", fr: "kazakh" }, asr: false, gen: false },
  {
    code: "kl",
    label: { en: "Kalaallisut", es: "groenlandés", fr: "groenlandais" },
    asr: false,
    gen: false,
  },
  { code: "km", label: { en: "Khmer", es: "jemer", fr: "khmer" }, asr: false, gen: false },
  { code: "kn", label: { en: "Kannada", es: "canarés", fr: "kannada" }, asr: false, gen: false },
  { code: "ko", label: { en: "Korean", es: "coreano", fr: "coréen" }, asr: true, gen: true },
  { code: "kr", label: { en: "Kanuri", es: "kanuri", fr: "kanouri" }, asr: false, gen: false },
  {
    code: "ks",
    label: { en: "Kashmiri", es: "cachemir", fr: "cachemiri" },
    asr: false,
    gen: false,
  },
  { code: "ku", label: { en: "Kurdish", es: "kurdo", fr: "kurde" }, asr: false, gen: false },
  { code: "kv", label: { en: "Komi", es: "komi", fr: "komi" }, asr: false, gen: false },
  { code: "kw", label: { en: "Cornish", es: "córnico", fr: "cornique" }, asr: false, gen: false },
  { code: "ky", label: { en: "Kyrgyz", es: "kirguís", fr: "kirghize" }, asr: false, gen: false },
  { code: "la", label: { en: "Latin", es: "latín", fr: "latin" }, asr: false, gen: false },
  {
    code: "lb",
    label: { en: "Luxembourgish", es: "luxemburgués", fr: "luxembourgeois" },
    asr: false,
    gen: false,
  },
  { code: "lg", label: { en: "Ganda", es: "ganda", fr: "ganda" }, asr: false, gen: false },
  {
    code: "li",
    label: { en: "Limburgish", es: "limburgués", fr: "limbourgeois" },
    asr: false,
    gen: false,
  },
  { code: "ln", label: { en: "Lingala", es: "lingala", fr: "lingala" }, asr: false, gen: false },
  { code: "lo", label: { en: "Lao", es: "lao", fr: "lao" }, asr: false, gen: false },
  {
    code: "lt",
    label: { en: "Lithuanian", es: "lituano", fr: "lituanien" },
    asr: false,
    gen: false,
  },
  {
    code: "lu",
    label: { en: "Luba-Katanga", es: "luba-katanga", fr: "luba-katanga (kiluba)" },
    asr: false,
    gen: false,
  },
  { code: "lv", label: { en: "Latvian", es: "letón", fr: "letton" }, asr: false, gen: false },
  { code: "mg", label: { en: "Malagasy", es: "malgache", fr: "malgache" }, asr: false, gen: false },
  {
    code: "mh",
    label: { en: "Marshallese", es: "marshalés", fr: "marshallais" },
    asr: false,
    gen: false,
  },
  { code: "mi", label: { en: "Māori", es: "maorí", fr: "maori" }, asr: false, gen: false },
  {
    code: "mk",
    label: { en: "Macedonian", es: "macedonio", fr: "macédonien" },
    asr: false,
    gen: false,
  },
  {
    code: "ml",
    label: { en: "Malayalam", es: "malabar", fr: "malayalam" },
    asr: false,
    gen: false,
  },
  { code: "mn", label: { en: "Mongolian", es: "mongol", fr: "mongol" }, asr: false, gen: false },
  { code: "mr", label: { en: "Marathi", es: "maratí", fr: "marathi" }, asr: false, gen: false },
  { code: "ms", label: { en: "Malay", es: "malayo", fr: "malais" }, asr: false, gen: true },
  { code: "mt", label: { en: "Maltese", es: "maltés", fr: "maltais" }, asr: false, gen: false },
  { code: "my", label: { en: "Burmese", es: "birmano", fr: "birman" }, asr: false, gen: false },
  { code: "na", label: { en: "Nauru", es: "nauruano", fr: "nauruan" }, asr: false, gen: false },
  {
    code: "nb",
    label: { en: "Norwegian Bokmål", es: "noruego bokmal", fr: "norvégien bokmål" },
    asr: false,
    gen: false,
  },
  {
    code: "nd",
    label: { en: "North Ndebele", es: "ndebele septentrional", fr: "ndébélé du Nord" },
    asr: false,
    gen: false,
  },
  { code: "ne", label: { en: "Nepali", es: "nepalí", fr: "népalais" }, asr: false, gen: false },
  { code: "ng", label: { en: "Ndonga", es: "ndonga", fr: "ndonga" }, asr: false, gen: false },
  { code: "nl", label: { en: "Dutch", es: "neerlandés", fr: "néerlandais" }, asr: true, gen: true },
  {
    code: "nn",
    label: { en: "Norwegian Nynorsk", es: "noruego nynorsk", fr: "norvégien nynorsk" },
    asr: false,
    gen: false,
  },
  { code: "no", label: { en: "Norwegian", es: "noruego", fr: "norvégien" }, asr: false, gen: true },
  {
    code: "nr",
    label: { en: "South Ndebele", es: "ndebele meridional", fr: "ndébélé du Sud" },
    asr: false,
    gen: false,
  },
  { code: "nv", label: { en: "Navajo", es: "navajo", fr: "navajo" }, asr: false, gen: false },
  { code: "ny", label: { en: "Nyanja", es: "nyanja", fr: "chewa" }, asr: false, gen: false },
  { code: "oc", label: { en: "Occitan", es: "occitano", fr: "occitan" }, asr: false, gen: false },
  { code: "oj", label: { en: "Ojibwa", es: "ojibwa", fr: "ojibwa" }, asr: false, gen: false },
  { code: "om", label: { en: "Oromo", es: "oromo", fr: "oromo" }, asr: false, gen: false },
  { code: "or", label: { en: "Odia", es: "oriya", fr: "odia" }, asr: false, gen: false },
  { code: "os", label: { en: "Ossetic", es: "osético", fr: "ossète" }, asr: false, gen: false },
  { code: "pa", label: { en: "Punjabi", es: "punyabí", fr: "pendjabi" }, asr: false, gen: false },
  { code: "pi", label: { en: "Pali", es: "pali", fr: "pali" }, asr: false, gen: false },
  { code: "pl", label: { en: "Polish", es: "polaco", fr: "polonais" }, asr: false, gen: true },
  { code: "ps", label: { en: "Pashto", es: "pastún", fr: "pachto" }, asr: false, gen: false },
  {
    code: "pt",
    label: { en: "Portuguese", es: "portugués", fr: "portugais" },
    asr: true,
    gen: true,
  },
  { code: "qu", label: { en: "Quechua", es: "quechua", fr: "quechua" }, asr: false, gen: false },
  {
    code: "rm",
    label: { en: "Romansh", es: "retorrománico", fr: "romanche" },
    asr: false,
    gen: false,
  },
  { code: "rn", label: { en: "Rundi", es: "kirundi", fr: "roundi" }, asr: false, gen: false },
  { code: "ro", label: { en: "Romanian", es: "rumano", fr: "roumain" }, asr: false, gen: true },
  { code: "ru", label: { en: "Russian", es: "ruso", fr: "russe" }, asr: true, gen: true },
  {
    code: "rw",
    label: { en: "Kinyarwanda", es: "kinyarwanda", fr: "kinyarwanda" },
    asr: false,
    gen: false,
  },
  {
    code: "sa",
    label: { en: "Sanskrit", es: "sánscrito", fr: "sanskrit" },
    asr: false,
    gen: false,
  },
  { code: "sc", label: { en: "Sardinian", es: "sardo", fr: "sarde" }, asr: false, gen: false },
  { code: "sd", label: { en: "Sindhi", es: "sindhi", fr: "sindhi" }, asr: false, gen: false },
  {
    code: "se",
    label: { en: "Northern Sami", es: "sami septentrional", fr: "same du Nord" },
    asr: false,
    gen: false,
  },
  { code: "sg", label: { en: "Sango", es: "sango", fr: "sango" }, asr: false, gen: false },
  {
    code: "sh",
    label: { en: "Serbian (Latin)", es: "serbio (latín)", fr: "serbe (latin)" },
    asr: false,
    gen: false,
  },
  { code: "si", label: { en: "Sinhala", es: "cingalés", fr: "cingalais" }, asr: false, gen: false },
  { code: "sk", label: { en: "Slovak", es: "eslovaco", fr: "slovaque" }, asr: false, gen: false },
  { code: "sl", label: { en: "Slovenian", es: "esloveno", fr: "slovène" }, asr: false, gen: false },
  { code: "sm", label: { en: "Samoan", es: "samoano", fr: "samoan" }, asr: false, gen: false },
  { code: "sn", label: { en: "Shona", es: "shona", fr: "shona" }, asr: false, gen: false },
  { code: "so", label: { en: "Somali", es: "somalí", fr: "somali" }, asr: false, gen: false },
  { code: "sq", label: { en: "Albanian", es: "albanés", fr: "albanais" }, asr: false, gen: false },
  { code: "sr", label: { en: "Serbian", es: "serbio", fr: "serbe" }, asr: false, gen: false },
  { code: "ss", label: { en: "Swati", es: "siswati", fr: "swati" }, asr: false, gen: false },
  {
    code: "st",
    label: { en: "Southern Sotho", es: "sesotho del sur", fr: "sotho du Sud" },
    asr: false,
    gen: false,
  },
  {
    code: "su",
    label: { en: "Sundanese", es: "sundanés", fr: "soundanais" },
    asr: false,
    gen: false,
  },
  { code: "sv", label: { en: "Swedish", es: "sueco", fr: "suédois" }, asr: false, gen: true },
  { code: "sw", label: { en: "Swahili", es: "suajili", fr: "swahili" }, asr: false, gen: false },
  { code: "ta", label: { en: "Tamil", es: "tamil", fr: "tamoul" }, asr: false, gen: true },
  { code: "te", label: { en: "Telugu", es: "telugu", fr: "télougou" }, asr: false, gen: false },
  { code: "tg", label: { en: "Tajik", es: "tayiko", fr: "tadjik" }, asr: false, gen: false },
  { code: "th", label: { en: "Thai", es: "tailandés", fr: "thaï" }, asr: false, gen: true },
  { code: "ti", label: { en: "Tigrinya", es: "tigriña", fr: "tigrigna" }, asr: false, gen: false },
  { code: "tk", label: { en: "Turkmen", es: "turcomano", fr: "turkmène" }, asr: false, gen: false },
  { code: "tl", label: { en: "Filipino", es: "filipino", fr: "filipino" }, asr: false, gen: false },
  { code: "tn", label: { en: "Tswana", es: "setsuana", fr: "tswana" }, asr: false, gen: false },
  { code: "to", label: { en: "Tongan", es: "tongano", fr: "tongien" }, asr: false, gen: false },
  { code: "tr", label: { en: "Turkish", es: "turco", fr: "turc" }, asr: false, gen: true },
  { code: "ts", label: { en: "Tsonga", es: "tsonga", fr: "tsonga" }, asr: false, gen: false },
  { code: "tt", label: { en: "Tatar", es: "tártaro", fr: "tatar" }, asr: false, gen: false },
  {
    code: "ty",
    label: { en: "Tahitian", es: "tahitiano", fr: "tahitien" },
    asr: false,
    gen: false,
  },
  { code: "ug", label: { en: "Uyghur", es: "uigur", fr: "ouïghour" }, asr: false, gen: false },
  {
    code: "uk",
    label: { en: "Ukrainian", es: "ucraniano", fr: "ukrainien" },
    asr: false,
    gen: true,
  },
  { code: "ur", label: { en: "Urdu", es: "urdu", fr: "ourdou" }, asr: false, gen: false },
  { code: "uz", label: { en: "Uzbek", es: "uzbeko", fr: "ouzbek" }, asr: false, gen: false },
  { code: "ve", label: { en: "Venda", es: "venda", fr: "venda" }, asr: false, gen: false },
  {
    code: "vi",
    label: { en: "Vietnamese", es: "vietnamita", fr: "vietnamien" },
    asr: false,
    gen: true,
  },
  { code: "vo", label: { en: "Volapük", es: "volapük", fr: "volapük" }, asr: false, gen: false },
  { code: "wa", label: { en: "Walloon", es: "valón", fr: "wallon" }, asr: false, gen: false },
  { code: "wo", label: { en: "Wolof", es: "wólof", fr: "wolof" }, asr: false, gen: false },
  { code: "xh", label: { en: "Xhosa", es: "xhosa", fr: "xhosa" }, asr: false, gen: false },
  { code: "yi", label: { en: "Yiddish", es: "yidis", fr: "yiddish" }, asr: false, gen: false },
  { code: "yo", label: { en: "Yoruba", es: "yoruba", fr: "yoruba" }, asr: false, gen: false },
  { code: "za", label: { en: "Zhuang", es: "zhuang", fr: "zhuang" }, asr: false, gen: false },
  { code: "zh", label: { en: "Chinese", es: "chino", fr: "chinois" }, asr: true, gen: true },
  { code: "zu", label: { en: "Zulu", es: "zulú", fr: "zoulou" }, asr: false, gen: false },
];
