import { palette, paletteDark } from "@spiralclass/shared";
import { describe, expect, it } from "vitest";
import { WCAG, contrastRatio } from "./contrast";

/**
 * Bare AA is not enough for a token that ships through the CSS mirror.
 *
 * globals.css stores each colour as `H S% L%` rounded to whole numbers, so what
 * the browser paints can sit up to about seven units per channel from the hex
 * this file reads. Six semantic pairings were solved to clear exactly 4.5 here,
 * passed, and then failed axe in the browser at 4.39-4.44 — the drift is enough
 * on its own to break AA.
 *
 * So the tinted-ground pairs are held above 5.0. The extra is the mirror's
 * rounding error, budgeted here rather than discovered in an accessibility run.
 */
const AA_WITH_MIRROR_HEADROOM = 5;

/**
 * Every pairing the design system asserts is legible, checked in both themes.
 *
 * This is the test the old palette did not have, and its absence is the whole
 * reason D-140 was needed: twenty-nine colours were chosen by eye and then
 * assigned roles, so four of the roles could not be performed. The gold
 * documented as "the brand's SECOND colour, for highlights and secondary
 * emphasis" sat at 2.16:1 and could not carry text anywhere. Dark-mode error
 * text failed at 4.19:1 — the one colour that most needs to be readable.
 *
 * A contrast failure is not a matter of taste, so it is not left to review.
 *
 * When this fails, do NOT lower the threshold. The value is solvable: the
 * palette is generated by searching OKLCH lightness for the smallest step that
 * clears the ratio its role requires, so a failing colour means the search
 * needs re-running, not that the rule is too strict.
 */

type Palette = typeof palette;
type Pair = [fg: keyof Palette, bg: keyof Palette, min: number];

/** The grounds a foreground can legitimately land on. */
const SURFACES = ["background", "surface", "muted", "secondary"] as const;

const TEXT_ON_EVERY_SURFACE: Pair[] = SURFACES.flatMap((bg): Pair[] => [
  // Body text targets AAA, not AA. It is also deliberately short of
  // black-on-white's 21:1 — see the glare guard at the bottom.
  ["text", bg, WCAG.AAA],
  ["textMuted", bg, WCAG.AA],
  // `primary` AS TEXT, added 2026-09-01 — the pairing whose absence is the
  // reason this file exists in the first place, repeated.
  //
  // `primary` does two jobs. Below, `primaryText` on `primary` verifies it as a
  // button FILL, and that was read as "primary is covered". It is also
  // `text-primary` — the link and emphasis colour at 50 call sites and, until
  // the same change, the default Badge — and in that role it landed on these
  // four surfaces with nothing checking it. Dark mode measured 3.49:1 on the
  // raised card, 3.68 on `secondary`, 4.18 on `muted`. axe found it; this
  // suite could not, because a pairing that is not listed is not tested.
  //
  // The general shape is the one D-140's own correction names: a guard is only
  // as good as the set of things it is pointed at, and "the token appears
  // somewhere in the list" is not the same as "every role it performs is
  // solved".
  ["primary", bg, WCAG.AA],
]);

const PAIRS: Pair[] = [
  ...TEXT_ON_EVERY_SURFACE,
  ["textSubtle", "background", WCAG.AA],
  ["textSubtle", "surface", WCAG.AA],
  ["textSubtle", "muted", WCAG.AA],
  // Filled controls, each against the foreground the system puts on it. These
  // are the pairings that were inverting in dark mode, because both sides read
  // a theme-dependent token over a fill that was not.
  ["primaryText", "primary", WCAG.AA],
  ["accentText", "accent", WCAG.AA],
  ["dangerText", "danger", WCAG.AA],
  ["secondaryText", "secondary", WCAG.AA],
  ["mutedText", "muted", WCAG.AA],
  // Status text on its own tinted ground — the Badge and Alert variants.
  //
  // These pairings were being asserted while the components used
  // `bg-success/15`, a DIFFERENT colour composited against the page, which axe
  // caught failing on the dashboard. The tinted grounds existed in this palette
  // from the start and were never mirrored into CSS, so no utility could reach
  // them. They can now, the variants use them, and this assertion finally
  // describes what ships.
  ["success", "successBg", AA_WITH_MIRROR_HEADROOM],
  ["warning", "warningBg", AA_WITH_MIRROR_HEADROOM],
  ["danger", "dangerBg", AA_WITH_MIRROR_HEADROOM],
  ["info", "infoBg", AA_WITH_MIRROR_HEADROOM],
  ["clay", "clayBg", AA_WITH_MIRROR_HEADROOM],
  ["sage", "sageBg", AA_WITH_MIRROR_HEADROOM],
  // ...and on the page, where the same colours are used as plain text.
  ["success", "background", WCAG.AA],
  ["warning", "background", WCAG.AA],
  ["danger", "background", WCAG.AA],
  ["info", "background", WCAG.AA],
  // A control boundary is non-text UI: WCAG 1.4.11 wants 3:1. The old `border`
  // token sat at 1.39:1, which made every input outline effectively invisible
  // in a product that is roughly ninety forms.
  ["borderStrong", "background", WCAG.AA_LARGE],
  ["borderStrong", "surface", WCAG.AA_LARGE],
  ["borderStrong", "secondary", WCAG.AA_LARGE],
];

describe.each([
  ["light", palette],
  ["dark", paletteDark],
])("%s palette", (themeName, theme) => {
  it.each(PAIRS)("%s on %s clears %f:1", (fg, bg, min) => {
    const ratio = contrastRatio(theme[fg], theme[bg]);
    // The fix is always to re-solve the colour, never to lower `min`. Name the
    // command that does it: telling someone to "re-run the OKLCH solve" without
    // saying how is what left the solve uncommitted and done by hand, which is
    // how dark textSubtle/borderStrong drifted below AA when the raised surface
    // moved. `--darker` searches downward, for a colour on a light ground.
    const solve =
      `node scripts/solve-contrast.mjs '${theme[fg]}' '${theme[bg]}' ${min}` +
      (themeName === "light" ? " --darker" : "");
    expect(
      Number(ratio.toFixed(2)),
      `${themeName}: ${fg} (${theme[fg]}) on ${bg} (${theme[bg]}) is ${ratio.toFixed(2)}:1, ` +
        `needs ${min}:1. Re-solve rather than lowering the threshold:\n  ${solve}`,
    ).toBeGreaterThanOrEqual(min);
  });

  it("keeps body text short of the luminance extreme", () => {
    // The counterpart to every assertion above: contrast can also be too high.
    // Black on white is 21:1 and is the pairing most often reported as causing
    // glare and apparent letter movement, which is the opposite of what D-140
    // is for. The palette targets about 13:1.
    const ratio = contrastRatio(theme.text, theme.surface);
    expect(ratio, `${themeName}: body text is ${ratio.toFixed(1)}:1 — too stark`).toBeLessThan(16);
  });

  it("never renders a ground on itself", () => {
    // Cheap, and it catches the copy-paste that a ratio check would report as
    // a mysterious 1:1 somewhere else entirely.
    const grounds = SURFACES.map((s) => theme[s]);
    expect(new Set(grounds).size, `${themeName}: two surfaces share a value`).toBe(grounds.length);
  });
});
