// Input validation schemas (Zod) now live in @spiralclass/shared so the mobile
// client can validate the same shapes with the same localized messages instead
// of sending unchecked input to the web APIs. Re-exported here so existing
// `@/lib/validators` imports keep working. Add/edit schemas in
// packages/shared/src/validators.ts.
export {
  isValidTimezone,
  signUpSchema,
  type SignUpInput,
  signInSchema,
  type SignInInput,
  phoneSignInSchema,
  type PhoneSignInInput,
  phoneCodeSchema,
  type PhoneCodeInput,
  timezoneSchema,
  type TimezoneInput,
  availabilityRangeSchema,
  availabilitySchema,
  type AvailabilityInput,
  blockedDateSchema,
  type BlockedDateInput,
  packageTemplateSchema,
  templatesSchema,
  type TemplatesInput,
  bookingRequestSchema,
  type BookingRequestInput,
  checkoutIntentSchema,
  type CheckoutIntentInput,
  leadCaptureSchema,
  type LeadCaptureInput,
  studentContactSchema,
  type StudentContactInput,
  teacherContactSchema,
  type TeacherContactInput,
  teacherPublicWhatsappSchema,
  type TeacherPublicWhatsappInput,
  teacherEditStudentContactSchema,
  type TeacherEditStudentContactInput,
  teacherCreateStudentSchema,
  type TeacherCreateStudentInput,
  portalCheckoutIntentSchema,
  type PortalCheckoutIntentInput,
  wiseInstrumentSchema,
  type WiseInstrumentInput,
  transferConfirmSchema,
  singleInviteSchema,
  type SingleInviteInput,
  bulkInviteSchema,
  type BulkInviteInput,
  invitationActionSchema,
  type InvitationActionInput,
} from "@spiralclass/shared";
